### ISSUE TITLE
Just Install devops on the ready-made member cluster, but console shows not installed

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#1007]
I just installed devops on the ready-made member cluster. But console show it is not installed on member.

![image](https://user-images.githubusercontent.com/22350668/88755820-90078b80-d194-11ea-8aaf-8791011be580.png)

**Comment by zryfish** [comment]
Check the output of the following command, make everything is setup as expected
```
kubectl -n kubesphere-system get cm kubesphere-config
```
