### ISSUE TITLE
Pipeline description is never displayed

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#1024]
Here is the place for user to edit pipeline description, but what's the purpose for this feature? This data is never used.

![image](https://user-images.githubusercontent.com/22350668/88876447-dffa5700-d255-11ea-892a-cc88bce22984.png)

**Comment by harrisonliu5** [comment]
https://github.com/kubesphere/kubesphere/issues/2811

**Comment by rayzhou2017** [comment]
verified
