### ISSUE TITLE
wrong custom ws role

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#1025]
**Describe the bug**
`ws-tester8` is the uer with the custom ws role `Workspace Settings`, but log in with the user, it is totally wrong as you can see from the following screenshots. The user is not invited into any project. And the ws settings part is missing items.
![Screen Shot 2020-07-30 at 11 32 31 AM](https://user-images.githubusercontent.com/28859385/88877659-9fe8a380-d258-11ea-879f-15a354052992.png)
![Screen Shot 2020-07-30 at 11 31 38 AM](https://user-images.githubusercontent.com/28859385/88877664-a6771b00-d258-11ea-87fa-df0ed1698d42.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev

**Comment by rayzhou2017** [comment]
same thing on devops @wansir 
![Screen Shot 2020-07-30 at 12 55 06 PM](https://user-images.githubusercontent.com/28859385/88882188-f4455080-d263-11ea-841c-facc9c97b4e4.png)

**Comment by wansir** [comment]
> same thing on devops @wansir
> ![Screen Shot 2020-07-30 at 12 55 06 PM](https://user-images.githubusercontent.com/28859385/88882188-f4455080-d263-11ea-841c-facc9c97b4e4.png)

`kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml`

Update custom ws role to verify.

**Comment by rayzhou2017** [comment]
verified
