### ISSUE TITLE
Got dirty data and error when creating pipelines of the same name as previously existing pipeline 

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#1028]
I created a new pipeline `github` which has the same name of removed pipeline. As you can see the number of RUNs and LAST UPDATE TIME, the console show data from old pipelines.

Besides, I also got errors when viewing run details.

![image](https://user-images.githubusercontent.com/22350668/88888273-99662600-d270-11ea-9d1b-80f471858864.png)

![image](https://user-images.githubusercontent.com/22350668/88888282-9c611680-d270-11ea-8ee0-f3757e96956c.png)

**Comment by shaowenchen** [comment]
It takes a while to delete data for Jenkins. We'd better add a test before Create Pipeline.

**Comment by LinuxSuRen** [comment]
fixed by #3180

/close
