### ISSUE TITLE
Commit records are missing?

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#1029]
![image](https://user-images.githubusercontent.com/22350668/88888804-928be300-d271-11ea-8f78-13c22cb246b4.png)

![image](https://user-images.githubusercontent.com/22350668/88888829-9cade180-d271-11ea-845b-3805c2a7ad66.png)

![image](https://user-images.githubusercontent.com/22350668/88888847-a6374980-d271-11ea-8335-c172a52646ca.png)

![image](https://user-images.githubusercontent.com/22350668/88888861-ad5e5780-d271-11ea-899e-9c76719b4166.png)

![image](https://user-images.githubusercontent.com/22350668/88888904-c0712780-d271-11ea-83ff-3771d72003e9.png)

**Comment by rayzhou2017** [comment]
not fixed. The problem is the commit tab page is empty.
![Screen Shot 2020-08-19 at 4 36 07 PM](https://user-images.githubusercontent.com/28859385/90612198-4a415e80-e23a-11ea-89da-767155123c97.png)

**Comment by harrisonliu5** [comment]
it is the same https://github.com/kubesphere/kubesphere/issues/2861

**Comment by LinuxSuRen** [comment]
I created a GitHub Multi-branch Pipeline. The commit records are incorrect. Please check out the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/108980238-6d0b6e80-76c6-11eb-97ad-3863ddefb1de.png)

hi @harrisonliu5 , it looks like that this is a complex problem. It'd be great if this bugfix could catch up with 3.1.0

/priority medium

# Version
`kubespheredev/ks-console:nightly-20210223`
