### ISSUE TITLE
nothing happens when creating account credentials for devops project and only inputing credential id

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#1046]
**Describe the bug**
When creating account credentials for devops project and only inputing credential id, nothing happens after clicking ok button
![image](https://user-images.githubusercontent.com/49136171/89016287-0fd75680-d34b-11ea-9e34-5671f865c10e.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere(2020-07-31)

/kind bug
/priority medium
/milestone 3.0.0
/area devops
/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
please tell me your env address

**Comment by junotx** [comment]
verified
/close
