### ISSUE TITLE
error when user entered the devops project as a role with empty permissions

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#1070]
**Describe the bug**
the user encountered error as follows when he entered basic info page of the devops project as a role with empty permissions
![image](https://user-images.githubusercontent.com/49136171/89156254-edd51280-d59c-11ea-9e22-2401499c8a03.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere(2020-08-03)

/kind bug
/milestone 3.0.0
/area devops
/assign @leoendless

**Comment by junotx** [comment]
The same error occured for other users who could see the page but have no permissions on viewing members and roles

**Comment by rayzhou2017** [comment]
Any update?

**Comment by junotx** [comment]
verified
/close
