### ISSUE TITLE
js import bug, CAN_SUBMIT_STATUS,   CAN_CANCEL_STATUS,undefind

### ISSUE THREAD

**Issue by ferried** [kubesphere/console#1088]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

I split the console foreground page and converted the server rendering to pure front-end rendering. In the process, I found several problems  

1.Some component import SelectComponent ,But the path was component/Base .  ,There has no SelectComponent exported and I changed it  import { Select } from component/Base  to import { Select } from @pitrix/lego-ui 

2.The problem like NO.1 and i changed it import { Tab } from component/Base to import { Tab } from '@pitrix/lego-ui  

3./src/pages/apps/components/Cards/Versions/ Item.jsx Import{CAN_ DELETE_ STATUS,CAN_ SUBMIT_ STATUS,CAN_ CANCEL_ STATUS,} from 'configs/openpitrix/version'  

Where can_ SUBMIT_ STATUS, CAN_ CANCEL_ Status, not defined  

**Versions used(KubeSphere/Kubernetes)**  

branch master  

**Environment**  

**To Reproduce**

**Expected behavior**

You can fix these little problems  and my version is https://github.com/ferried/my-kubesphere-console

and I'm studying how to extract globals from my cluster and completely staticize the console

**Comment by leoendless** [comment]
What do problems 1 and 2 mean?

**Comment by ferried** [comment]
> What do problems 1 and 2 mean?

i has rewrite the problem

**Comment by leoendless** [comment]
That was a terrible mistake, we will check that totally. Thanks~.

**Comment by leoendless** [comment]
Fixed in v3.0.0
