### ISSUE TITLE
CRD menu and desc are inaccurate

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/console#1100]
**Describe the bug**
English UI's desc is incorrect:
![crd1](https://user-images.githubusercontent.com/18525465/89494076-06853880-d7e8-11ea-9619-3a41d11d0550.png)

English UI's menu should be changed to CRDs
![crd2](https://user-images.githubusercontent.com/18525465/89494138-24529d80-d7e8-11ea-8e01-03513d995d7d.png)

Chinese UI's desc should be changed as well
![crd3](https://user-images.githubusercontent.com/18525465/89494067-038a4800-d7e8-11ea-8e33-e6feed3d54e8.png)

**Comment by rayzhou2017** [comment]
verified
