### ISSUE TITLE
Project quota display doesn't refresh after edit

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/console#1117]
**Describe the bug**
After edit project quota and confirmed, project quota still displays old values, need to reload page or switch out and back to quota tab to display new values.

![image](https://user-images.githubusercontent.com/38337958/89599800-1c036c80-d893-11ea-9e06-f06200b49be5.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.0.0

**Expected behavior**
A immediately refresh after user confirm quota edit.

**Comment by rayzhou2017** [comment]
check if it is fixed

**Comment by rayzhou2017** [comment]
verified
