### ISSUE TITLE
project request/limit is not correct

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#1139]
**Describe the bug**
Using a custom platform role `cluster management` to change the project request/limit, but  the tab page still shows unlimited.
![Screen Shot 2020-08-10 at 2 47 47 PM](https://user-images.githubusercontent.com/28859385/89757811-e2dc2e00-db18-11ea-87d3-6644b90a4895.png)
![Screen Shot 2020-08-10 at 2 47 52 PM](https://user-images.githubusercontent.com/28859385/89757820-e7a0e200-db18-11ea-98c0-fab966415a4c.png)
![Screen Shot 2020-08-10 at 2 51 05 PM](https://user-images.githubusercontent.com/28859385/89757832-eff91d00-db18-11ea-99bf-e38abb7e0b00.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0(2020-08-10)

**Comment by rayzhou2017** [comment]
invalid, this is quota, not container resource request/limit. /cc @leoendless

**Comment by leoendless** [comment]
Did the quota card auto updated?

**Comment by rayzhou2017** [comment]
Not notice. I will check it.

**Comment by rayzhou2017** [comment]
yes, it is updated automatically.
