### ISSUE TITLE
用户在使用私有仓库镜像时，镜像名称需要处理scheme

### ISSUE THREAD

**Issue by runzexia** [kubesphere/console#114]
2.1.1 将允许镜像名称包含 scheme，具体来说，镜像仓库密钥地址包含以下两种情况。

1. 不带scheme
例如： `dockerhub.qingcloud.com`
在这种情况下前端无需特殊处理，镜像名称可能为 `dockerhub.qingcloud.com/runzexia/hello:latest`
2. https/http
例如 `https://dockerhub.qingcloud.com`
在这种情况下前端需要去除镜像仓库地址中的scheme 
错误示例： `https://dockerhub.qingcloud.com/runzexia/hello:latest`  
 `http://dockerhub.qingcloud.com/runzexia/hello:latest`
正确示例:
`dockerhub.qingcloud.com/runzexia/hello:latest`

**Comment by runzexia** [comment]
assign @minghaoye

**Comment by runzexia** [comment]
cc @soulseen

**Comment by soulseen** [comment]
为了更加全面，后端对scheme也做了处理

**Comment by soulseen** [comment]
第二种情况应该是只有使用http时才需要指定加上http协议头，其他情况默认使用https，手动加上了https也是没有关系的吧

**Comment by runzexia** [comment]
@soulseen 现在在创建部署的时候可以选择镜像仓库，如果secret里面包含了 `https://` 会导致用户最终部署的 image 字段为 `https://docker.io/nginx:latest`，这个地方需要前端做处理。

**Comment by soulseen** [comment]
嗯，

**Comment by runzexia** [comment]
fix
/close
