### ISSUE TITLE
[upgrade devops] devopsproject name is not correct

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#1148]
**General remarks**

![image](https://user-images.githubusercontent.com/43693241/89844138-42841900-dbad-11ea-85c8-e421d802e131.png)

**Describe the bug**

There is no generateName. Maybe we should add a label `"kubesphere.io/devopsproject": "real name"` to show. 

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5

**Comment by wansir** [comment]
`generateName` and `name` can be set at the same time during upgrade.
