### ISSUE TITLE
 The console can not display the description information of the storage volume

### ISSUE THREAD

**Issue by yuswift** [kubesphere/console#1151]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
 The console can not display the description information of the storage volume when I add some description.
For UI issues please also add a screenshot that shows the issue.
<img width="1339" alt="Jietu20200811-105234" src="https://user-images.githubusercontent.com/37265389/89852307-27230900-dbc1-11ea-8324-20b489a7765f.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:v3.0.0

**Expected behavior**
The console should display the description information of the storage volume

**Comment by rayzhou2017** [comment]
verified
