### ISSUE TITLE
custom devops role problem

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#1158]
**Describe the bug**
A custom devops role with `Pipelines View / Pipelines Management` can't view pipeline.
<img width="1242" alt="Screen Shot 2020-08-11 at 8 37 11 PM" src="https://user-images.githubusercontent.com/28859385/89898053-9e34bd80-dc12-11ea-853d-1fccd9d8ceb2.png">

<img width="1239" alt="Screen Shot 2020-08-11 at 8 37 00 PM" src="https://user-images.githubusercontent.com/28859385/89898094-b278ba80-dc12-11ea-8197-53280abd4f81.png">
<img width="926" alt="Screen Shot 2020-08-11 at 8 35 42 PM" src="https://user-images.githubusercontent.com/28859385/89898104-b9073200-dc12-11ea-988b-6229276022c3.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0 (2020-08-11)

**Comment by wansir** [comment]
/assign @shaowenchen 

The pipeline list of different users should not be different, empty result is not expected.

**Comment by rayzhou2017** [comment]
BTW, the user is not granted with any platform role.

**Comment by rayzhou2017** [comment]
verified
