### ISSUE TITLE
App update menu is wrong

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#1165]
**Describe the bug**
Here is the upgrade menu. But it pops up with the edit info window.
![Screen Shot 2020-08-13 at 10 06 42 AM](https://user-images.githubusercontent.com/28859385/90086394-ea841880-dd4c-11ea-91e7-29e036663cf1.png)
![Screen Shot 2020-08-13 at 10 06 50 AM](https://user-images.githubusercontent.com/28859385/90086419-f5d74400-dd4c-11ea-923f-7c3cd4bd1641.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0 (2020-08-13)

**Comment by leoendless** [comment]
A mistake. This is a function of the next version.

**Comment by rayzhou2017** [comment]
verified
