### ISSUE TITLE
custom platform role permission denied - multi-cluster project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#1178]
**Describe the bug**
A custom platform role with `cluster view / management` can't open multi-cluster project， multi-cluster workloads, multi-cluster pvc, multi-cluster ingress, mulit-cluster secret, multi-cluster configmap.
![Screen Shot 2020-08-14 at 4 53 35 PM](https://user-images.githubusercontent.com/28859385/90232254-fb1cb780-de4e-11ea-85d2-5ccd8eeb88ce.png)
![Screen Shot 2020-08-14 at 4 58 33 PM](https://user-images.githubusercontent.com/28859385/90232613-84cc8500-de4f-11ea-9f7d-990e5d07d08e.png)
![Screen Shot 2020-08-14 at 4 58 53 PM](https://user-images.githubusercontent.com/28859385/90232644-8eee8380-de4f-11ea-84d9-fc80855d8cbd.png)
![Screen Shot 2020-08-14 at 5 07 20 PM](https://user-images.githubusercontent.com/28859385/90233444-c14cb080-de50-11ea-8c36-9d27011b4c01.png)
![Screen Shot 2020-08-14 at 5 07 29 PM](https://user-images.githubusercontent.com/28859385/90233455-c578ce00-de50-11ea-89dc-0ae3885f6373.png)
![Screen Shot 2020-08-14 at 5 07 51 PM](https://user-images.githubusercontent.com/28859385/90233462-c873be80-de50-11ea-87a0-5f8afa295388.png)

![Screen Shot 2020-08-14 at 4 54 10 PM](https://user-images.githubusercontent.com/28859385/90232302-0c65c400-de4f-11ea-9ae6-df4b7fc34f0a.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0 (2020-08-14)

**Comment by wansir** [comment]
```
kubectl apply -f https://raw.githubusercontent.com/kubesphere/ks-installer/master/roles/ks-core/prepare/files/ks-init/iam-accounts.yaml
```
/kind need-to-verify

Update custom role to verify.

**Comment by rayzhou2017** [comment]
Do I need to restart member cluster services?

**Comment by rayzhou2017** [comment]
verified
