### ISSUE TITLE
no translation for devops credential desc key

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#1183]
**Describe the bug**
<img width="1072" alt="Screen Shot 2020-08-15 at 8 26 13 PM" src="https://user-images.githubusercontent.com/28859385/90312283-b61f8080-df35-11ea-8845-f478082ec002.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0 (2020-08-15)

**Comment by Sherlock113** [comment]
@leoendless Could you have a look at this. I cannot find a separate "_CREATE_DESC" in the locales folder. Besides, I think there should be something between "No" and "Found", like "No Resource Found" or sth, as I cannot find "No Found" in the locales folder either.

**Comment by rayzhou2017** [comment]
verified
