### ISSUE TITLE
Words are squeezed in Resource Request setting page

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#1224]
**To Reproduce**
1. Go to Overview of a new project.
2. Click Set next to Resource Default Request Not Set.

Is it possible that the pop-up window can be larger? Words are squeezed together both for English and Spanish.

![截屏2020-08-27下午1 19 42](https://user-images.githubusercontent.com/65327072/91387919-da9a2780-e868-11ea-92d0-9c295a576032.png)
![截屏2020-08-27下午1 22 10](https://user-images.githubusercontent.com/65327072/91387763-88590680-e868-11ea-977e-7a3a13671cc3.png)

**Comment by jioce** [comment]
issue fixed v3.2.0 
/closed

**Comment by wenxin-01** [comment]
issue fixed in  `v3.2.0`

/close
