### ISSUE TITLE
undefined error when  editing cron parameters of DevOps

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#1250]
**Describe the bug**

There is an undefined parameter in URL when editing the Build Trigger.

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: 3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**To Reproduce**

edit `Build Trigger` 

![image](https://user-images.githubusercontent.com/43693241/95720104-60502600-0ca3-11eb-88eb-00d128f30ccb.png)

/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
URL: kapis/clusters/gondor/devops.kubesphere.io/v1alpha2/devops/test-demo/checkCron

the request is 

``` json

{"cron":"H */4 * * 1-5"}

```

the response is 
``` json
{
  message: "<h1>Bad Message 400</h1><pre>reason: Illegal character SPACE=' '</pre>"
  result: "error"
}
```

**Comment by LinuxSuRen** [comment]
I've tested against with `kubespheredev/ks-console:latest`. It works well. Thanks.
