### ISSUE TITLE
container real-time log shows incomplete

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#1257]
**Describe the bug**

container real-time log shows no tail log：
view container log and that is normal
![image](https://user-images.githubusercontent.com/49136171/96398713-1618f880-11ff-11eb-8819-06811c4fe23e.png)
but switch to real-time log and can not see the tail log
![image](https://user-images.githubusercontent.com/49136171/96398787-49f41e00-11ff-11eb-95e7-4360d0a6255b.png)

**Versions used(KubeSphere/Kubernetes)**

KubeSphere(3.0.0)

**Environment**

single cluster & allinone

/kind bug

**Comment by JohnNiang** [comment]
* Correct log format
![image](https://user-images.githubusercontent.com/16865714/118676591-1d07f800-b82e-11eb-83ef-9b9c7e5f1947.png)

* Log in container log window
![image](https://user-images.githubusercontent.com/16865714/118676666-2beeaa80-b82e-11eb-96fc-c083744fd765.png)

**Comment by JohnNiang** [comment]
And many redundant and unexpected blank lines may be included into the log content.

**Comment by jioce** [comment]
issue still exists
![image](https://user-images.githubusercontent.com/88183150/142346914-15f66df7-2a76-49a3-80c6-88375986bc5f.png)

![image](https://user-images.githubusercontent.com/88183150/142346973-4af6b690-db41-44a8-be20-499c0e3b51d5.png)

version used: 
kubesphere: v3.2.0

**Comment by weili520** [comment]
> issue still exists ![image](https://user-images.githubusercontent.com/88183150/142346914-15f66df7-2a76-49a3-80c6-88375986bc5f.png)
> 
> ![image](https://user-images.githubusercontent.com/88183150/142346973-4af6b690-db41-44a8-be20-499c0e3b51d5.png)> 
> version used: kubesphere: v3.2.0

**Comment by weili520** [comment]
![截屏2021-11-19 14 58 29](https://user-images.githubusercontent.com/33231138/142579294-8da928b5-3e9f-4bdf-b0a7-d936d3007a42.png)

**Comment by weili520** [comment]
I think it is caused by the node.js HTTP receive mechanism. When the HTTP response is chunked, the data didn't lose, it will show with the next response, but the response interval is about 2 minutes.

**Comment by JohnNiang** [comment]
> I think it is caused by the node.js HTTP receive mechanism. When the HTTP response is chunked, the data didn't lose, it will show with the next response, but the response interval is about 2 minutes.

Hi @weili520 , if you don't have a better solution now, you could refer to an existing implementation: https://github.com/tektoncd/dashboard/tree/main/packages/components/src/components/Log

**Comment by weili520** [comment]
@harrisonliu5 I think we should upgrade the `node-fetch` to v3.x, this problem is caused by that [the fetch response.body is not a nodejs `readable stream`](https://github.com/node-fetch/node-fetch/issues/1308#issuecomment-925202298). It is ESM, the resolution is here [Add example for loading ESM from CommonJS](https://github.com/node-fetch/node-fetch/pull/1236#issue-962556727).

**Comment by weili520** [comment]
I  have tried it, it works well.

The pods log-generator is created by using the command: `kubectl apply -f https://raw.githubusercontent.com/wenchajun/fluentbit-operator/notification/docs/user-guides/forwarding-logs-via-http/kubesphere/log-generator.yaml`

it will generate a log every five seconds.

https://user-images.githubusercontent.com/33231138/148180055-2afddcc0-d4eb-44d3-b262-7abe78cb15c1.mov

**Comment by weili520** [comment]
> @harrisonliu5 I think we should upgrade the `node-fetch` to v3.x, this problem is caused by that [the fetch response. body is not a nodejs `readable stream`](https://github.com/node-fetch/node-fetch/issues/1308#issuecomment-925202298). It is ESM, the resolution is here [Add example for loading ESM from CommonJS](https://github.com/node-fetch/node-fetch/pull/1236#issue-962556727).

This problem will disappear if the user updates the KubeSphere version to v3.2.1, it's amazing.

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/172287985-c4bd8833-b48c-4830-ace1-1fd1d54d7300.png)

version used 
kubesphere: v3.3.0-rc.1
