### ISSUE TITLE
Chinese unit in DevOps code quality

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#1278]
In Code Quality, the unit is displayed as "个" in Chinese, while in English this word can actually be omitted. Perhaps words like objects or items can be the English version, but I prefer no unit here. I will try later to build it locally to see if the unit can be replaced with a blank space.

![image](https://user-images.githubusercontent.com/65327072/97531304-e0d68c80-19ee-11eb-9e63-fef2c14e4f2b.png)

**Comment by harrisonliu5** [comment]
done
