### ISSUE TITLE
feature: interactive creation pipeline

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#1283]
![image](https://user-images.githubusercontent.com/43693241/97823718-bd645800-1cf4-11eb-8a5b-7a0d8cb4e53c.png)

**Comment by LinuxSuRen** [comment]
Hi @shaowenchen , Is this a bug or a feature? The title says it's a feature, but you give it a label named a bug.

No matter it's a bug or a feature, adding some description will be better.

**Comment by harrisonliu5** [comment]
done
