### ISSUE TITLE
new app version displays in the App Store while not released to App Store though passing the review

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#1298]
I uploaded two app versions for the same app emqx in App Templates; v1.0.0 and v4.0.2. v1.0.0 was released to the App Store while v4.0.2 is not. However, I notice for a regular user account (project-regular), it can still see the latest version 4.0.2 in App Store for this app, which is strange, as the app version 4.0.2 is not released yet.

![截屏2020-11-06下午10 15 09](https://user-images.githubusercontent.com/65327072/98376308-3dd0e300-207e-11eb-8b20-1f1deae396cf.png)

I think the correct process should be: the ISV (the account that uploads the app) clicks the button **Release to Store** and then the latest version displays in the App Store. The issue is: the button is not clicked yet but you still see the latest app version.

![截屏2020-11-06下午10 15 39](https://user-images.githubusercontent.com/65327072/98376711-d8c9bd00-207e-11eb-9858-6167ae0036ac.png)

Besides, if you click the app, you can only see v1.0.0, not the v4.0.2, which I think it is expected as the app is not released yet.

![Xnip2020-11-06_22-17-06](https://user-images.githubusercontent.com/65327072/98376951-30682880-207f-11eb-83bd-f0b6c3dec012.jpg)

**Comment by jioce** [comment]
issue fixed v3.2.0
/closed

**Comment by wenxin-01** [comment]
issue fixed in  `v3.2.0`

/close
