### ISSUE TITLE
DevOps Action --> the Commit List Page Bug

### ISSUE THREAD

**Issue by geniussheep** [kubesphere/console#1309]
![image](https://user-images.githubusercontent.com/7587017/99402296-274f4500-2924-11eb-8911-43585ffe4e36.png)

![image](https://user-images.githubusercontent.com/7587017/99402822-bc523e00-2924-11eb-9a96-6686f5fd6526.png)

![image](https://user-images.githubusercontent.com/7587017/99371198-8f3c6600-28f9-11eb-8827-8b757b0ac9d0.png)

Bug1：The page display is 100 items per page, not 10 items per page
Bug2：Page turning has no effect, it is always the data of the first page

**Comment by harrisonliu5** [comment]
done
