### ISSUE TITLE
Add support for discovering tags in multi-branch pipeline

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1310]
**What would you like to be added**:
Adding a switch to enable or disable a multi-branch pipeline to discover tags or not.

**Why is this needed**:
In some cases, we need to trigger the multi-branch pipeline via the git tags. Kubephere already supports trigger a pipeline via PR or branches. It would be good to have this feature.
I have already created a PR for the back-end part. https://github.com/kubesphere/kubesphere/pull/3125

**Comment by LinuxSuRen** [comment]
In order to have an image in your mind. I put the screenshot with a mark below.
![ks-discover-tags](https://user-images.githubusercontent.com/1450685/99477798-35d24680-298e-11eb-834a-24f36b36427f.png)

**Comment by shaowenchen** [comment]
It's a tag trigger parameter for the Github repo.

**Comment by harrisonliu5** [comment]
done
