### ISSUE TITLE
Rollback button appears for the latest app version when an old app version is deployed from app repo

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#1313]
I added an app repository `https://helm-chart-repo.pek3a.qingstor.com/kubernetes-charts/` to provide app templates. I deployed the app grafana from this app repository but I noticed the upgrade button does not seem right:

I deployed the version 4.3.0 directly, and the latest version of this app in the repo is actually 5.5.7. The button next to the version number is Rollback. I reckon the expected button should be **Upgrade** instead of **Rollback**.
![Xnip2020-11-18_16-23-44](https://user-images.githubusercontent.com/65327072/99504643-c45cbd00-29ba-11eb-9b7c-2ee2c7522712.jpg)

**Comment by leoendless** [comment]
This function has been refactored.
