### ISSUE TITLE
Project created with the same name as a project deleted still has apps in it while does not have related workloads and services.

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#1314]
1. Delete a project.
2. Create a new project which has the same name as the project deleted.
3. The new project created still has all the apps in it, but the workloads and services of these apps do not exist.

![Xnip2020-11-18_17-10-50](https://user-images.githubusercontent.com/65327072/99509728-1e608100-29c1-11eb-978e-16d4f4bec337.jpg)

**Comment by zheng1** [comment]
Duplicate with https://github.com/kubesphere/kubesphere/issues/2783
