### ISSUE TITLE
Add support of Gitlab multi-branch pipeline

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1316]
**What would you like to be added**:
It will be a new option for creating a multi-branch pipeline. What we need are the red fields of the below picture.

![gitlab-1](https://user-images.githubusercontent.com/1450685/99644267-b1b0b980-2a88-11eb-9b46-a26443695e92.png)

Gitlab multi-branch pipeline also needs a git tag discover feature. About this part, you can check out https://github.com/kubesphere/console/issues/1310

**Why is this needed**:
Gitlab is a very popular git provider. Many users want to have this feature.

**How to test against it**
Please check out the below issue if you need the backend to test it. You can give all details of the backend.
https://github.com/kubesphere/kubesphere/pull/3131

**Comment by harrisonliu5** [comment]
You need to provide a GitLab query API @LinuxSuRen

**Comment by LinuxSuRen** [comment]
Currently, there's no Gitlab query API. Users need to type those fields manually. Because Jenkins BlueOcean still does not support Gitlab.

**Comment by harrisonliu5** [comment]
done
