### ISSUE TITLE
feature: add trigger for s2i

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#1337]
**What would you like to be added**:

Support to trigger S2i/B2i remotely.

**Why is this needed**:

- friendly to developers
- deploy servers quickly after pushing the code

**What should you do**

1. Add Parameters to S2IBuilder

![image](https://user-images.githubusercontent.com/43693241/100579158-a5e1b480-331e-11eb-85e0-93ade80ceccb.png)

2. Trigger S2I/B2i

Visit this URL: http://s2ioperator-trigger-service.kubesphere-devops-system.svc/s2itrigger/v1alpha1/general/namespaces/s2i/s2ibuilders/shaowenchen--latest-dk7/?secretCode=x34h

Return: 201

(s2i is your namespaces, shaowenchen--latest-dk7 is your s2ibuilder)

/area devops
/assign @harrisonliu5

**Comment by shaowenchen** [comment]
触发令牌 - Secret Code

**Comment by harrisonliu5** [comment]
done
