### ISSUE TITLE
Allow users to choose a different Jenkins agent for pipeline stage

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1348]
**What would you like to be added**:
In some use cases, there're multiple languages in one single project or build serval different projects in one pipeline. But Kubesphere 3.0 can only set a global Jenkins agent for a pipeline.

A simple solution is adding support to set different Jenkins agents for each pipeline stage. Basically, they are the same between the global agent setting and the stage scoped agent setting.

![select-node-in-stage](https://user-images.githubusercontent.com/1450685/101327744-12722b80-38aa-11eb-944f-5aaf99630c9f.png)

**Why is this needed**:
I find out there's another feature request which is https://github.com/kubesphere/kubesphere/issues/2862

**Enhancement**
For now, we need to type the label of the target Jenkins node (or agent). But we can only get all the supported labels by visiting Jenkins UI. In order to make it be easier for all users especially for someone who is new to Jenkins. I'd like offer my second proposal below:

* https://github.com/kubesphere/kubesphere/issues/3185

/area devops

**Comment by LinuxSuRen** [comment]
hi @shaowenchen , do you think it should be part of https://github.com/kubesphere/kubesphere/issues/3052 or not?

**Comment by harrisonliu5** [comment]
done
