### ISSUE TITLE
Display the alias and description in the "Applications" details page

### ISSUE THREAD

**Issue by fukiki** [kubesphere/console#1351]
**What would you like to be added**:

In the resource table, the resource name, alias, and description are displayed, but in the resource detail interface, non-tabular display items, such as cards and pannels, do not show aliases and descriptions.

In the "Applications" details page, the alias name and description of the  services and workloads are not displayed.

<img width="912" alt="1" src="https://user-images.githubusercontent.com/59835099/101426729-793e2600-3938-11eb-8cef-950cae6c96a9.png">

**Why is this needed**:

The display of multiple cards or pannels is also a way to display the list, and the display content should be consistent with the table. 

At the same time, the alias and description make it easy for users to obtain overview information, reducing the operation of clicking on details.

If the community confirms that there is a need for improvement, I can submit a PR.

**Comment by zackzhangkai** [comment]
`bookinfo-ingress ` is ingress name,  `hostname:productpage.demo-xxxx` is the hostname in `ingress` to match requst, the `URL` is because the service is NodePort, just told how to request it. What do you mean by `alias` and `description`?

**Comment by fukiki** [comment]
In some application scenarios, users will pay attention to the alias and description, not the name `bookinfo-ingress`.
So my suggestion is to increase the display of alias or description.

**Comment by leoendless** [comment]
@zackzhangkai each resource in kubesphere has an alias and description annotation. I think it's good advice to display the alias name. But the description text is usually very long and inconvenient to display.

**Comment by leoendless** [comment]
The resource name and the alias name are enough to let users know what resource it is

**Comment by imjoey** [comment]
> The resource name and the alias name are enough to let users know what resource it is

@leoendless +1 for me. We could see the additional alias alongside in many other pages. So we think the alias may be also needed for users. We've fixed this issue, @fukiki would commit the pr soon.

**Comment by leoendless** [comment]
Cool！looking forward to your PR.
