### ISSUE TITLE
Add credential selection support for Gitlab multi-branch pipeline

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1361]
**What would you like to be added**:
Add a selection of Gitlab server.

Please see the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/101870707-20cb8a80-3bbd-11eb-907b-f7f227730dcd.png)

Below is an example of the data structure (you need to fouc on `credential_id`):
```
 15 spec:
 14   multi_branch_pipeline:
 13     discarder:
 12       days_to_keep: "-1"
 11       num_to_keep: "-1"
 10     gitlab_source:
  9       credential_id: admin
  8       discover_branches: 1
  7       owner: linuxsuren1
  6       repo: linuxsuren1/private
  5       server_name: default
  4     name: private
  3     script_path: Jenkinsfile
  2     source_type: gitlab
  1   type: multi-branch-pipeline
31  status: {}
```

**Why is this needed**:
For a private Gitlab server, the credential is necessary.

/area devops

**Comment by harrisonliu5** [comment]
done
