### ISSUE TITLE
The sonarqube page of a pipeline is blank

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1367]
**General remarks**

**Describe the bug**
When I visit the page of Sonarqube in Kubesphere Pipeline with `http://localhost:8000/good/clusters/default/devops/rickfzhvl/pipelines/java-gitee/branch/master/code-quality`

Got errors from the browser console.

![image](https://user-images.githubusercontent.com/1450685/102315388-0b84a080-3faf-11eb-87ee-93256de4d8b3.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: development version

All the below components use the latest docker image from `kubespheredev/xxx`

* `ks-apiserver`
* `ks-console`
* `ks-controller-manager`

**Environment**
Nothing special

**To Reproduce**
Follow this [user guide](https://kubesphere.com.cn/docs/devops-user-guide/how-to-integrate/sonarqube/).

**Expected behavior**
I can see the scanning result of Sonarqube.

/kind bug
/area devops

**Comment by LinuxSuRen** [comment]
I also found a potential issue by reading the code lines.

[The branch name](https://github.com/kubesphere/console/blob/ab2d0104302d6d93406714ea0c07671634a630c6/src/stores/devops/codeQuality.js#L34) might always be `master` because of [this line](https://github.com/kubesphere/console/blob/ab2d0104302d6d93406714ea0c07671634a630c6/src/pages/devops/containers/Pipelines/Detail/Layout/pipeline.jsx#L102).

So if I create a pipeline that is not a multi-branch pipeline. Then I'll never be going to see the Sonarqube page.

**Comment by harrisonliu5** [comment]
done
