### ISSUE TITLE
Offer a select for Jenkins agent labels in the Pipeline editing page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1371]
**What would you like to be added**:
Offer a select for Jenkins agent labels in the Pipeline editing page. Please see the following screenshot:

![WX20201218-140546](https://user-images.githubusercontent.com/1450685/102580784-318a7c00-413a-11eb-929f-0f6144f067e1.png)

You can get the data from this API:

`GET /kapis/devops.kubesphere.io/v1alpha2/devops/rickfzhvl/jenkins/labelsdashboard/labelsData`

The response could be like:
```
{
   "status":"ok",
   "data":[
      {
         "label":"a",
      },
      {
         "label":"b",
      }
   ]
}
```

**Why is this needed**:
Type the agent label name manually is not reliable. Firstly, users don't know which labels they can use. Secondly, people can make mistakes by typing.

/area devops

**Backend**:
We need a new plugin [label-linked-jobs-plugin](https://github.com/jenkinsci/label-linked-jobs-plugin). But I've not put it into [ks-jenkins](https://github.com/kubesphere/ks-jenkins). I'll leave a comment below once it's ready.

**Comment by LinuxSuRen** [comment]
This is the PR of ks-jenkins https://github.com/kubesphere/ks-jenkins/pull/13

**Comment by LinuxSuRen** [comment]
This is the sample payload of API `POT /v1alpha2/tojenkinsfile`

```
{
	"pipeline": {
		"agent": {
			"type": "node",
			"arguments": [{
				"key": "label",
				"value": {
					"isLiteral": true,
					"value": "maven"
				}
			}]
		},
		"stages": [{
			"name": "go build",
			"agent": {
				"type": "node",
				"arguments": [{
					"key": "label",
					"value": {
						"isLiteral": true,
						"value": "golang"
					}
				}]
			},
			"branches": [{
				"name": "default",
				"steps": [{
					"name": "sh",
					"arguments": [{
						"key": "script",
						"value": {
							"isLiteral": true,
							"value": "echo 's'"
						}
					}]
				}]
			}]
		}]
	}
}
```

Please pay attention to `pipeline.stages.agent`.

In case of anyone who might be interested in how can I get the API payload. You can create a Pipeline via Jenkins [BlueOcean](https://github.com/jenkinsci/blueocean-plugin), then you can get it.

**Comment by harrisonliu5** [comment]
done
