### ISSUE TITLE
【Application template】Local upload image display failed 

### ISSUE THREAD

**Issue by TinaSprunt** [kubesphere/console#1374]
**Describe the bug**

###【Application template】Local upload image display failed 

![image](https://user-images.githubusercontent.com/38268966/102598350-db780180-4156-11eb-841d-b088a085237e.png)

I found it in the code
![image](https://user-images.githubusercontent.com/38268966/102598703-5f31ee00-4157-11eb-91da-a0c076d0493d.png)

avatar not processed

![image](https://user-images.githubusercontent.com/38268966/102599199-1af31d80-4158-11eb-9c31-20a017311885.png)

I try to fix it
![image](https://user-images.githubusercontent.com/38268966/102599742-e03db500-4158-11eb-8197-bf83bf8d2631.png)

it works for me

![image](https://user-images.githubusercontent.com/38268966/102599531-90f78480-4158-11eb-92a7-8103f9102917.png)

**Comment by leoendless** [comment]
Thanks for your feedback! Would you like to create a PR to fix this problem?

**Comment by TinaSprunt** [comment]
> 感谢您的反馈意见！您想创建PR来解决此问题吗？

Thanks for your answer, I will try

**Comment by TinaSprunt** [comment]
> Thanks for your feedback! Would you like to create a PR to fix this problem?

Thanks for your answer, I will try
