### ISSUE TITLE
Lack of confirm before leaving the editing box of Jenkinsfile

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1378]
**What would you like to be added**:

Please see the following screenshot. No matter clicking the `Cancel` button or type `Esc`, please make sure don't close the box directly. Or

![image](https://user-images.githubusercontent.com/1450685/102745912-16b54300-4398-11eb-84ea-3629ecb83916.png)

**Why is this needed**:

Make sure users can get the confirmation before they leave the editing box of Jenkinsfile. Typing the wrong key is a very normal thing. But it hurts people if they already wrote down many code lines in the editing box. The confirmation is necessary.

/area devops
/priority medium

**Comment by harrisonliu5** [comment]
done
