### ISSUE TITLE
‘last login time' on home page is 'this login time'

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/console#1383]
**Describe the bug**

After login to KubeSphere, you could see 'last login' date and time info, but it's not last login but this login

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by harrisonliu5** [comment]
#1858

**Comment by calvinyv** [comment]
it's still the same problem on v3.1.0
/assign @zheng1 @harrisonliu5

**Comment by jioce** [comment]
issue fixed v3.2.0
/closed

**Comment by wenxin-01** [comment]
issue fixed in  `v3.2.0`

/close
