### ISSUE TITLE
Support to select Gitlab servers and related projects in the Gitlab multi-branch Pipeline

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1387]
**What would you like to be added**:
Offer a select for Gitlab multi-branch Pipeline setting page.

# Getting server list

Request: `GET /v1alpha2/devops/${devops}/jenkins/gitlab/serverList`
Response : `{"status":"ok","data":[{"name":"default","url":"https://gitlab.com"}]}`

It means users can choose the items of `Git Server`. See also the following screenshot:
![image](https://user-images.githubusercontent.com/1450685/104276906-c9347d80-54e0-11eb-950a-b96e8af1fd42.png)

# Geting project list

Request: `GET /v1alpha2/devops/${devops}/jenkins/gitlab/projectList?server=${serverName}&owner=${owner}`
Response: `{"status":"ok","data":["LinuxSuRen1/jenkins-cli","LinuxSuRen1/test"]}`

It means users can choose the items of `Repository Name`. See also the following screenshot:
![image](https://user-images.githubusercontent.com/1450685/104276962-e406f200-54e0-11eb-8081-a3064806cb08.png)

**Why is this needed**:
Make it be easier for users to set up a Gitlab multi-branch Pipeline.

**Upstream**
See also https://github.com/jenkinsci/gitlab-branch-source-plugin/pull/103

**Comment by harrisonliu5** [comment]
done
