### ISSUE TITLE
Do not need to confirm if the content of Jenkinsfile has not any changes

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1398]
**What would you like to be added**:
Do not need to confirm if the content of Jenkinsfile has not any changes. Currently, it always let me confirm it no matter I do or do not any changes.

![image](https://user-images.githubusercontent.com/1450685/103253667-10891d00-49bd-11eb-81c2-debefc0af26a.png)

**Why is this needed**:
Sometimes we just want to take a look at the Jenkinsfile instead of editing it.

/area devops
/priority low

**Comment by LinuxSuRen** [comment]
Same situation with Pipeline edting page.

**Comment by harrisonliu5** [comment]
done
