### ISSUE TITLE
Do not need to have the API request to Sonarqube status because it's disabled

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1399]
**What would you like to be added**:
In my case, I didn't integrate Sonarqube into KubeSphere. But I still can get the errors that you can see from the screenshot below:

![image](https://user-images.githubusercontent.com/1450685/103254285-a9209c80-49bf-11eb-930c-31ccbfda9f8f.png)

**Why is this needed**:
The errors that come from the browser console might let users feel confused. But it's not a really bug.

/area devops
/priority low

**Comment by harrisonliu5** [comment]
done
