### ISSUE TITLE
Routes-Edit Rules: the operation on the web is inconsistent with actual configuration

### ISSUE THREAD

**Issue by fukiki** [kubesphere/console#1404]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When edit Rules of Routes, edit 'HostName', at the same time edit 'Protocol' and chaned it to 'https' on the web, the actual configuration item does not take effect.

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: 3.0
Kubernetes: 1.17.9

**Environment**

1 masters:  8cpu/8g
2 nodes: 8cpu/16g

**To Reproduce**
1. Go to 'Workbench -> Workspaces -> Projects -> Application Workloads -> Routes'.
2. Click one route 'test-ingress' and go to route details page, there is one rule: 'HostName' is test1.com, 'Protocol' is http.
3. Click on 'More' -> 'Edit Routes'-> 'Set Route Rule' -> 'Specify Domain'.
4. Edit 'HostName': test2.com, at the same time 'Protocol' chaned to 'https'，Click on 'Save'
![q1](https://user-images.githubusercontent.com/59835099/103326821-0afb0800-4a8d-11eb-8808-2c2766b26c49.png)

5. In page 'Edit Routes', 'Protocol' has not changed, still is 'http'. Click on 'update', updated successfully.
![q2](https://user-images.githubusercontent.com/59835099/103326839-22d28c00-4a8d-11eb-8f56-01242353e8cf.png)

6. Click on 'More' -> 'Edit YAML' to see the configuration, there is nothing in spec-tls-hosts.
![q3](https://user-images.githubusercontent.com/59835099/103326950-8e1c5e00-4a8d-11eb-9c3c-c78e78142271.png)

7. Click on 'More' -> 'Edit Routes'-> 'Set Route Rule' -> 'Specify Domain'.
8. Only edit 'Protocol' and chane it to 'https', click on 'Save'.
9. In page 'Edit Routes', 'Protocol' has changed to 'https'. Click on 'Update', updated successfully.
10. Click on 'More' -> 'Edit YAML' to see the configuration, there is a new host domain in spec-tls-hosts: test2.com.
![q5](https://user-images.githubusercontent.com/59835099/103327036-e5bac980-4a8d-11eb-8b1a-04fc0ef2d73f.png)

11. Click on 'More' -> 'Edit Routes'-> 'Set Route Rule' -> 'Specify Domain'.
12. Only edit 'Protocol' chaned to 'http', click on 'Save';
13. Go to edit again, 'HostName': test3.com, at the same time 'Protocol' chaned to 'https', click on 'Save', in page 'Edit Routes', 'Protocol' has not changed to 'https'. 
14. Then go to edit 'Protocol' again , change it to 'https', click on 'Save',  in page 'Edit Routes', 'Protocol' has changed to 'https', 'HostName' is test3.com, click on 'Update', updated successfully.
15. Click on 'More' -> 'Edit YAML' to see the configuration, the host domain test2.com still in spec-tls-hosts.
![q4](https://user-images.githubusercontent.com/59835099/103326879-4c8bb300-4a8d-11eb-998c-9f47089318ad.png)

**Expected behavior**
In step 5~6 : In page 'Edit Routes', 'Protocol' should be 'https', and there is a new host domain 'test2.com' in spec-tls-hosts.

In step 15 : The host domain 'test2.com' should not in spec-tls-hosts.

**Comment by fukiki** [comment]
This issue still exists on the master branch.

**Comment by leoendless** [comment]
Fixed in master branch. Update the ks-console image to `kubespheredev/ks-console:latest`.

**Comment by fukiki** [comment]
> Fixed in master branch. Update the ks-console image to `kubespheredev/ks-console:latest`.

@leoendless  Update the ks-console image to kubespheredev/ks-console:latest, 
There is no dialog open after clicking the "Edit Routes" button:
![image](https://user-images.githubusercontent.com/59835099/103614943-a5af8700-4f64-11eb-96af-a1d999636c7a.png)

**Comment by leoendless** [comment]
> > Fixed in master branch. Update the ks-console image to `kubespheredev/ks-console:latest`.
> 
> @leoendless Update the ks-console image to kubespheredev/ks-console:latest,
> There is no dialog open after clicking the "Edit Routes" button:
> ![image](https://user-images.githubusercontent.com/59835099/103614943-a5af8700-4f64-11eb-96af-a1d999636c7a.png)

Missing re-check after fixing rule editor for multi-cluster ingress.

**Comment by leoendless** [comment]
@fukiki Please check the edit form again.

**Comment by fukiki** [comment]
@leoendless Bug fixed, thanks.
