### ISSUE TITLE
Do not need the 'Add action button' if the corresponding strategy exists

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1405]
As I mentioned in the subject, we don't need it. For example, I already added 'Discover Branches' as a branches scanning strategy, the button 'Discover Branches' still exists. The most important thing is that nothing happened when I try to click it.

See the screenshot below:

![image](https://user-images.githubusercontent.com/1450685/103333070-879ae000-4aa7-11eb-81b8-2135af87216c.png)

# Suggestion
* Make the corresponding button be invisible if the strategy exists
* Disable the button 'Add Action' if all strategies are added

/area devops

**Comment by harrisonliu5** [comment]
done
