### ISSUE TITLE
Release canary support statefulset workload

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/console#1434]
**Describe the bug**

![image](https://user-images.githubusercontent.com/20178386/105009260-3c0b9e80-5a75-11eb-8041-0454ecb328e3.png)

/assign @leoendless 
/area microservice
/milestone 3.1.0

**Comment by zryfish** [comment]
That's made on purpose, did you try headless service in Istio? What's the support now?

**Comment by zackzhangkai** [comment]
Headless is no need to inject sidecar. Statefulset with ClusterIP, should be also available to use release canary.

**Comment by zryfish** [comment]
> Headless is no need to inject sidecar. Statefulset with ClusterIP, should be also available to use release canary.

Statefulset workload with ClusterIP is not encouraged, I think we need to think about it thoroughly before taking action.
