### ISSUE TITLE
TypeError: Cannot read property 'concat' of undefined

### ISSUE THREAD

**Issue by gdzy1987** [kubesphere/console#147]
# yarn                                                          
yarn install v1.22.0
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > react-hot-loader@4.12.19" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
warning " > babel-jest@23.6.0" has unmet peer dependency "babel-core@^6.0.0 || ^7.0.0-0".
[5/5] 🔨  Building fresh packages...
success Saved lockfile.
$ rimraf .cache-loader
✨  Done in 72.88s.

# yarn lego 
yarn run v1.22.0
$ webpack -p --config scripts/webpack.lego.js
✔ success webpack compiled in 1s 455ms
Hash: a928e222abddf0e99f13
Version: webpack 4.41.6
Time: 1460ms
Built at: 02/13/2020 8:30:31 AM
   Asset       Size  Chunks                    Chunk Names
lego.css    370 KiB       0  [emitted]  [big]  lego
 lego.js  932 bytes       0  [emitted]         lego
Entrypoint lego [big] = lego.css lego.js
[0] ./src/scss/lego.theme.scss 39 bytes {0} [built]
    + 1 hidden module
Child mini-css-extract-plugin node_modules/cache-loader/dist/cjs.js!node_modules/css-loader/index.js??ref--4-2!node_modules/postcss-loader/src/index.js??postcss!node_modules/sass-loader/dist/cjs.js!src/scss/lego.theme.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/cache-loader/dist/cjs.js!./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/dist/cjs.js!./src/scss/lego.theme.scss 370 KiB {0} [built]
        + 1 hidden module
✨  Done in 2.32s.

# yarn start
yarn run v1.22.0
$ concurrently -k --raw 'yarn dev:client' 'yarn dev:server'
$ cross-env NODE_ENV=development nodemon -w ./common -w ./server -e js,yaml server/server.js
$ cross-env NODE_ENV=development webpack-dev-server --config scripts/webpack.dev.js -w
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): common server/**/*
[nodemon] watching extensions: js,yaml
[nodemon] starting `node server/server.js`
Dashboard app running at port 8000
Happy[jsx]: Version: 5.0.1. Threads: 3
ℹ ｢wds｣: Project is running at http://0.0.0.0:8001/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/ym-10458/Documents/devops/kubesphere.io/console
Happy[jsx]: All set; signaling webpack to proceed.
✔ success webpack compiled in 605ms
✖ ｢wdm｣: Hash: 7eec6b63eb20fd752509
Version: webpack 4.41.6
Time: 694ms
Built at: 02/13/2020 8:30:40 AM
    Asset      Size  Chunks             Chunk Names
  main.js  33.5 KiB    main  [emitted]  main
vendor.js   1.3 MiB  vendor  [emitted]  vendor
Entrypoint main = vendor.js main.js
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8001 (webpack)/hot/dev-server.js react-hot-loader/patch ./src/core/index.js 64 bytes {main} [built]
[./node_modules/react-hot-loader/dist/react-hot-loader.development.js] 97.1 KiB {vendor} [built]
[./node_modules/react-hot-loader/patch.js] 229 bytes {vendor} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8001] (webpack)-dev-server/client?http://0.0.0.0:8001 4.29 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {vendor} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {vendor} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {vendor} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {vendor} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {vendor} [built]
[./src/core/index.js] 952 bytes {main} [built] [failed] [1 error]
    + 44 hidden modules

ERROR in ./src/core/index.js
Module build failed (from ./node_modules/happypack/loader.js):
TypeError: Cannot read property 'concat' of undefined
    at findPath (/Users/ym-10458/Documents/devops/kubesphere.io/console/node_modules/babel-plugin-recharts/lib/index.js:55:26)
    at /Users/ym-10458/Documents/devops/kubesphere.io/console/node_modules/babel-plugin-recharts/lib/index.js:126:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/ym-10458/Documents/devops/kubesphere.io/console/node_modules/babel-plugin-recharts/lib/index.js:118:21)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
 @ multi react-hot-loader/patch ./src/core/index.js main[1]
ℹ ｢wdm｣: Failed to compile.

**Comment by leoendless** [comment]
can you print the nodejs version ?

**Comment by gdzy1987** [comment]
> can you print the nodejs version ?

$ node --version
v13.6.0

# MacBook-Pro in ~ [15:43:58]
$ yarn -v
1.22.0

**Comment by leoendless** [comment]
The reason is an incompatible dependency version locked by ``yarn.lock`` with nodejs v13.x.  

we recommend a nodejs version such as v8.x or v10.x (keeping in line with our local env), or try to delete ``yarn.lock`` then execute ``yarn install``.

**Comment by leoendless** [comment]
Has the problem been solved ? @gdzy1987
