### ISSUE TITLE
can't change parameters  in pipeline

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#1481]
**Describe the bug**

![image](https://user-images.githubusercontent.com/43693241/107144589-2227f200-6977-11eb-8d97-b16af03281d6.png)

I change the parameter to v0.0.2. But it is automatically modified to v0.0.1

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.3
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/area devops
project devops
/assign @harrisonliu5

**Comment by LinuxSuRen** [comment]
hi @shaowenchen . I don't quite understand this issue. There're some possible use cases:

* Change the parameter of an input
  * Run Pipeline at the first time, the parameter does not effect
  * Run Pipeline at the second time, the parameter does not effect
* Run the Pipeline, give a different parameter, Run the Pipeline again, the parameter keep using the old one

Please tell me if you want to describe other cases.

**Comment by shaowenchen** [comment]
There is no need to run the pipeline.
 After modifying the TAG_NAME, it will automatically revert to v0.0.1.
