### ISSUE TITLE
Typo in DevOps credential creating dialog

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1485]
**Describe the bug**
The credential-creating dialog can only create one instead of many. So the title should be `Create Credential` instead of `Create Credentials`

![image](https://user-images.githubusercontent.com/1450685/108507486-5abfb800-72f5-11eb-99b6-157c16413974.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: `kubespheredev/ks-console:nightly-20210218`

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to DevOps project
2. Create a credential
3. See the title

**Expected behavior**
The dialog title should be accurate.

/area devops
/good-first-issue

**Comment by LinuxSuRen** [comment]
![image](https://user-images.githubusercontent.com/1450685/108508883-762bc280-72f7-11eb-8121-c44c2780200c.png)

`passphrase` The first letter should be capitalized.

![image](https://user-images.githubusercontent.com/1450685/108508995-9ce9f900-72f7-11eb-8baf-2ac9f8a8e091.png)

`secret` The first letter should be capitalized.

![image](https://user-images.githubusercontent.com/1450685/108509169-dde20d80-72f7-11eb-9293-176129dc09bb.png)

`Please enter the Credentials name` should be `Please enter the credentials name`

**Comment by 96RadhikaJadhav** [comment]
@LinuxSuRen  Can I work on the issue?

**Comment by LinuxSuRen** [comment]
hi @96RadhikaJadhav , of course. You're welcome. We'll very appreciate your effort.

**Comment by 96RadhikaJadhav** [comment]
@LinuxSuRen I have created a PR #1487 . Can you please tell me for the last typo in delete credentials, where exactly we need to correct it? I was confused about it so I left it off.

**Comment by jioce** [comment]
issue fixed v3.2.0
/closed

**Comment by wenxin-01** [comment]
issue fixed in  `v3.2.0`

/close
