### ISSUE TITLE
gatewayServer login failure error “login.iam.kubesphere.io is forbidden” code 403

### ISSUE THREAD

**Issue by xinnicai** [kubesphere/console#1490]
according https://github.com/kubesphere/console/blob/master/docs/access-backend.md
![image](https://user-images.githubusercontent.com/30997380/109094875-a6d78600-7755-11eb-8a39-a19f5ae27a2a.png)
![image](https://user-images.githubusercontent.com/30997380/109094898-b22ab180-7755-11eb-9007-255a35a4973a.png)
用户名：admin
密码：P@88w0rd

![image](https://user-images.githubusercontent.com/30997380/109095039-f453f300-7755-11eb-832a-d0bfe34668f2.png)

![image](https://user-images.githubusercontent.com/30997380/109095055-fddd5b00-7755-11eb-8d6f-a1fa052e7a70.png)
How to solve this problem

**Comment by leoendless** [comment]
What version of the KubeSphere cluster?

**Comment by wansir** [comment]
@xinnicai 

Please check out the latest code of `release-3.0` branch to match the backend API server.

**Comment by xinnicai** [comment]
> 哪个版本的KubeSphere集群？

1.19

**Comment by xinnicai** [comment]
@wansir branch release-3.0 yarn start Error
![image](https://user-images.githubusercontent.com/30997380/109117715-51af6a80-777d-11eb-8d3d-7fd809930866.png)
but i`m already excute yarn add core-js@2.6.5
![image](https://user-images.githubusercontent.com/30997380/109118019-b66ac500-777d-11eb-9ba1-3d2c4afa7eff.png)

**Comment by leoendless** [comment]
> @wansir branch release-3.0 yarn start Error
> ![image](https://user-images.githubusercontent.com/30997380/109117715-51af6a80-777d-11eb-8d3d-7fd809930866.png)
> but i`m already excute yarn add core-js@2.6.5
> ![image](https://user-images.githubusercontent.com/30997380/109118019-b66ac500-777d-11eb-9ba1-3d2c4afa7eff.png)

Try changing the nodejs to 10.x version.

**Comment by xinnicai** [comment]
@leoendless here note node needs 12.x+
![image](https://user-images.githubusercontent.com/30997380/109123672-1022bd80-7785-11eb-89be-4cae0207e837.png)

**Comment by leoendless** [comment]
> @leoendless here note node needs 12.x+
> ![image](https://user-images.githubusercontent.com/30997380/109123672-1022bd80-7785-11eb-89be-4cae0207e837.png)

That is the requirement when developing on the master branch

**Comment by xinnicai** [comment]
@leoendless It doesn't work
![image](https://user-images.githubusercontent.com/30997380/109126688-82e16800-7788-11eb-9223-771f6f143ca8.png)

**Comment by leoendless** [comment]
You need to re-install the `node_modules`.
```
yarn
yarn lego
yarn start
```

**Comment by xinnicai** [comment]
@leoendless already done，but Error
![image](https://user-images.githubusercontent.com/30997380/109131056-609e1900-778d-11eb-8a66-f1f94b71003f.png)
![image](https://user-images.githubusercontent.com/30997380/109131132-7b708d80-778d-11eb-85d6-83df30f1a52c.png)
![image](https://user-images.githubusercontent.com/30997380/109131236-90e5b780-778d-11eb-966d-ebdd054de1f9.png)

**Comment by leoendless** [comment]
Looks like a dependency problem. Remove `yarn.lock` and re-install the dependencies ?

**Comment by xinnicai** [comment]
@leoendless 
Already remove yarn.lock,but useless.
Is use  code of release-3.0 branch ?

**Comment by xinnicai** [comment]
@leoendless @wansir This issue has been resolved.Thanks!
