### ISSUE TITLE
Feat:  Namespace started with kube- is not allowed

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/console#1491]
**What would you like to be added**:

Kubernetes documentation explicitly tells users not to create namespaces that start with kube- - see https://kubernetes.io/docs/tasks/administer-cluster/namespaces/#creating-a-new-namespace where it says:

Note: Avoid creating namespace with prefix kube-, since it is reserved for Kubernetes system namespaces.

**Comment by zackzhangkai** [comment]
assign @fukiki  

Glad to see your contributing.  Thank for your help @imjoey.

**Comment by fukiki** [comment]
@zackzhangkai  I will  fix it.
