### ISSUE TITLE
Inappropriate page in the Gitlab multi-branch pipeline tag list

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1494]
**Describe the bug**

/area devops
/priority high

![image](https://user-images.githubusercontent.com/1450685/109278672-c05ef780-7853-11eb-8317-b08f7d1a5af8.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere version is: `nightly-20210224`

**Environment**
This is not an environmental issue.

**To Reproduce**

Firstly, install KubeSphere via: `kk create cluster --with-kubesphere nightly-20210224 -y`

1. Go to the DevOps project page
2. Create a Gitlab multi-branch Pipeline
3. Create a git tag on your repo
4. Scan the repo
5. See the target git page

You can see the button `Scan Repository` instead of a list page.

**Expected behavior**
Users can see the specific git build history items.

**Comment by LinuxSuRen** [comment]
I got the same issue with the GitHub multi-branch Pipeline.

![image](https://user-images.githubusercontent.com/1450685/109281178-ef2a9d00-7856-11eb-8b58-00487bb85603.png)

**Comment by harrisonliu5** [comment]
this API doesn't respond to any data 

![image](https://user-images.githubusercontent.com/17872673/109448619-5cba1180-7a81-11eb-9483-3773ecd053ea.png)

kapis/clusters/rohan/devops.kubesphere.io/v1alpha2/devops/simplenng9d/pipelines/github/runs/?start=0&limit=10&branch=v0.0.1

@LinuxSuRen

**Comment by LinuxSuRen** [comment]
This should be a listing page instead of `scan repository`. So it's ok without any data. You can trigger it if you want to have any data.

**Comment by harrisonliu5** [comment]
copy that, I will fix it as soon as possible
