### ISSUE TITLE
Refresh button is not working which in the projects choose dialog

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1536]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

The refresh buttons are not working in the projects choose dialog.

![image](https://user-images.githubusercontent.com/1450685/110123436-d80e2100-7dfb-11eb-8e36-d85c3d02568a.png)

![image](https://user-images.githubusercontent.com/1450685/110123647-1f94ad00-7dfc-11eb-8777-2e042a22fe4f.png)

/area devops
/priority medium

**Versions used(KubeSphere/Kubernetes)**
`kubespheredev/ks-console:nightly-20210304`

**Environment**
This is not an issue.

**To Reproduce**
1. Go to the DevOps Project page
2. Click on the left part to show the project choose dialog
3. See the errors

**Expected behavior**
The refresh buttons are working well or just hide them.

**Comment by leoendless** [comment]
This issue should have been fixed on the master branch.
