### ISSUE TITLE
Svg pictures display abnormally

### ISSUE THREAD

**Issue by tagGeeY** [kubesphere/console#1549]
Env:

`$node -v
v14.16.0

$yarn -v
1.22.10
`

I follow up [#issue 147 comment](https://github.com/kubesphere/console/issues/147#issuecomment-586861701), then `yarn start` successfully, but svg pics display very large, like this: 

![issue](https://user-images.githubusercontent.com/35259969/110459188-a3ee7500-8107-11eb-9700-61b73b2d4be6.png)

Does the version of `yarn` resulted this?

**Comment by leoendless** [comment]
Please reffer to https://github.com/kubesphere/console/tree/release-3.0#start-kubesphere-console-for-development
