### ISSUE TITLE
Discard the environment variables via graphic editing mode

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1575]
**Describe the bug**

Discard the environment variables via graphic editing mode.

/area devops
/priority high

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: `nightly-20210314`

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to the DevOps page
2. Create a pipeline with the Jenkinsfile from below
3. Edit the pipeline with graphic mode, then click the save button
4. Check the Jenkinsfile again.

A sample of Jekninsfile:
```
pipeline {
  agent any
  
  environment {
    APP = "hello"
  }
  
  stages {
    stage('simple') {
      steps {
        echo "My name is ${params.name}."
      }
    }
  }
}
```

**Expected behavior**
Do not discard the environment variables.

**Comment by harrisonliu5** [comment]
the data convert by API does not handle the environment data.

`kapis/clusters/gondor/devops.kubesphere.io/v1alpha2/tojson`

**Comment by LinuxSuRen** [comment]
There's another issue that the environment variables will be duplicated after https://github.com/kubesphere/kubesphere/pull/3588
