### ISSUE TITLE
Search input not aligned with background div.

### ISSUE THREAD

**Issue by zryfish** [kubesphere/console#1581]
**Describe the bug**

Search input not aligned with backgroud.

<img width="1182" alt="截屏2021-03-15 14 23 24" src="https://user-images.githubusercontent.com/3326354/111111830-062cf700-859a-11eb-8c0b-610dfe25799b.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: nightly-20210314
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @kubesphere/sig-console 
/milestone v3.1.0

**Comment by harrisonliu5** [comment]
Could you tell me the current environment, or try to clear the cache?

**Comment by leoendless** [comment]
Fixed in the latest build.
