### ISSUE TITLE
The style of the search input box in Alerting policy list is a mess

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1590]
**What would you like to be added**:

The style of the search input box in Alerting policy list is a mess.

The bad one:
![image](https://user-images.githubusercontent.com/1450685/111250871-1354ef00-8649-11eb-9e3b-1432013643ec.png)

The good one:
![image](https://user-images.githubusercontent.com/1450685/111250884-1b149380-8649-11eb-9c47-8a4e376bd103.png)

**Why is this needed**:
Having a consistent style of all the search input boxes.

/priority low
/kind feature-request

**Comment by zryfish** [comment]
duplicated with #1581
