### ISSUE TITLE
There is an error editing dependent permissions

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#1598]
**Environment**
`kubespheredev/ks-console:latest`

**To Reproduce**
1. Go to 'Access Control'
2. Click on 'Account Roles'
3. Click on 'Create'
4. Click on 'Edit Authorization' after enter name
5. Select 'Clusters Management'
6. Click the selection box before ’Cluster Management‘

**Expected behavior**
step5: 'Clusters Management' and 'Clusters View' have check mark
step6: 'Clusters View' have check mark

**Actual behavior**
step5: only 'Cluster View' has check mark
step6 ：
![image](https://user-images.githubusercontent.com/68640256/111271924-d7cc1c00-866c-11eb-89c9-6a4afafc66e0.png)

/kind bug
/assign @leoendless
/milestone 3.1.0
/priority high

**Comment by leoendless** [comment]
By design.
