### ISSUE TITLE
The build environment cannot be loaded out

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#1620]
**Describe the bug**
When building an image, the build environment does not load
![image](https://user-images.githubusercontent.com/36271543/111594589-34af0a00-8806-11eb-862b-3e357d063cf4.png)

/kind bug
/assign @leoendless 
/priority High
/milestone 3.1.0
/area console

**Comment by harrisonliu5** [comment]
this is the same #1666

**Comment by liuyp2018** [comment]
close
