### ISSUE TITLE
The build environment is not displayed on the build image page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#1666]
**Describe the bug**

The build environment is not displayed on the build image page
![image](https://user-images.githubusercontent.com/36271543/112286149-f8781f80-8cc5-11eb-854d-10c3d9a046cd.png)

/kind bug
/assign @leoendless
/milestone 3.1.0
/priority medium

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/112453266-7a357f00-8d92-11eb-86dc-28691f54d45a.png)

@liuyp2018

**Comment by harrisonliu5** [comment]
`apis/devops.kubesphere.io/v1alpha1/s2ibuildertemplates `

this API does not return the templates of jar

**Comment by shaowenchen** [comment]
In the test environment, the template data was lost.

**Comment by liuyp2018** [comment]
close
