### ISSUE TITLE
Filter Project Problem

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/console#1670]
**Describe the bug**

KubeSphere Host 3.1  & Member 3.0

After click the 'x' button, the context does not clear as expected.

![image](https://user-images.githubusercontent.com/20178386/112409017-b85f7e00-8d53-11eb-9118-8e83545b97b1.png)

/kind bug
/priority low
/area console

**Comment by Mrxyy** [comment]
I haven't found this problem in the process of fixing
/cc @kubesphere/sig-testing

**Comment by jioce** [comment]
issue fixed v3.2.0
/closed

**Comment by wenxin-01** [comment]
issue fixed in  `v3.2.0`

/close
