### ISSUE TITLE
The matching data cannot be queried by a fuzzy query in CRD details page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#1676]
**Describe the bug**
**steps:**
1. In the custom resource CRD details page
2. Set the query field to query

**Expected results:**
Matching data can be queried through fuzzy queries

**Actual results:**
The matching data cannot be queried by a fuzzy query

![image](https://user-images.githubusercontent.com/36271543/112431074-ff606a00-8d79-11eb-9dc7-4bd7d284e1f6.png)

/kind bug
/assign @leoendless
/milestone 3.1.0
/priority medium

**Comment by leoendless** [comment]
The k8s APIs does not support fuzzy query.
