### ISSUE TITLE
Deleted resources still exist in the CRD resource list

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#1685]
**Describe the bug**
**steps:**
1. On the CRD details page, go to page 2 of the list
2. Delete a CRD resource
3. After deletion, view the deleted resource

**Expected results:**
The deleted resource does not exist in the list

**Actual results:**
Deleted resources still exist in the list.
Click the refresh button in the list on page 2 ,the deleted resources still exist in the list.
When jumping to the first page and reenter page 2, the deleted resource will not appear in the list.

![image](https://user-images.githubusercontent.com/36271543/112567038-130fdd00-8e1b-11eb-9b2f-7509c6f2b59f.png)

/assign @leoendless
/priority High
/milestone 3.1.0
/area console

**Comment by zhanglin-doudou** [comment]
### Not reappearance
I created a CRD named cronTab.
![image](https://user-images.githubusercontent.com/15157210/127638007-6675e50e-c3b2-4ca3-bccc-198c2b0c4ffd.png)
![image](https://user-images.githubusercontent.com/15157210/127638087-9924ffde-e1b4-4262-a85b-6037b385aac0.png)

And open two pages, one is detials the other is list. I deleted  cronTab CRD. 
![image](https://user-images.githubusercontent.com/15157210/127638516-c2e430c5-1032-4294-9869-54417412ca53.png)
Next, I refresh above two pages.
![image](https://user-images.githubusercontent.com/15157210/127638517-600e3138-bc8d-4c3b-8d3a-5ddaf4019a9b.png)
![image](https://user-images.githubusercontent.com/15157210/127638559-394d3f72-38ea-4f21-86fe-0d917f7c9a6c.png)
![image](https://user-images.githubusercontent.com/15157210/127638656-77a1a0e2-612b-4d2b-8130-8429921e67d6.png)

It has been deleted.

/cc @kubesphere/sig-testing

**Comment by zhanglin-doudou** [comment]
@liuyp2018

**Comment by zryfish** [comment]
Cannot reproduce, will reopen if this issue gets enough feedback.
/close
