### ISSUE TITLE
style problem in Creating Homemade Application -- Service Component page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#1701]
**Describe the bug**
In multi-cluster project, there is style problem in Creating Homemade Application -- Service Component page
![image](https://user-images.githubusercontent.com/36271543/112793072-32b33980-9097-11eb-9f96-292d95ac9324.png)

/kind bug
/assign @leoendless 
/priority Low
/milestone 3.1.0

**Comment by leoendless** [comment]
By design. When hovering, the operation buttons on the right will appear above the text on the right.
