### ISSUE TITLE
The style of the label is not aligned while displaying the detail of topology

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#1702]
**Describe the bug**

![image](https://user-images.githubusercontent.com/43693241/112793195-6d1cd680-9097-11eb-97d5-8d013dde3397.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.1.0

The style of the label is not aligned.

**Comment by leoendless** [comment]
By design. The label is aligned to the right, and the value is aligned to the left.
