### ISSUE TITLE
Support 'select all' when deleting related resource of a specified workload

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/console#1735]
KubeSphere 3.0.0
Prereq:
Create a workload with some related resource, like pvc...etc
Step:
1. Delete this workload, a msg will pop up and ask the user to select the related resource to delete together

When the resource list is too long, it will be more efficient to provide a 'select all' option
![WechatIMG1425](https://user-images.githubusercontent.com/28883416/113234466-e143be00-92d3-11eb-9bd6-7089f6dd2de8.png)

**Comment by jioce** [comment]
issue fixed v3.2.0
/closed

**Comment by wenxin-01** [comment]
issue fixed in  `v3.2.0`

/close
