### ISSUE TITLE
No member-clusters are displayed in 'Cluster resource consumption'.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#1749]
**Environment**
`host 3.1 + member 3.1 + member 3.0`
http://139.198.9.112:30883

**To Reproduce**
1. Go to 'Toolbox'
2. Click on 'Metering and Billing'
3. Click on 'View Consumption' in 'Cluster resource consumption'

**Expected behavior**
see all clusters

**Actual behavior**
only see host-cluster

![image](https://user-images.githubusercontent.com/68640256/113401246-a7f37700-93d5-11eb-9aea-2871c42cfc7e.png)

/priority high
/cc @harrisonliu5 
/kind bug
/milestone 3.1.0

**Comment by harrisonliu5** [comment]
The clusters that are not shown are because they do not have the right to meter billing

**Comment by yunkunrao** [comment]
Yes, in current metering design metering cluster list only show cluster which enabled metering module. So it's expected.
