### ISSUE TITLE
Cluster display error of workspace in 'Workspace (project) resource consumption'

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#1750]
**Environment**
`host 3.1 + member 3.1 + member 3.0`
http://139.198.9.112:30883

**To Reproduce**
1. Go to 'Toolbox'
2. Click on 'Metering and Billing'
3. Click on 'View Consumption' in 'Workspace (project) resource consumption''

**Actual behavior**
![image](https://user-images.githubusercontent.com/68640256/113402379-7d0a2280-93d7-11eb-8db4-a503a4a5568e.png)

/priority high
/cc @harrisonliu5 
/kind bug
/milestone 3.1.0

**Comment by harrisonliu5** [comment]
The clusters that are not shown are because they do not have the right to meter billing

**Comment by wenxin-01** [comment]
issue fixed
