### ISSUE TITLE
The UI of the Pipeline basic information edit dialog is chaos

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1781]
**Describe the bug**
The UI of the Pipeline basic information edit dialog is chaos. Please see the following screenshots:

![image](https://user-images.githubusercontent.com/1450685/114355023-91050f80-9ba1-11eb-802e-fba0ffb30c10.png)

![image](https://user-images.githubusercontent.com/1450685/114355050-9b270e00-9ba1-11eb-9b23-54d3f09a3dca.png)

/area devops
/priority low
/kind bug
/good-first-issue

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: `nightly-20210411`

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to the DevOps project page
2. Create a Pipeline
3. Edit the basic information of the Pipeline
4. See style of UI

**Expected behavior**
Expect a clean style of the Pipeline dialog.

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
