### ISSUE TITLE
show tracing tab

### ISSUE THREAD

**Issue by zackzhangkai** [kubesphere/console#1782]
Now, if we enabled servicemesh plugin, the logging pods are already. So we should show the tracing tab by default.

![image](https://user-images.githubusercontent.com/20178386/114360076-35d61b80-9ba7-11eb-8d7a-1d50264c84c6.png)

```
# k get po -n kubesphere-logging-system
NAME                                                              READY   STATUS      RESTARTS   AGE
elasticsearch-logging-curator-elasticsearch-curator-161798zzfg8   0/1     Completed   0          2d14h
elasticsearch-logging-curator-elasticsearch-curator-161807dd8qc   0/1     Completed   0          38h
elasticsearch-logging-curator-elasticsearch-curator-161816t9dsj   0/1     Completed   0          14h
elasticsearch-logging-data-0                                      1/1     Running     1          17d
elasticsearch-logging-data-1                                      1/1     Running     1          17d
elasticsearch-logging-discovery-0                                 1/1     Running     1          17d
```

/assign @leoendless 
/area microservice
/area console

**Comment by harrisonliu5** [comment]
The condition for displaying tracing is that the cluster needs to enable the logging module。

![image](https://user-images.githubusercontent.com/17872673/117936623-a8b5ec00-b337-11eb-9b56-f5afee8873ad.png)

@zackzhangkai

**Comment by zackzhangkai** [comment]
Just take servicemesh as the condition, no need to verify logging.
@harrisonliu5

**Comment by zackzhangkai** [comment]
verified.
