### ISSUE TITLE
Checkbox doesn't work for kubernetesDeploy step while adding a deploy stage

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#1794]
**Describe the bug**

Checkbox doesn't work for kubernetesDeploy step while adding a deploy stage

![image](https://user-images.githubusercontent.com/16865714/114716487-ad9e7480-9d66-11eb-80c1-b21c3942635a.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: nightly-20210412
Kubernetes: 1.19.0

**Environment**
How many nodes and their hardware configuration: 

1 masters:  4cpu/8g
1 nodes: 4cpu/8g

(and other info are welcomed to help us debugging)

**To Reproduce**
Go to the DevOps project page
Create a Pipeline
Edit the basic information of the Pipeline
See style of UI
1. Go to the DevOps project page
2. Create a pipeline
3. Click Edit Pipeline
4. Select Custom Pipline
5. Click add icon
6. Click Add Step
7. Select kubernetesDeploy step on the right
8. Click two checkbox
4. See error: nothing to be changed

**Expected behavior**

Both of checkboxs should be responsive when we click them.

**Comment by JohnNiang** [comment]
And description of `enableConfigSubstitution` checkbox is missed also.

**Comment by JohnNiang** [comment]
The second checkbox doesn't work now as follows:

![image](https://user-images.githubusercontent.com/16865714/116100012-1d095200-a6df-11eb-812e-8b7e543469c4.png)

Please have an inspect of this issue @harrisonliu5

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/116184230-ea4c7180-a751-11eb-9d9f-65bef11eccd7.mp4

**Comment by harrisonliu5** [comment]
please give a environment for me

**Comment by JohnNiang** [comment]
> please give a environment for me

Wait a second please. I'll build a latest environment for you.

**Comment by JohnNiang** [comment]
@harrisonliu5 Sorry about that. It works very well in latest environment.
