### ISSUE TITLE
Stage agent label is reset while drawer is blur in pipeline graphic editor

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#1810]
**Describe the bug**

Stage agent label is reset while drawer is blur in pipeline graphical interface.

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

1 master: 4c/8g
1 node: 4c/8g

**To Reproduce**

1. Go to DevOps Project
1. Create a pipeline by default
1. Click `Edit Pipeline`
2. Select Custom Pipeline
3. Add a stage
4. Select stage agent type with node
5. Select stage agent label with maven
6. Click outside of drawer
7. Click the stage again
8. See the agent label value(reset by default)

**Expected behavior**

Do not reset my agent label when stage setting drawer is closed without confirming.

**Comment by harrisonliu5** [comment]
This problem is not reproduced in the current console environment @JohnNiang

**Comment by JohnNiang** [comment]
1. Change stage agent label:

![image](https://user-images.githubusercontent.com/16865714/117947731-11569600-b343-11eb-9c76-db7dd6b54b81.png)

2. Blur (Do not click confirm button) the drawer, and then check the label:

![image](https://user-images.githubusercontent.com/16865714/117947927-3ba85380-b343-11eb-8785-66085126779b.png)

**Comment by harrisonliu5** [comment]
sorry, I sent a comment message in the wrong place.
