### ISSUE TITLE
The permissions list of 'Workspace Setting' is wrong

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#1813]
**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `dev:latest`

**Preset conditions**
there is a workspace named 'test'

**To Reproduce**
1. Go to workspace 'test'
2. Click on 'workspace setting'
3. Click on 'Workspace Roles'
4. click on 'create'
5. click on 'Edit Permissions' after input name
6. clcik on 'Workspace Settings'

**Expected behavior**
there are 'view workspace settings' and 'manage workspace settings' in Permissions list

**Actual behavior**
There are two 'Workspace Settings' in Edit Permissions list
![image](https://user-images.githubusercontent.com/68640256/115242987-000bd680-a155-11eb-96da-6fe56110beba.png)

/kind bug
/assign @harrisonliu5 
/milestone 3.1.0
/priority medium

**Comment by harrisonliu5** [comment]
`kapis/iam.kubesphere.io/v1alpha2/workspaces/testliu/workspaceroles?label=iam.kubesphere.io/role-template=true`

there is two 'Workspace Setting' return from this API.

/assign @wansir

**Comment by harrisonliu5** [comment]
fixed by https://github.com/kubesphere/kubesphere/issues/3754

**Comment by wenxin-01** [comment]
issue fixed `kubesphere v3.1.1-rc.0`

![image](https://user-images.githubusercontent.com/68640256/123744038-c0920100-d8e0-11eb-83f0-cb641c400c36.png)
