### ISSUE TITLE
The navigation button confused people due to the gray color

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1818]
**What would you like to be added**:
Set a common color of the clickable button on the Metering and Billing page. Please see the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/115353376-0351a180-a1eb-11eb-9b51-5b03b8b474c3.png)

**Why is this needed**:
As I mentioned in the title, the navigation button on the Metering and Billing page confused people due to the gray color. Normally, the buttons are colorful if it's clickable.

**Comment by liuyp2018** [comment]
not fixed in v3.1.1-rc.1

**Comment by harrisonliu5** [comment]
This PR does not merge into v3.1.1-rc1. @liuyp2018

**Comment by jioce** [comment]
issue fixed v3.2.0
/closed

**Comment by wenxin-01** [comment]
issue fixed in  `v3.2.0`

/close
