### ISSUE TITLE
Add cluster upgrade prompt information in metering and billing.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#1825]
**Environment**
`dev:latest`

![image](https://user-images.githubusercontent.com/68640256/115493917-30f42480-a297-11eb-995a-774e64a1f559.png)
![image](https://user-images.githubusercontent.com/68640256/115493962-449f8b00-a297-11eb-8744-72a24204145d.png)

**Expected behavior**

For non-3.1 clusters, use the prompt information and identification in the figure below.
![image](https://user-images.githubusercontent.com/68640256/115493994-584af180-a297-11eb-9271-07dc0f8ecfb7.png)

/kind bug
/assign @harrisonliu5 
/milestone 3.1.0
/priority low

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/118244956-c1a6d480-b4d2-11eb-824d-390af920cc87.png)

**Comment by wenxin-01** [comment]
issue fixed `ks3.1`
