### ISSUE TITLE
UI adjustment for Metering and Billing

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#1827]
**Versions used(KubeSphere/Kubernetes)**
KubeSphere: `dev:latest`

![image](https://user-images.githubusercontent.com/68640256/115518615-f8664200-a2ba-11eb-8869-8e93003c4ea3.png)

![image](https://user-images.githubusercontent.com/68640256/115518705-12a02000-a2bb-11eb-923f-971886555bf2.png)

/kind bug
/assign @harrisonliu5
/milestone 3.1.0
/priority low

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/118242839-51974f00-b4d0-11eb-8562-b686cbac129c.png)

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/118243939-98397900-b4d1-11eb-84e3-ef953f98acb0.png)

**Comment by wenxin-01** [comment]
Need to optimize

![image](https://user-images.githubusercontent.com/68640256/122154689-19e94180-ce98-11eb-97bc-d03c42ef83d8.png)

**Comment by jioce** [comment]
issue fixed v3.2.0
/closed
