### ISSUE TITLE
the Alert Monitoring section is not available to project-regular

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#1829]
For the same alerting policy, the Alert Monitoring section is not available to project-regular (`operator` role in the project) but admin can see it.

Environment: KubeSphere 3.1.0 latest

![Xnip2021-04-21_17-52-46](https://user-images.githubusercontent.com/65327072/115534886-d1b00780-a2ca-11eb-9acb-b35ab7098d7c.png)
<img width="1328" alt="Xnip2021-04-21_17-53-00" src="https://user-images.githubusercontent.com/65327072/115534921-d8d71580-a2ca-11eb-962b-ff303dc24acb.png">

**Comment by junotx** [comment]
The api `/namespaces/{namespace}/targets/query` should be called to query expr for the alerting rules under the projects. A similar situation exists in the following page of one project. @harrisonliu5 

![image](https://user-images.githubusercontent.com/49136171/115536095-fce72680-a2cb-11eb-8c5b-a5e4b2208ed5.png)
