### ISSUE TITLE
screenshots of app template were still deleted when delete screenshots but not to save

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#1830]
**Describe the bug**

Screenshots of app template were still deleted when edit template and click  "delete all" to delete screenshots but not to save

![image](https://user-images.githubusercontent.com/49136171/115532924-d378cb80-a2c8-11eb-8efb-9872c16cb0f3.png)

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: latest(20210421)

**Expected behavior**

Screeshots should be deleted if and only if the edit is saved

/kind bug
/assign @zheng1

**Comment by liuyp2018** [comment]
the issue is fixed
