### ISSUE TITLE
app template version was set to chinese and submitted successfully

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#1832]
**Describe the bug**

set version to a chinese string when submit app template to review, and it can be submitted successfully

![image](https://user-images.githubusercontent.com/49136171/115647128-dd94db80-a355-11eb-877e-c732503b01bb.png)
![image](https://user-images.githubusercontent.com/49136171/115647170-f00f1500-a355-11eb-8ec2-0d8cfdf1cba1.png)

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: latest(20210422)

**Expected behavior**

page should prompt that the version is not properly formmated, and the form cannot be submitted

/kind bug
/assign @harrisonliu5

**Comment by liuyp2018** [comment]
verified and fixed
