### ISSUE TITLE
search box for app store are not cleaned up when click x

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#1843]
**Describe the bug**

1. click **X** after searching by keyword `om`
![image](https://user-images.githubusercontent.com/49136171/115812274-b6a4db00-a423-11eb-8a98-e3ce25d248e5.png)
2. content in seach box are not cleaned up although the list is refreshed
![image](https://user-images.githubusercontent.com/49136171/115812372-d5a36d00-a423-11eb-9030-7158fc5f30fe.png)
3. search can not be finished when click keyboard enter after the cursor moves back into the search box

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: latest(20210423)

**Expected behavior**

search box should be cleaned up when click x

/kind bug
/priority middle
/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/117786469-1bf82900-b278-11eb-9596-2ded6d2b8b39.mp4

@junotx

**Comment by liuyp2018** [comment]
Verify that the problem has been fixed
