### ISSUE TITLE
After creating a long user name in KubeSphere 3.0, deleting the user will cause the system to crash.

### ISSUE THREAD

**Issue by TinaSprunt** [kubesphere/console#1844]
**General remarks**

KubeSphere 3.0 installed with ks-installer,after creating a long user name in KubeSphere 3.0, deleting the user will cause the system to crash.

**Describe the bug**

The back-end code of this issue is being repaired,details about:

[#3796](https://github.com/kubesphere/kubesphere/issues/3796)
[#3784](https://github.com/kubesphere/kubesphere/issues/3784)

![2222](https://user-images.githubusercontent.com/38268966/115831783-a2250a80-a444-11eb-9f72-11e4a0d1e7f4.png)

After fixing the back-end code, if the user name created by the user is too long, the back-end will throw an error to the web interface

![1111](https://user-images.githubusercontent.com/38268966/115832159-24153380-a445-11eb-8f69-61b2e43a0bc3.png)

Maybe we should：
    - 1.Make necessary user prompts on the console
    - 2.Limit user input length

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: 3.0（It is expected that 3.1 will also have this problem.）
Kubernetes: 1.18.8

**Expected behavior**

1.Make necessary user prompts on the console
2.Limit user input length

/kind bug

**Comment by fuchunlan** [comment]
We can not type more than 32 characters in the username input box now, please check it.
![image](https://user-images.githubusercontent.com/63338728/120737199-385a4f00-c520-11eb-8287-55ded1d1c8b3.png)
