### ISSUE TITLE
app template review list has more entries than limit

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#1847]
**Describe the bug**

It was more than the limt in the application template review list 

![image](https://user-images.githubusercontent.com/49136171/115980124-dae7ef80-a5bc-11eb-8da4-f6b62b5013d5.png)

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: latest(20210425)

**To Reproduce**
1. Go to the detail page of  app template 
2. Submit for review and then cancel review, repeated six times
3. Click on app review tab,  and click on the next page then click on the previous page
3. See error

**Expected behavior**

The entries count should be equal to the limit, or less than the limit (for the last page)

/kind bug
/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
This problem is not reproduced in the current console environment @junotx

**Comment by liuyp2018** [comment]
The problem has not been reproduced. Please confirm whether the problem exists @junotx

**Comment by jioce** [comment]
issue fixed v3.2.0
/closed

**Comment by wenxin-01** [comment]
issue fixed in  `v3.2.0`

/close
