### ISSUE TITLE
Cannot select metric items on the custom monitoring page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1865]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When I try to add metrics of argocd, it's not able to get all metrics due the UI issues.

![image](https://user-images.githubusercontent.com/1450685/116642887-6806bc00-a9a2-11eb-9a63-b861569b120e.png)

![image](https://user-images.githubusercontent.com/1450685/116642942-82d93080-a9a2-11eb-94a5-6dbe04e881b7.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: `kubespheredev/ks-console:nightly-20210420`

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to the Custom Monitoring page
2. Find a metrics category that has a lot

**Expected behavior**
Users can get all metrics of a component.

**Comment by LinuxSuRen** [comment]
I cannot select the item with version v3.2.0. See the screenshot

![image](https://user-images.githubusercontent.com/1450685/141745403-96bf5fa3-2784-48b6-9ef3-6835ee392f57.png)

**Comment by liuyp2018** [comment]
fixed in release v3.2.0
/close
