### ISSUE TITLE
The multi-branch Pipeline run API is incorrect

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1877]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
As you can see, the API calling is incorrect.

The incorrect API address: `http://ip:port/kapis/devops.kubesphere.io/v1alpha2/devops/{devops}/pipelines/{pipeline}/runs`

The correct API address: `http://ip:port/kapis/devops.kubesphere.io/v1alpha2/devops/{devops}/pipelines/{pipeline}/branches/{branch}/runs`

![image](https://user-images.githubusercontent.com/1450685/117756251-6d8cbd80-b250-11eb-9189-bcf58949ad87.png)

/area devops
/priority high

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.0

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to the DevOps project page
2. Create a Pipeline with Gitlab as source
3. Go to the master branch Pipeline page.
4. Click the `Run` button
5. Nothing happend

**Expected behavior**
The branch Pipeline can be trigger manually.

**Comment by LinuxSuRen** [comment]
What makes me feel confused is that GitHub multi-branch Pipeline is fine.

**Comment by LinuxSuRen** [comment]
> What makes me feel confused is that the GitHub multi-branch Pipeline is fine.

I just tested it again. It always failed when you create a multi-branch (Gitlab or GitHub) that has the Pipeline parameters.

In case of anyone who wants to try it, you can use [this repo](https://github.com/devops-ws/learn-pipeline-java) with `Jenkinsfile-parameters.groovy`

**Comment by JohnNiang** [comment]
I'm going to close this issue due to the [fix](https://github.com/kubesphere/console/pull/1900). Please feel free to reopen this issue if you have the same problem.
