### ISSUE TITLE
Incorrect select items of multi-branch Pipeline Trusted User

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1898]
**Describe the bug**
As I mentioned in the title, please see the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/118427275-69a0e580-b6ff-11eb-8622-c2843fcbe0db.png)

/priority medium
/area devops
/milestone 3.1.1

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.0

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Create a GitHub multi-branch Pipeline
2. Edit the Pipeline
3. Remove the strategy `Discover PR from Forks`
4. Click the `Add Action` button, choose `Discover PR from Forks`
5. See the wrong selection items of `Trusted User`

**Expected behavior**
Having readable select items of `Trusted User`.

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/118465665-ae933f00-b734-11eb-9a44-25cd4fc23af5.mp4

**Comment by LinuxSuRen** [comment]
https://user-images.githubusercontent.com/1450685/118574640-6f5a0200-b7b7-11eb-8b11-a092d57ad7eb.mp4

**Comment by LinuxSuRen** [comment]
https://user-images.githubusercontent.com/1450685/118574896-fdce8380-b7b7-11eb-9b19-963c7983c8cc.mp4

**Comment by liuyp2018** [comment]
Verified and fixed in v3.1.1-rc.1

**Comment by LinuxSuRen** [comment]
hi @liuyp2018 , thanks for helping to verify this issue. I'm going to close it.
/close
