### ISSUE TITLE
No web terminal for the containers under system-workspace

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/console#1915]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
No web terminal for the containers under system-workspace

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**To Reproduce**
1. Go to 'system-workspace', drill down to any container

**Expected behavior**
A web terminal link should be shown on this container

**Comment by liuyp2018** [comment]
verified and fixed in v3.1.1-rc.1
