### ISSUE TITLE
Optimize the editing config yaml of resources in multi-cluster projects

### ISSUE THREAD

**Issue by harrisonliu5** [kubesphere/console#1916]
**What would you like to be added**:
Add 'Edit Config Template' in 'Application Workloads' and 'Volumes'.

**Why is this needed**:
Editing the configuration YAML of a single resource cannot be edited with a step-by-step visual configuration like a normal project.

- [x] Workloads    @xuliwenwenwen 
- [x] Services       @harrisonliu5 
- [x] Routes          @xuliwenwenwen
- [x] Volume         @fuchunlan

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
