### ISSUE TITLE
Inconsistent button name in the ImageBuilder page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1919]
**Describe the bug**

![image](https://user-images.githubusercontent.com/1450685/119631285-50f0a800-be42-11eb-89d5-1501a7636f27.png)

/area devops
/priority high

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.0

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to the ImageBuilder page
2. Create a builder
3. Click the `Run` button, check the name

**Expected behavior**
Having consistent button name.

**Comment by LiteSun** [comment]
As #1922 is merged, This issue can be closed. cc @fuchunlan

**Comment by JohnNiang** [comment]
I've confirmed that the issue has been fixed by #1922.
