### ISSUE TITLE
Unable to get the node label list of member cluster

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1924]
**Describe the bug**
Having a multi-cluster environment. The node label list is empty when users try to create a Pipeline with graphic mode. The Pipeline belongs to a member cluster. As you can see below, the API request got a 404 response.

![image](https://user-images.githubusercontent.com/1450685/120144564-b82ca480-c214-11eb-9028-9d461843a11a.png)

According to my tests. The following API request is ok:

`http://ip:port/kapis/clusters/member/devops.kubesphere.io/v1alpha2/devops/solo-projecthcbrh/jenkins/labelsdashboard/labelsData`

The incorrect API is: `http://ip:port/kapis/devops.kubesphere.io/v1alpha2/devops/solo-projecthcbrh/jenkins/labelsdashboard/labelsData`

/area devops
/priority high

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: `v3.1.0`

The host and member cluster are all `v3.1.0`.

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Have two cluster, the host cluster named `host`; the member cluster named `member`
2. Create a Pipeline on a member cluster
3. Select the node label on the Pipeline graphic editing page
4. No label items

**Expected behavior**
The node labels list cannot be empty on the member cluster.

**Comment by LinuxSuRen** [comment]
hi @kubesphere/sig-console team, please take a look at this issue.

**Comment by wenxin-01** [comment]
If both host and member clusters have enabled `devops`,  this problem is not found, but only member cluster has enabled `devops`, which will cause this problem.

**Comment by LinuxSuRen** [comment]
hi @wenxin-01 , thanks for the additional information.
