### ISSUE TITLE
Couldn't go back one page at pipeline detail page

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#1928]
**Describe the bug**

Couldn't go back one page at pipeline detail page.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: latest-dev
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

For example:
1 masters:  8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**
1. Go to single pipeline page
2. Click **Go back one page <--** button in browser
3. See error

**Expected behavior**

Go back one page when I click **Go back one page <--** button in browser.

/kind bug
/area devops
/priority high

**Comment by harrisonliu5** [comment]
It would be more intuitive to illustrate this bug for a screenshot or short video, thanks.

**Comment by JohnNiang** [comment]
@harrisonliu5 

This page won't be went back to `Pipeline List` page while I click the `Go back` button.

![image](https://user-images.githubusercontent.com/16865714/120954307-76a27900-c781-11eb-8d1e-1d0d75b51992.png)
