### ISSUE TITLE
Cannot drag and drop tasks to sort in pipeline editor

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#1930]
**Describe the bug**
I cannot drag and drop tasks to sort in pipeline editor.

![image](https://user-images.githubusercontent.com/16865714/120879606-3b743e80-c5f7-11eb-9f1b-3b8fe11ab250.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.0

**To Reproduce**
1. Go to 'Pipeline Editor'
2. Create some tasks
3. Try to drag and drop tasks to sort
4. No effect

**Expected behavior**
Make tasks sortable.

/kind bug
/area devops
/priority low

**Comment by LinuxSuRen** [comment]
hi @harrisonliu5 , I don't know if the feature exists. I'd suggest turning this issue to be a feature request. Anyway, in my opinion, the incorrect description does not block anyone. So I prefer the priority of this issue is low.

**Comment by JohnNiang** [comment]
@LinuxSuRen Here is a explanation about the feature facing performance issue: <https://github.com/kubesphere/console/pull/1931#issuecomment-855659642>.
