### ISSUE TITLE
Inconsistent image name validation when creating a new service from s2i

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#1952]
**Describe the bug**

See from the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/122040339-40f93200-ce0a-11eb-8e56-3548ec177e80.png)

![image](https://user-images.githubusercontent.com/1450685/122040174-160ede00-ce0a-11eb-8c0d-0f2f5da36d29.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.1

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to the S2I page
2. Create new service from S2I
3. Input the image name with a name that has a capital word
4. See the errors

**Expected behavior**
Get an error tip before submitting the form.

**Comment by liuyp2018** [comment]
fixed in release v3.2.0
/close
