### ISSUE TITLE
Container log only showed the previous container logs, not current container's

### ISSUE THREAD

**Issue by zryfish** [kubesphere/console#1972]
**Describe the bug**
In pod detail page, click into container details, view container log. It only showed the previous container log, the request like the following 

```
http://xxxxx/api/v1/namespaces/kubesphere-system/pods/ks-console-5576fccbb8-scbjq/log?container=ks-console&tailLines=1000&timestamps=true&follow=false&previous=true
```

the request parameter `previous=true` means to retrieve the previous container log.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.0

**Expected behavior**
Shows the current container log

/kind bug

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
