### ISSUE TITLE
UI theme

### ISSUE THREAD

**Issue by Viviannn** [kubesphere/console#198]
请问是否可以添加换主题的功能呢？

虽然提供的有variables.scss、lego.theme.scss、lego.custom.scss等样式文件
但是项目中还是有很多零散的样式
想要改主题色还需要手动去搜索更改
并且涉及的文件还是挺多的

后续可否在现有基础上统一样式添加换主题的功能呢？

**Comment by leoendless** [comment]
目前主要聚焦在业务功能上，后期可能会对此功能进行调整。另外欢迎给项目提 pr 来改善目前的样式切换问题

**Comment by rayzhou2017** [comment]
Please use English
