### ISSUE TITLE
editing container configuration template page, the input box validation rule is incorrect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2010]
**Describe the bug**
**steps:**
1.Go to the Workload -- Edit the Configuration Template page
2.Modify update policy - Number of container groups when updating
3.Enter the quantity in the input box to save

**Expected behavior:**
It can be successfully saved

**actual results:**
Unable to save successfully. Error message appears on page

![image](https://user-images.githubusercontent.com/36271543/122899299-4a404c80-d37e-11eb-8a44-828f16e90ee1.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: ks v3.1.1
ks-console image : kubespheredev/ks-console:latest

/kind bug
/assign @harrisonliu5 
/priority Medium
/milestone 3.1.0
/area console

**Comment by liuyp2018** [comment]
and suggestion that  optimizing  the text prompts:
![image](https://user-images.githubusercontent.com/36271543/122902900-77422e80-d381-11eb-85b9-49f3e7fb49d4.png)

**Comment by wansir** [comment]
Do not include quotation marks in numeric types.

**Comment by fuchunlan** [comment]
Other issues need to be fixed in the background

**Comment by liuyp2018** [comment]
fixed
