### ISSUE TITLE
Do not translate "ConfigMap" into "配置" and "Secret" into "密钥".

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#2035]
![image](https://user-images.githubusercontent.com/76198553/123577234-0332db00-d806-11eb-8ca8-171951c1a9b2.png)
"密钥" means a private key or public key used to encrypt or decrypt certain information.
"配置" means a software or hardware configuration.
Both are too general and misleading. ConfigMap and Secret are concepts unique to Kubernetes, and we should not translate them.
/priority Medium
/milestone 3.2.0
/area console

**Comment by weili520** [comment]
The text has switched to:

![截屏2022-03-14 16 30 13](https://user-images.githubusercontent.com/33231138/158134068-7160f070-cd8d-4998-8d62-1894030e7ce5.png)

so, maybe we should close it after verified.

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172288523-a094551e-5424-4018-94d7-6fb71fb4cd57.png)

version used
kubesphere：v3.3.0-rc.1
