### ISSUE TITLE
need to add close button for adding application template window

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2040]
**Describe the bug**
need to add close button for adding application template window
![image](https://user-images.githubusercontent.com/36271543/123614412-e367db00-d836-11eb-9b1f-43693809fee7.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: ks v3.1.1

/assign @harrisonliu5 
/priority Medium
/milestone 3.1.0
/area console

**Comment by liuyp2018** [comment]
need to add close button for this dialog
![image](https://user-images.githubusercontent.com/36271543/123730499-05aa3900-d8c9-11eb-911b-e91c4876446f.png)

/remove-kind need-to-verify

**Comment by liuyp2018** [comment]
also need to add  close button for this dialog
![image](https://user-images.githubusercontent.com/36271543/125917054-40c8ee4f-8a1a-4c13-a93b-b9bae50480c8.png)

**Comment by harrisonliu5** [comment]
This is the same as #2110

**Comment by liuyp2018** [comment]
fixed
