### ISSUE TITLE
Follow the steps in the Developer Guide  and I' m get stuck when using 'yarn'

### ISSUE THREAD

**Issue by zqn1217** [kubesphere/console#206]
![微信截图_20200326155315](https://user-images.githubusercontent.com/38694442/77623401-02fcbd80-6f7b-11ea-98eb-7ae070aea63e.png)
What should I do？

**Comment by leoendless** [comment]
This is a problem with your local network. Please try some npm repo registries such as ``https://registry.npm.taobao.org``
