### ISSUE TITLE
The cursor should be clickable when we move it on the project area.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#2080]
We could switch the project by moving the cursor to the left upper corner，but it would be better that the cursor will change the shape to show the area is clickable，or we can set a entrypoint at the area.
![项目切换光标.png](https://i.loli.net/2021/07/01/LnZgQMp2xGbAjBR.png)

/area console
/kind feature-request
/cc @kubesphere/sig-console

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
