### ISSUE TITLE
Summary of multi cluster configuration problems

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#2092]
**Versions Used**
KubeSphere: `v3.1.1-rc.1`

`Resource requests should not be greater than resource limits`

https://user-images.githubusercontent.com/68640256/124448586-33a1e880-ddb5-11eb-8950-530df3a09dc1.mov

`Service Settings error`

https://user-images.githubusercontent.com/68640256/124448855-74016680-ddb5-11eb-9f8d-a121d8ec235e.mov

`Environment Variables error`

https://user-images.githubusercontent.com/68640256/124449098-b034c700-ddb5-11eb-8cf6-aeccd9955211.mov

/kind bug
/assign @harrisonliu5
/priority Medium
/milestone 3.1.1

**Comment by wenxin-01** [comment]
`Resource requests should not be greater than resource limits`  did not fix @harrisonliu5

**Comment by harrisonliu5** [comment]
> **Versions Used**
> KubeSphere: `v3.1.1-rc.1`
> 
> `Resource requests should not be greater than resource limits`
> 
It will be fixed in the next version .

**Comment by wenxin-01** [comment]
issue fixed `ks-console nightly-20210929`
![image](https://user-images.githubusercontent.com/68640256/135404773-b4eb6d5c-6eb2-47fa-a31c-1a819169c8d8.png)
