### ISSUE TITLE
Missing gitlab option in 'Select Code Repository'.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#2094]
KubeSphere: `v3.1.1-rc.1`

![image](https://user-images.githubusercontent.com/68640256/124717295-93c09800-df37-11eb-9bb4-a0cd5cea6cec.png)

/kind bug
/assign @harrisonliu5
/priority High
/milestone 3.1.1

**Comment by Felixnoo** [comment]
Same issue in KubeSphere v3.1.1.

**Comment by wenxin-01** [comment]
issue fixed `ks nightly-20210928`
