### ISSUE TITLE
Setting workspace/ project/pod quota error

### ISSUE THREAD

**Issue by yinmin090922** [kubesphere/console#2102]
Describe the bug
Two issues occurred when setting resource requests and resource limits with the keyboard in the workspace/ project/pod quota.

Versions used
KubeSphere: v3.1.1-dirty

To Reproduce
1. Go to page 'The workspace/project/pod quota'
2. Use the keyboard to set resource requests and resource limits.
3. The first issue:
    When you need to enter a decimal, you must enter two decimal points in a row to display it.
4. The second issue:
    There are no restrictions in resources limit input maximum.When the input enough digital display the results do not tally with the input data. When I enter many number 8 results are as follows.
    
![image](https://user-images.githubusercontent.com/50839324/125273332-64e36100-e33f-11eb-9bc2-eb9463f74417.png)
/kind bug
/assign @kubesphere/sig-console
/priority medium

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
