### ISSUE TITLE
Setting resource quota error

### ISSUE THREAD

**Issue by yinmin090922** [kubesphere/console#2104]
Describe the bug
One issue occurred when setting resource quota with the keyboard in the project quota.

Versions used
KubeSphere: v3.1.1-dirty

To Reproduce
1. Go to page 'The workspace/project/pod quota'
2. Use the keyboard to set resource quota.
3. When the input value is infinite, the result is "Infinity".
4. Click "save".The resource quota is "0".
![image](https://user-images.githubusercontent.com/50839324/125381991-74a68800-e3c7-11eb-865d-b13b1de3ed3b.png)
![image](https://user-images.githubusercontent.com/50839324/125381992-74a68800-e3c7-11eb-91ec-9123ffad8431.png)

Expected behavior
![image](https://user-images.githubusercontent.com/50839324/125382566-76bd1680-e3c8-11eb-840f-60977c53c870.png)
/kind bug
/assign @kubesphere/sig-console
/priority low

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
