### ISSUE TITLE
'About' window can't be closed automatically when moving mouse and clicking out of 'About' window

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/console#2110]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
'About' window can't be closed automatically when moving mouse and clicking out of 'About' window

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.1.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 
1 masters:  8cpu/8g
2 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**
1. Go to 'About' menu on the right top of the console
2. Click on 'About' menu, The KubeSphere About window is shown
3. 'About' window can't be closed automatically when moving mouse and clicking out of 'About' window
**Expected behavior**
 'About' window can be closed automatically

**Comment by liuyp2018** [comment]
this issue has been fixed and can be closed
