### ISSUE TITLE
The support of the lifecyle management consisting of the poststart and the prestop on console.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#2112]
As title.

/assign

**Comment by VioZhang** [comment]
The design drawing as follow： 
https://www.figma.com/file/vFx0DrJ1zRM3pCPvGIs3HH/Lifecycle-Hooks?node-id=2%3A539

**Comment by VioZhang** [comment]
The drawing design:
https://www.figma.com/file/vFx0DrJ1zRM3pCPvGIs3HH/Lifecycle-Hooks?node-id=2%3A539

**Comment by XiaohuiSept** [comment]
> The drawing design: https://www.figma.com/file/vFx0DrJ1zRM3pCPvGIs3HH/Lifecycle-Hooks?node-id=2%3A539

The new link:
https://www.figma.com/file/ZRvI25Lr3phV5a9mNu6jL9/KubeSphere-3.2.0?node-id=1118%3A373106

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.0`
![image](https://user-images.githubusercontent.com/68640256/170226117-cbd52523-1bb5-4232-8df9-305a0aa1dcc5.png)
