### ISSUE TITLE
Add user to project 400 Error when project has more than 10 users

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#214]
Error tips:

![image](https://user-images.githubusercontent.com/43693241/78127698-3772ec80-7447-11ea-93e1-05af6583dc61.png)

There are no paging parameters when getting the members under the project. 

/assign @leoendless

**Comment by leoendless** [comment]
could you patch you request information ?

**Comment by shaowenchen** [comment]
I can't provide more details of the request . ╭(╯^╰)╮

I get all users under the project when changing paging parameters . But，the page does not display a paging button.

**Comment by shaowenchen** [comment]
outdated
/close
