### ISSUE TITLE
Remove statistics on the number of pods in the fedProject overview

### ISSUE THREAD

**Issue by harrisonliu5** [kubesphere/console#2140]
**Describe the bug**

It is not easy to display the pods' resources of the FedProject separately, so it is recommended to remove the statistics of the pods

For UI issues please also add a screenshot that shows the issue.

![image](https://user-images.githubusercontent.com/17872673/128283952-201b68ea-311c-4d99-824b-84d8b09e48c1.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.1.1

/assign @kubesphere/sig-console

/priority low

**Comment by liuyp2018** [comment]
This issue has been fixed in released v3.2.0, please check and close it.
