### ISSUE TITLE
Some places where you can't deselect all.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#2141]
**Versions used(KubeSphere/Kubernetes)**
KubeSphere: `v3.1.1`

**To Reproduce**
![image](https://user-images.githubusercontent.com/68640256/128308576-7d13aae4-c7d6-4586-ad08-e0e93e389636.png)
![image](https://user-images.githubusercontent.com/68640256/128308577-950d6124-2891-437c-82c9-8a44d6bb4ed2.png)
![image](https://user-images.githubusercontent.com/68640256/128308622-8b2fcf27-0487-487b-9a7f-519973cc4b66.png)
![image](https://user-images.githubusercontent.com/68640256/128308699-c2975a67-913c-4ae3-aa1a-8bc31e011db5.png)

**Expected behavior**
Double click the select all button can deselect all

/kind bug
/assign @kubesphere/sig-console
/priority low

**Comment by harrisonliu5** [comment]
These are the default data in the platform, may be  can't delete.

**Comment by wenxin-01** [comment]
> These are the default data in the platform, may be can't delete. @wenxin-01

Yes, it's reasonable that they can't delete. I mean, clicking the select all button again can deselect the selected content. @harrisonliu5

**Comment by wenxin-01** [comment]
issue fixed `ks-console nightly-20210929`
