### ISSUE TITLE
Support editing node affinity on console after creating a deployment

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/console#2164]
**Describe the bug**
The runtime Deployment in the workload does not support the affinity modification Settings for the UI, which are available when Deployment is created
![image](https://user-images.githubusercontent.com/65068467/129695550-ff4fdd18-091e-4c27-a112-153a56c7d9be.png)
![image](https://user-images.githubusercontent.com/65068467/129695641-0323fe3c-4e5d-44cb-956f-1e780f19aa46.png)

**Comment by yuswift** [comment]
/retitle Support editing node affinity on console after creating a deployment

**Comment by yuswift** [comment]
@harrisonliu5 Could you provide some suggestions to help the new contributors? (e.g. the code dir that should be updated)

**Comment by mangoGoForward** [comment]
I noticed that this issue has solved, please see the screenshot below:

![image](https://user-images.githubusercontent.com/35127166/143415377-164b71ae-f191-4d01-bccb-b069232d338e.png)

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/172290028-bd471a16-db35-428f-b8a0-c0232b6180f8.png)

version used 
kubesphere: v3.3.0-rc.1
