### ISSUE TITLE
App upgrade

### ISSUE THREAD

**Issue by zheng1** [kubesphere/console#218]
**What would you like to be added**:
App upgrade

**Why is this needed**:
https://kubesphere.com.cn/forum/d/1130

/assign @leoendless 
/kind feature

**Comment by zheng1** [comment]
https://github.com/kubesphere/kubesphere/issues/1945

**Comment by zheng1** [comment]
https://github.com/kubesphere/kubesphere/issues/1883

**Comment by leoendless** [comment]
@pengcong06 is the upgrade api ready ?

**Comment by pengcong06** [comment]
> @pengcong06 is the upgrading api ready ?

sorry,it's late.
post /clusters/{cluster}/namespaces/{namespace}/applications/{application}
params can reference CreateApplication( just replace AppId with ClusterId)

**Comment by pengcong06** [comment]
About Application in multi clusters:
Steps:
1.ListRuntimes, to chosse cluster(runtime_id)
2.ListNamespaces,to chosse namespace in the cluster
3.use runtime_id and namespace to CreateApplication(runtime_id,namespace)

1,2 @wansir can help you get it.and 3 is just like before.
all the application apis' uri have prefixed with "/clusters/{cluster}"

Tips:
For the meaning of runtime has changed, the runtime data store in current mysql is invalided.it may affect the result of api,I will make some fake but useful data soon.
