### ISSUE TITLE
Change pvc access modes to list

### ISSUE THREAD

**Issue by f10atin9** [kubesphere/console#2183]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
Current the access mode is a single selection, but it should be a string array in fact.
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/36705019/130403870-cd3c4c25-4384-41eb-a124-4686e0f8ef91.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)

https://github.com/kubesphere/kubesphere/issues/4089

**Comment by live77** [comment]
Hi, 

> /good-first-issue

Hi, I would like to resolve this issue, may I start working on it ?
I would like to make sure that this issue is just about a front-end feature, nothing related to the modify the backends(the ks-api stuffs).

**Comment by weili520** [comment]
> Hi,
> 
> > /good-first-issue
> 
> Hi, I would like to resolve this issue, may I start working on it ?
> I would like to make sure that this issue is just about a front-end feature, nothing related to the modify the backends(the ks-api stuffs).
yes, nothing related to backend, it just a ui issue.

**Comment by live77** [comment]
> > Hi,
> > > /good-first-issue
> > 
> > 
> > Hi, I would like to resolve this issue, may I start working on it ?
> > I would like to make sure that this issue is just about a front-end feature, nothing related to the modify the backends(the ks-api stuffs).
> 
> Hi live77, it just a front-end issue, nothing related to backend api.

cool. thanks .

**Comment by f10atin9** [comment]
> > > Hi,
> > > > /good-first-issue
> > > 
> > > 
> > > Hi, I would like to resolve this issue, may I start working on it ?
> > > I would like to make sure that this issue is just about a front-end feature, nothing related to the modify the backends(the ks-api stuffs).
> > 
> > 
> > Hi live77, it just a front-end issue, nothing related to backend api.
> 
> cool. thanks .

Looking forward to your contribution! 😃

**Comment by live77** [comment]
> > > > Hi,
> > > > > /good-first-issue
> > > > 
> > > > 
> > > > Hi, I would like to resolve this issue, may I start working on it ?
> > > > I would like to make sure that this issue is just about a front-end feature, nothing related to the modify the backends(the ks-api stuffs).
> > > 
> > > 
> > > Hi live77, it just a front-end issue, nothing related to backend api.
> > 
> > 
> > cool. thanks .
> 
> Looking forward to your contribution! 😃

😄, I just submitted a pull request, wish it would help.
