### ISSUE TITLE
Node module in Cluster Status should be removed

### ISSUE THREAD

**Issue by serenashe** [kubesphere/console#2201]
**Describe the bug**
As the node status is already shown on the left of **Component Status**, an additional **Node** module seems to be redundant. Besides, a node is not a  component. The node module in **Component Status** should be removed.

![image](https://user-images.githubusercontent.com/75245999/131318998-eb092d85-4a94-4ad6-8fad-99c954924ff7.png)

**To Reproduce**
1. Log in to the KubeSphere console.
2. Click **Platform** on the upper left corner,
3. Go to **Monitoring & Alerting** > **Cluster Status** > **Overview**.
4. You can see that the **Node** module is in **Component Status**.

**Expected behavior**
The node module should be removed.

/assign @VioZhang Please take a look, thanks:)

**Comment by VioZhang** [comment]
@weili520 There is a better solution https://github.com/kubesphere/console/issues/2247
