### ISSUE TITLE
Content will be cleared after clicking confirm button on shell modal

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#2217]
**Describe the bug**

Content will be cleared after clicking confirm button on shell modal.

![78f5d35d7333e423335aaba71bbbb27](https://user-images.githubusercontent.com/16865714/131957729-2c3dde3a-8425-49fc-b5a9-a5892c0daf0d.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: latest
Kubernetes: (If KubeSphere installer used, you can skip this)

**To Reproduce**
1. Create a normal Pipeline
2. Edit Pipeline
3. Add a stage and add a shell step inside the step
4. Input script text into the shell modal and click confirm button
5. Reopen the shell modal and click confirm button
6. See error

**Expected behavior**
When I click the confirm button in shell modal, the content won't be cleared by mistake.

/area devops
/priority high

**Comment by harrisonliu5** [comment]
https://user-images.githubusercontent.com/17872673/132619800-002e56f4-868f-4af7-8527-ab68ad2aaef7.mp4

please try it later

**Comment by JohnNiang** [comment]
I confirmed that ks-console with docker image id [docker.io/kubespheredev/ks-console@sha256:25c78f80b7a972ed547811d1a87b981d373278b387de09b39704d1abc6f75b97](https://hub.docker.com/layers/kubespheredev/ks-console/master/images/sha256-25c78f80b7a972ed547811d1a87b981d373278b387de09b39704d1abc6f75b97?context=explore) worked well.

/close
