### ISSUE TITLE
登录cookie在什么地方修改？

### ISSUE THREAD

**Issue by xinnicai** [kubesphere/console#2240]
请求中显示登录通过'/login'登录
![image](https://user-images.githubusercontent.com/30997380/132470552-abb1ce80-2b5e-46c6-8b4d-e1108b4658cb.png)
找到路由
![image](https://user-images.githubusercontent.com/30997380/132470665-c9cbccce-864d-4cdd-b6ce-f31aeed93a0e.png)

![image](https://user-images.githubusercontent.com/30997380/132470803-7fac42ed-d980-499a-93c2-9e996c3258b1.png)

调试使用的是vscode
![image](https://user-images.githubusercontent.com/30997380/132470954-d191b200-fc16-41d9-ae37-48af066b748b.png)

或者把登录的流程解释一下？

**Comment by weili520** [comment]
1. use vscode build-in function to debug as fllows.
![截屏2021-09-09 09 35 21](https://user-images.githubusercontent.com/33231138/132607740-2fb40213-a2fc-478f-befa-9804394db768.png)

2. add a launch.json to start debug.
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "command": "yarn start",
      "name": "Run npm start",
      "request": "launch",
      "type": "node-terminal"
    }
  ]
}
```

**Comment by xinnicai** [comment]
how to set node version?(node 10.10.0)

**Comment by weili520** [comment]
> how to set node version?(node 10.10.0)
install [nvm](https://www.google.com.hk/search?q=+nvm+mac&newwindow=1&ei=17w5YdF_mtH5BsCyksAE&oq=+nvm+mac&gs_lcp=Cgdnd3Mtd2l6EAMyBAgAEEMyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgQIABAKMgQIABAKOgcIABBHELADOgcIABCABBAMSgQIQRgAULnTAVj76AFg8O8BaAVwAngAgAHxAYgB5wqSAQUwLjMuNJgBAKABAbABAMgBCMABAQ&sclient=gws-wiz&ved=0ahUKEwiRx9-NtPHyAhWaaN4KHUCZBEgQ4dUDCA4&uact=5) to manage node version, or install a new version.

**Comment by xinnicai** [comment]
nono ，i use terminal command nvm use node 10.10.0 and yarn start,is ok
but in launch is useless

**Comment by weili520** [comment]
how about switch node version to 12.18+ ?

**Comment by weili520** [comment]
how about switching to version 12.18+ ? 
![截屏2021-09-09 09 35 21](https://user-images.githubusercontent.com/33231138/132653459-74283e35-55c0-4fad-ad78-a24cc3cc70e4.png)

**Comment by xinnicai** [comment]
the computer reboot is ok，thankyou
