### ISSUE TITLE
It is no need to show "Node" at the Component Status and there is no "DevOps" component when we have installed it.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#2247]
![image](https://user-images.githubusercontent.com/41519383/133015678-517cf7e0-94d7-43b3-aa32-32f6beeba410.png)

**Comment by VioZhang** [comment]
The drawing design:
https://www.figma.com/file/8Le5pz18Rtf1UhOha29uvp/Other?node-id=1%3A54383

**Comment by liuyp2018** [comment]
This issue has been fixed in released v3.2.0 and can be closed.
