### ISSUE TITLE
search string becomes [object object] in ks-console

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/console#2250]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
in ks-console, the search keyword `contract` becomes `[object object]` in search result.

![image](https://user-images.githubusercontent.com/70880165/133220494-018ac958-0714-4da5-9e48-ced699507193.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**

**Expected behavior**

**Comment by weili520** [comment]
![截屏2021-11-24 14 07 12](https://user-images.githubusercontent.com/33231138/143184014-2f546fc3-54ff-4764-ab68-f69e1ddf339b.png)

**Comment by liuyp2018** [comment]
fixed
/close
