### ISSUE TITLE
[License] Why using AGPL-3.0 as the license of this project

### ISSUE THREAD

**Issue by imjoey** [kubesphere/console#226]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

Hi folks, thank you very much for this great work. I was very curious about the license of this console project. May I have the reason why you guys are choosing `AGPL-3.0` instead of `Apache-2.0` the same as the other projects in KubeSphere community?

Any feedback are much appreciated. Thanks.

**Comment by rayzhou2017** [comment]
1. You can use it including the console part without modification for free.
2. If you make change on the console project, then follow the license. Either make your change public, or contact us for license agreement.
3. Make your change public is good for other. It is recommended to contribute to the upstream.
4. We want to make this project stay healthy as long as possible. Without financial support, it hardly goes further. So if you want to make money from this project but don't want to make your change public, then share your income with us for the project continuing evolving. That is reasonable, isn't it?
5. Basically, people won't open source dashboard, especially such nice, thoroughly designed one. But we open it. 
6. If you do not like all reasons above, then you could develop your own dashboard with the backend of KubeSphere which is Apache 2.0.

**Comment by imjoey** [comment]
@rayzhou2017 many thanks for your clear explanations.

I'm an open source fan, so we're willing to make as much contributions as we could back to upstream community. While to be honest, it's not easy to make 100% code public. AFAIK, the dashboards in rancher and openshift(okd) community are with a commercial friendly license.

Anyway, much appreciated again for the reply. I've got my answer and will close this issue.
