### ISSUE TITLE
No related resource is returned in the workload deletion dialog box.

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#2273]
**Describe the bug**
No related resource is returned in the workload deletion dialog box.
![image](https://user-images.githubusercontent.com/76198553/134276549-080db69a-eeb7-4835-a611-c2f7e14fb405.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: current console/master

**Expected behavior**
![image](https://user-images.githubusercontent.com/76198553/134276694-6838144d-4d96-4047-9374-6e4feda5e6bb.png)

/assign @harrisonliu5

**Comment by liuyp2018** [comment]
this issue has been fixed and can be closed

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
