### ISSUE TITLE
When creating a workload setting container group, do not select the GPU type. Clicking to confirm is invalid

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2274]
**Describe the bug**
1. Click Create Workload, set a name, click Next
2. set image,click the √，The page is not responding
![image](https://user-images.githubusercontent.com/88183150/134281303-644d5b6b-ae7e-4c9c-88bf-44cf860c863d.png)

Versions Used
KubeSphere: v3.2.0-alpha.0

/kind bug
/assign @harrisonliu5 
priority medium
/milestone v3.2

**Comment by weili520** [comment]
##2272
