### ISSUE TITLE
The notification needs to be optimized on the notification Settings page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2284]
**Describe the bug**
The prompts need to be optimized
![image](https://user-images.githubusercontent.com/36271543/134451872-6c443a0c-e1bf-4de0-ad53-abae4fdde786.png)

![image](https://user-images.githubusercontent.com/36271543/134452089-173a3ebd-1953-4bf2-bcce-8b073dc7a95c.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: ks3.2 alpha
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @xuliwenwenwen
/priority low

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
