### ISSUE TITLE
DevOps information display error

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#2286]
**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.2.0-alpha.0`

**To Reproduce**
![image](https://user-images.githubusercontent.com/68640256/134460058-3d29dc0f-f19e-4b04-9319-ab08718e199c.png)

![image](https://user-images.githubusercontent.com/68640256/134466805-b8903fb8-2747-4759-94fe-4f0fea19d875.png)

![image](https://user-images.githubusercontent.com/68640256/134469333-0ef9b164-41f4-4d5a-8bd5-fddb350b8bc4.png)

![image](https://user-images.githubusercontent.com/68640256/134887109-d1dd125a-a813-4a7b-b519-afd20eb3571e.png)

/kind bug
/assign @kubesphere/sig-console
/priority medium

**Comment by Patrick-LuoYu** [comment]
This issue is a known issue and will be fixed in later PRs. UI text optimization is still in progress.

**Comment by wenxin-01** [comment]
Issue fixed in `v3.2.1`
