### ISSUE TITLE
Three cancel buttons on Project gateway editing page

### ISSUE THREAD

**Issue by zryfish** [kubesphere/console#2292]
**Describe the bug**
There are three duplicated `cancel` buttons on gateway editing page.

![截屏2021-09-23 17 51 39](https://user-images.githubusercontent.com/3326354/134487629-01ab4827-d2a3-4bb1-b83f-d35344389ca7.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0-alpha.0
Kubernetes: v1.21.5

**Environment**
How many nodes and their hardware configuration: 

/kind bug

**Comment by liuyp2018** [comment]
this issue has been fixed and can be closed
