### ISSUE TITLE
Still can enable project gateway even when cluster gateway is enabled

### ISSUE THREAD

**Issue by zryfish** [kubesphere/console#2293]
**Describe the bug**
 When there is a cluster gateway, shouldn't allow user to enable project gateway. 
![截屏2021-09-23 18 03 12](https://user-images.githubusercontent.com/3326354/134489106-983eb2f6-4e2c-45be-9c0d-428dc0588093.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0-alpha.0
Kubernetes: v1.21.5

/kind bug

**Comment by liuyp2018** [comment]
this issue has been fixed ,Please close it if you confirmed that
