### ISSUE TITLE
Value not saved after notification filter condition is saved

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2299]
**Describe the bug**
Value not saved after notification filter condition is saved
![image](https://user-images.githubusercontent.com/36271543/134607129-28b45a2f-d2a7-4168-8864-240cd99176da.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 alpha.0
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @xuliwenwenwen
/priority Medium

**Comment by xuliwenwenwen** [comment]
Support inputting multiple values, need enter keypress appends items to the list, I will add usage tips later.

**Comment by liuyp2018** [comment]
fixed
