### ISSUE TITLE
Multi-cluster project overview Chinese display error

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2300]
**Describe the bug**
1. Click for overview,there are untranslated parts

![image](https://user-images.githubusercontent.com/88183150/134609652-eb825567-72b6-4695-bd63-fc0ed14d6f02.png)

Versions used@harrisonliu5 ubeSphere/Kubernetes)
KubeSphere:v3.2.0-alpha.0

/kind bug
/@kubesphere/sig-console
priority medium

**Comment by Patrick-LuoYu** [comment]
This issue has been fixed. UI text optimization is still in progress.
