### ISSUE TITLE
Storage type field value display problem

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2309]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/134639705-4c2fb023-9e3c-485b-a428-307e11a9930d.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2 alpha.0
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @harrisonliu5 
/priority Low

**Comment by weili520** [comment]
![截屏2021-11-02 15 46 53](https://user-images.githubusercontent.com/33231138/139806073-d35a9746-5055-4870-a7a5-f154e240534f.png)

**Comment by liuyp2018** [comment]
not fixed in released v3.2.0
![image](https://user-images.githubusercontent.com/36271543/142361394-7df0756b-7d00-402a-8730-fa9975931fe7.png)

**Comment by weili520** [comment]
![截屏2021-11-24 14 10 07](https://user-images.githubusercontent.com/33231138/143184358-62db311c-12e7-4f1f-94ff-c90981e88f0b.png)

**Comment by liuyp2018** [comment]
fixed
