### ISSUE TITLE
Traffic data not shown on the side bar and Grayscale Release Job

### ISSUE THREAD

**Issue by RolandMa1986** [kubesphere/console#2316]
**Describe the bug**
When upgrading kiali to v1.38, The traffic data no longer shows on the following page.

![20210926141511](https://user-images.githubusercontent.com/1720333/134795993-4c2a93d4-ac4f-43fc-82f1-ec911995de03.png)

![20210926141549](https://user-images.githubusercontent.com/1720333/134795991-5e866737-5941-4a64-bafb-1b1a1232af2d.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2 alpha0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
kiali v1.38
Istio v1.11.1

**To Reproduce**

**Expected behavior**
Traffic data should display on those 2 pages

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
