### ISSUE TITLE
The deleted PV still exists in the list

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2317]
**Describe the bug**
In the pv list, the deleted data still exists in the list. the delete data exists in the list unless manually refresh the list.
![image](https://user-images.githubusercontent.com/36271543/134796801-abeae042-1ead-499d-967e-6da7d4ad6ed9.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 alpha.0
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @harrisonliu5
/priority Medium
/Milestone v3.2

**Comment by liuyp2018** [comment]
The problem has not been fixed
/remove-kind  need-to-verify

**Comment by jioce** [comment]
issue is fixed in v3.3.0-rc.1
