### ISSUE TITLE
FederatedDeployment volume name is displayed incorrectly

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2345]
**Describe the bug**
FederatedDeployment volume name is displayed incorrectly

<img width="958" alt="存储卷名称错误1" src="https://user-images.githubusercontent.com/88183150/135063455-6e1ed872-f738-4713-a26c-fce258dfeca0.png">

<img width="961" alt="存储卷名称错误2" src="https://user-images.githubusercontent.com/88183150/135063465-edf25732-0b10-4b23-a15f-7756a0e1cee3.png">

**Versions used(KubeSphere/K
KubeSphere: nightly-20210927

/kind bug
/@kubesphere/sig-console
/priority medium

**Comment by weili520** [comment]
![截屏2021-11-24 14 41 27](https://user-images.githubusercontent.com/33231138/143187942-3d04f345-6d43-4a69-b098-ef3e2a43b506.png)

![截屏2021-11-24 14 41 41](https://user-images.githubusercontent.com/33231138/143187955-26c87f51-4a53-4653-a5f5-d332e705d008.png)

**Comment by jioce** [comment]
issue fixed
