### ISSUE TITLE
Edit federated service tag selector error

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2357]
**Describe the bug**
1. click more,click Edit Config Template
2. delete the key, click save,click to confirm
3. The update is successful, check that the resource status has not changed

![image](https://user-images.githubusercontent.com/88183150/135220190-ca1f00ee-1ed4-4f94-9be5-944baf958e2b.png)

![image](https://user-images.githubusercontent.com/88183150/135221417-2af39457-f79e-42b0-a04a-5c7465e771c4.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: nightly-20210927

/kind bug
/@kubesphere/sig-console
/priority low

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/155270125-6dc19171-4cc6-4c5d-b59a-ebf4c7ae1dd1.png)

The version of console is 3.2.1, which has no bug. @jioce

**Comment by jioce** [comment]
issue is fixed
