### ISSUE TITLE
Pipeline edit information re-select change account option stealth

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/console#2360]
**General remarks**
Line edit information re-select change account options stealth, need to move the mouse to the blank will be displayed and the page is too wide need to drag past
![image](https://user-images.githubusercontent.com/65068467/135224273-1fd7d208-4b9f-40fa-81ee-c099c5b849d3.png)
![image](https://user-images.githubusercontent.com/65068467/135224435-0989f64c-4e76-4f18-9411-d3fb1f1ad827.png)

**Comment by LinuxSuRen** [comment]
duplicated with https://github.com/kubesphere/console/issues/1781
/close
