### ISSUE TITLE
Federated routing rules display error

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2365]
**Describe the bug**
1. Create federated routing，set rules
2. Click on the route name to enter the details interface ，check the route information, and the routing rules are displayed incorrectly

![image](https://user-images.githubusercontent.com/88183150/135236934-740611f1-5771-4aa5-9a33-425c4da46b8c.png)

![image](https://user-images.githubusercontent.com/88183150/135237051-ee21b4e5-ea9e-47c6-8e24-da74484bda48.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: nightly-20210927

/kind bug
/@kubesphere/sig-console
/priority medium

**Comment by jioce** [comment]
**Describe the bug**
  Deleting routing rules does not take effect

![image](https://user-images.githubusercontent.com/88183150/137057090-f66b6036-f99e-4164-934b-d4b9b0a6eb19.png)

![image](https://user-images.githubusercontent.com/88183150/137057169-2565b494-c5e6-4efb-93a6-bbb15dbec6f4.png)

**Comment by RolandMa1986** [comment]
/unassign @RolandMa1986 
I can't reproduce this issue with v3.2.0-alpha.1. @jioce

**Comment by jioce** [comment]
**Describe the bug**
     route requires at least one routing rule,After deleting all the routing rules, the confirmation button cannot be clicked

![image](https://user-images.githubusercontent.com/88183150/138019736-bb3f832a-4702-4759-8385-8f6c300e0982.png)


![image](https://user-images.githubusercontent.com/88183150/138020078-39fbe622-22d2-403a-892c-1668b036b572.png)

**Comment by jioce** [comment]
issue fiixed  
version used:
ks-console:nightly-20211116
