### ISSUE TITLE
KubeSphere Console i18n Support

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/console#2380]
KubeSphere console has supported four languages in [locales](https://github.com/kubesphere/console/tree/master/locales), including English, Simplified Chinese, Traditional Chinese, Spanish. As the UI copywriting has huge updates in English and Simplified Chinese from v3.2.0, the existing version of **Traditional Chinese** and **Spanish** are supposed to be updated accordingly. 

We are also looking for contributors who are willing to help us to support more languages for the KubeSphere console, such as **Turkish, Japanese, Arabic, French, Deutsch, Korean**, and more. If you are interested in helping our community to support one of these languages, feel free to leave your comments below.

- [ ] Arabic
- [ ] Deutsch
- [ ] French 
- [ ] #2381
- [ ] Japanese
- [ ] Korean
- [ ] Turkish

**Comment by himanshu007-creator** [comment]
Hi , i would like to work on <code>Hindi</code> translations

**Comment by FeynmanZhou** [comment]
It's duplicated with https://github.com/kubesphere/console/issues/2934
