### ISSUE TITLE
unable to select multicluster pvc's project

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/console#2387]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
See the screenshots.

pvc1 is in demo-test project, but this project is not shown in the dropdown list.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: ks 3.2 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
https://console.kubesphere.io/clusters/host/volumes/Volumes

![Screen Shot 2021-10-08 at 11 24 52 AM](https://user-images.githubusercontent.com/70880165/136493600-0fb4de8e-6d8f-4d00-b925-017302d8e576.png)
![Screen Shot 2021-10-08 at 11 24 58 AM](https://user-images.githubusercontent.com/70880165/136493605-456423e4-7c0e-473d-80a2-70a3790b6662.png)
![Screen Shot 2021-10-08 at 11 25 07 AM](https://user-images.githubusercontent.com/70880165/136493608-bd4e3847-17dd-42fd-a437-3d3425e2bf36.png)

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
