### ISSUE TITLE
Failed to fetch node list 

### ISSUE THREAD

**Issue by wansir** [kubesphere/console#2388]
**Describe the bug**

![image](https://user-images.githubusercontent.com/8263040/136494186-e2c9a41b-01e1-48ee-823c-76984775967e.png)

The correct API path should be `/kapis/resources.kubesphere.io/v1alpha3/nodes`

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0-alpha.1

**Comment by harrisonliu5** [comment]
https://github.com/kubesphere/console/issues/2335

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
