### ISSUE TITLE
incorrect link for multi-cluster pvc

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/console#2389]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
for a multi-cluster pvc, when I click a cluster name (`shire` in this case), it jumps to `https://console.kubesphere.io/clusters/shire/projects/demo-test/persistentvolumeclaims/pvc1` ,  I think this is wrong, it should jump to `/volumes/pvc1`, not `/persistentvolumeclaims/pvc1`.

![Screen Shot 2021-10-08 at 11 24 58 AM](https://user-images.githubusercontent.com/70880165/136494638-70ac5df5-e768-4afb-a80e-5ac2fa6ce742.png)
![Screen Shot 2021-10-08 at 11 35 44 AM](https://user-images.githubusercontent.com/70880165/136494644-ba7c243c-0ea8-47b9-a057-6e03186ff53a.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.2 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
https://console.kubesphere.io/clusters/shire/projects/demo-test/volumes/pvc1/resource-status

/milestone v3.2

**Comment by liuyp2018** [comment]
In released v3.2, this problem does not exist, please confirm and close it
