### ISSUE TITLE
the route address is incorrect 

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2391]
**Describe the bug**
**steps**
1. enter the cluster configuration page, creating Cluster Gateway
2. Enter the project manage page and create an application
3. Creating an Application Route
4. View the address of the application route

**the problem**
the route address is incorrect 

![image](https://user-images.githubusercontent.com/36271543/136505804-b6a42914-c403-46cc-84f0-88f84519935c.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @RolandMa1986 
/kind bug
/priority high

**Comment by RolandMa1986** [comment]
@liuyp2018 For Auto Generate Domain Name, the Router must be created when the router is ready. So can you confirm that the Gateway was ready when you creating the Router?

**Comment by liuyp2018** [comment]
fixed
