### ISSUE TITLE
Improve the Service Topology Details Layout for a Specific Service

### ISSUE THREAD

**Issue by Felixnoo** [kubesphere/console#2392]
**What would you like to be added**:

Currently, when clicking a specific Service listed on the **Service Topology** page, a details form will be displayed on the right as shown in the following screenshot.
![en](https://user-images.githubusercontent.com/75110798/136509824-4448bf44-17f6-4b88-804d-3ab133faa4af.png)

The information shown on that form is not organized well and it is also difficult to make Chinese localization.

Please consider improving the layout here.

**Why is this needed**:
For better user experience.

**Comment by XiaohuiSept** [comment]
Drawing design as follow: 
https://www.figma.com/file/G6LDkjRMGtHq1NGkr5bIyI/Design-Requirements-Pool?node-id=78%3A146477
/cc @harrisonliu5

**Comment by Felixnoo** [comment]
Layout improved.

**Comment by jioce** [comment]
![image](https://user-images.githubusercontent.com/88183150/170238226-561d32c6-19e0-466f-ad61-ecdd0ba04daf.png)

version used
v3.3.0-rc.0
