### ISSUE TITLE
DevOps 删除的参数，依然显示在页面上

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#24]
版本：2.1
模块：DevOps
复现方法：修改流水线参数，删除一部分，增加一部分
相关截图：

![image](https://user-images.githubusercontent.com/43693241/70111878-9b022e80-168e-11ea-9ad6-3bfbb0edccc4.png)

/assign @leoendless 
/area devops

**Comment by minghaoye** [comment]
修改jenkinsfile 里的 parameters属性后重新返回的pipeline-detail里好像没有更新，需要手动触发一次运行后才可以 @runzexia

**Comment by shaowenchen** [comment]
在 staging 环境，已经触发很多次了。

**Comment by minghaoye** [comment]
触发后要刷新一下页面，我修复一下
