### ISSUE TITLE
Unable to edit or take snapshot for multi-cluster PVC

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/console#2405]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
Compare a multi-cluster PVC with a normal PVC, the multi-cluster PVC doesn't have `编辑信息`  `更多操作` buttons. So how can I edit this pvc or take snapshot for it?

![image](https://user-images.githubusercontent.com/70880165/136639463-a43fa4a5-466b-474a-9224-d2b49cdef238.png)

![image](https://user-images.githubusercontent.com/70880165/136639484-d30b21e9-bba5-48c6-be3e-b1f4d23c319d.png)

![image](https://user-images.githubusercontent.com/70880165/136639555-ca9bb46b-1845-4878-8a07-4875899e23d0.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: ks3.2 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
https://console.kubesphere.io

/priority high
/milestone v3.2

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.0`
/close
