### ISSUE TITLE
prompt optimization for gateway

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2415]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/136646570-144d1216-0efb-4419-a2ad-4803f7d9bff1.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/area console
/kind bug
/priority low

**Comment by liuyp2018** [comment]
The problem has not been fixed
<img width="914" alt="d4052c8097506c690316ba6c8e4572d" src="https://user-images.githubusercontent.com/36271543/138385665-02150390-a8d4-4a2f-bc05-33f23fde584b.png">

/remove-kind need-to-verify

**Comment by wenxin-01** [comment]
Issue fixed in `v3.2.1`
![image](https://user-images.githubusercontent.com/68640256/172307497-14723c2b-a79e-4e44-a48a-31119ef18f1f.png)
