### ISSUE TITLE
The drop - down box cannot show all items

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2429]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/136753837-d7460e36-566b-4b9d-a9af-ca01d05dca28.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @harrisonliu5
/priority Medium
/Milestone v3.2

**Comment by weili520** [comment]
I think this problem has been resolved.

https://user-images.githubusercontent.com/33231138/146142482-a2245871-74b5-4cab-9adb-1e7e99732ceb.mov

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172316349-5d316666-5279-4557-a492-b9591319db67.png)

![image](https://user-images.githubusercontent.com/88183150/172316443-87ac5b70-405c-4bc7-9918-0c1f618762de.png)

version used
kubesphere: v3.3.0-rc.1
