### ISSUE TITLE
After the verification fails, users cannot be allowed to proceed to the next step

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2431]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/136767787-909b5454-7608-4e1a-ad06-6c3f261e5db2.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2 alpha.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5
/area console
/kind bug
/priority Low

**Comment by weili520** [comment]
> /assign

Pass the form's error control permission to it.

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172318836-5add27db-e76b-4806-9742-33045bba4402.png)

![image](https://user-images.githubusercontent.com/88183150/172319423-72c7e2a1-3899-446e-a972-f15c69e53133.png)

version used
kubesphere: v3.3.0-rc.1
