### ISSUE TITLE
UI display error on log search page 

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2464]
**Describe the bug**
UI display error 
![image](https://user-images.githubusercontent.com/36271543/137276261-e63c3db6-f262-4a35-9bfa-7124aef579e1.png)

![image](https://user-images.githubusercontent.com/36271543/137276395-ed0d6fe8-5ebe-470c-a71f-497da6663299.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 nightly-20211013
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/kind bug
/priority Medium

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/137297999-247009d3-3562-4b49-9753-b967ec59e8eb.png)

**Comment by weili520** [comment]
![截屏2021-11-24 14 07 12](https://user-images.githubusercontent.com/33231138/143184120-1c6e75e8-7bc1-4339-8522-80cae49cba4d.png)

**Comment by liuyp2018** [comment]
fixed
