### ISSUE TITLE
Input box input problem

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2466]
**Describe the bug**

https://user-images.githubusercontent.com/36271543/137294195-2d7ff212-c02a-4326-9be3-766ef9d9c697.mp4

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 nightly-20211013
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/kind bug
/priority Medium

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/172321453-1bf1e896-ce4d-4fa2-a48f-d99a93f00f2f.png)

version used
kubesphere: v3.3.0-rc.1
