### ISSUE TITLE
Modify the mouse display mode

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2469]
**Describe the bug**

The log cannot be clicked. need to change the display mode

https://user-images.githubusercontent.com/36271543/137294572-165ef1da-5200-4150-b45e-3b3489f8872c.mp4

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 nightly-20211013
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/kind bug
/priority Low

**Comment by wenxin-01** [comment]
Issue fixed in `v3.2.1`
