### ISSUE TITLE
When querying logs, the time range is not set, and error occurs on the console.

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2470]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/137295528-dfb0316c-2897-4dca-9f32-85890aefe58d.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 nightly-20211013
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/kind bug
/priority Low

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc1`. but has other issue.https://github.com/kubesphere/console/issues/3350
