### ISSUE TITLE
The multi-cluster project is not displayed in the user project list of the host cluster

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2483]
**Describe the bug**
The multi-cluster project is not displayed in the user project list of the host cluster
![image](https://user-images.githubusercontent.com/36271543/137666239-bef7d285-7fc6-431f-b86c-ca7ac40828b3.png)
![image](https://user-images.githubusercontent.com/36271543/137666280-7b240562-75b7-4ab7-b89a-9a736b9cb43b.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: nightly-20211016
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5
/area console
/kind bug
/priority Medium

**Comment by liuyp2018** [comment]
The problem is still exists in v3.2.0-rc.1. please take a look at this.
/remove-kind need-to-verify

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172306761-38b6b110-0a7d-4262-9f60-7d36c2095b51.png)
