### ISSUE TITLE
The GPU quota is not displayed on the deployment page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2485]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/137683409-ad9a9446-7aeb-40a1-9c69-09bce074e086.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: nightly-20211016
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @weili520 
/area console
/kind bug
/priority Low

**Comment by weili520** [comment]
It has beed resolved.
version: v3.2.1
![截屏2022-01-06 18 12 27](https://user-images.githubusercontent.com/33231138/148366924-b393a66b-0ef0-42b7-ad8c-d02e63104a0e.png)

**Comment by wenxin-01** [comment]
Issue fixed in `v3.2.1`
