### ISSUE TITLE
Modules on container log details page needs to be improved

### ISSUE THREAD

**Issue by serenashe** [kubesphere/console#2490]
/assign @VioZhang 
Hello Vio, I have some enhancement advice for the designers.

1. Click the toolbox icon on the lower-right of the KubeSphere console and select **Log Search**.
2. Go to the details page of a log.

As you can see from the following screenshot: 
1. The first line of the **Refresh Rate** column was partly visible, the width should be wider.
2. I think the designer should choose a lighter color of the **Refresh Rate** drop-down list icon to create contrast because it is almost invisible for users.
3. You guys can add a tip bubble for the start/pause icon on the left of the **Refresh Rate** column to be in accordance with the design of previous pages. But this is optional and is totally up to you guys.

Please take a look, thanks :)

![image](https://user-images.githubusercontent.com/75245999/137853312-cfbca6c9-8ba3-43c4-8426-29aaa8857cad.png)

**Comment by XiaohuiSept** [comment]
Drawing design as follow:
https://www.figma.com/file/G6LDkjRMGtHq1NGkr5bIyI/Design-Requirements-Pool?node-id=2%3A603
/cc @harrisonliu5
