### ISSUE TITLE
There should not be a "v" in front of the version.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#2513]
There should not be a "v" in front of the version.

![image](https://user-images.githubusercontent.com/41519383/138204263-cfdf1333-b307-4a7c-8adc-1231a6ce2d9b.png)

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`
![image](https://user-images.githubusercontent.com/68640256/172288334-75dc3578-3d18-4599-b2b8-dd3fc36ee1e6.png)
