### ISSUE TITLE
EKS lack hint annotations

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2514]
**Describe the bug**
![image](https://user-images.githubusercontent.com/36271543/138207652-2733b5a7-1c56-47dd-a087-2ef310de9fcf.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0-rc.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5
/area console
/kind bug
/priority Medium

**Comment by harrisonliu5** [comment]
Amazon EKS doesn't have the init annotations.

**Comment by liuyp2018** [comment]
fixed
