### ISSUE TITLE
Edit application template page, text display issues

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2516]
**Describe the bug**
![image](https://user-images.githubusercontent.com/36271543/138223844-26c517fe-85b5-444f-9326-031fba51fb99.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0-rc.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5
/area console
/kind bug
/priority Medium

**Comment by weili520** [comment]
![截屏2022-01-06 18 07 19](https://user-images.githubusercontent.com/33231138/148366330-2109b2d3-0659-4635-b77d-c2090b035e8f.png)
version: v3.2.1

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172289126-6b9cb5f9-e834-425c-a9c6-4638c8c86b9f.png)
