### ISSUE TITLE
Can't close the About page

### ISSUE THREAD

**Issue by hchenc** [kubesphere/console#2521]
**Describe the bug**
There is no close button to close the About page

![console-bug](https://user-images.githubusercontent.com/11419617/138238224-b9ccf4f9-8750-4b81-944d-575ed63191cc.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.1
Kubernetes: v1.20.6

/kind bug

**Comment by zryfish** [comment]
Fixed in v3.2.0 
/close
