### ISSUE TITLE
servicemonitor settings shows incorrect data

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/console#2523]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
in application workloads -> service -> edit monitoring exporter, change interval to 3m, expired time to 10s, save it.
re-edit this exporter, found interval is still 1m, expired time is 10s (the default values).

![Screen Shot 2021-10-21 at 4 49 01 PM](https://user-images.githubusercontent.com/70880165/138244409-7394c0c6-b96b-4215-9e9e-38e759f84881.png)
![Screen Shot 2021-10-21 at 4 49 05 PM](https://user-images.githubusercontent.com/70880165/138244421-c6aa7a30-3fa6-48c1-a5c2-6978ec719a64.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: ks 3.1.0 through 3.2.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by liuyp2018** [comment]
this issue has been fixed ,Please close it if you confirmed that
