### ISSUE TITLE
advised to add message: Set the GPU limit to blank and cancel the limit

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2526]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/138382887-cf1b047c-1b76-454e-838e-456120d9554b.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0-rc.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @weili520 
/area console
/kind bug
/priority low

**Comment by weili520** [comment]
The prompt message in the input box has been optimized.

![截屏2022-01-06 18 04 42](https://user-images.githubusercontent.com/33231138/148365957-8fbdc880-8e77-4df0-8690-5472d6c5d88b.png)

**Comment by wenxin-01** [comment]
Issue fixed in `v3.2.1`

![image](https://user-images.githubusercontent.com/68640256/172289488-e8529655-5626-49db-b39c-8b4a02b1db7d.png)
