### ISSUE TITLE
‘Platform' navigation menu doesn't hide automatically when clicking 'app store' or 'workbench' link

### ISSUE THREAD

**Issue by calvinyv** [kubesphere/console#253]
**Describe the bug**
‘Platform' navigation menu doesn't hide automatically when clicking 'app store' or 'workbench' link

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**
1. Login to KubeSphere Console and click the 'Platform' menu on top left corner.
2. Click on 'app store' or 'workbench' link

**Expected behavior**
‘Platform' navigation menu should hide automatically.

**Comment by leoendless** [comment]
In 3.0, you can't click the header links if the platform management modal is open.
