### ISSUE TITLE
Remove the Activity option in the operation drop-down list of the pipeline list page.

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#2533]
**Describe the bug**

The **Activity** option as shown in the following figure is redundant and should be removed, because its only function is to go the **Activity** tab of the pipeline details page.

![image](https://user-images.githubusercontent.com/76198553/138633034-8822ec3a-92d2-4118-9a5b-d3be33ab2db2.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.2 alpha 1 

**Expected behavior**
![image](https://user-images.githubusercontent.com/76198553/138633255-76137861-10f2-4baf-8495-cdb6eeab2818.png)

/assign @harrisonliu5 @LinuxSuRen

**Comment by MukulKolpe** [comment]
Sorry, I'm stuck with some other work right now...It will be better if someone else takes it. Sorry for taking your time.

**Comment by LinuxSuRen** [comment]
> Sorry, I'm stuck with some other work right now...It will be better if someone else takes it. Sorry for taking your time.

Totally understand that. And thanks for letting us know it. Please feel free to join us once you are free.
