### ISSUE TITLE
Change UI element layout in the pipeline creation dialog box.

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#2546]
**Describe the bug**

**Clone Depth** should be a child element of **Enable shallow clone**, as shown in the following figure.

![image](https://user-images.githubusercontent.com/76198553/138993765-2b383091-19d9-4521-9f63-e23eaf810c5e.png)

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: 3.2 alpha 1

**Expected behavior**

![image](https://user-images.githubusercontent.com/76198553/138993991-ec2c6515-8ada-4aac-9877-f611a083cf07.png)

/assign @harrisonliu5 @LinuxSuRen

**Comment by weili520** [comment]
> Also, it would be great if someone could help me log into the dashboard. I'm using gitpod and I've updated the URLs in local_config.yaml but it seems like the requests are still failing. ![image](https://user-images.githubusercontent.com/52294825/139003862-805d1acf-f893-4e8f-900e-32ae6ea006aa.png)
> 
> ```
> TypeError: Cannot read property 'code' of undefined
>     at handleLogin (/workspace/console/server/controllers/session.js:68:19)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at async bodyParser (/workspace/console/node_modules/koa-bodyparser/index.js:95:5)
>     at async /workspace/console/server/components/errorProcess.js:24:7
>     at async /workspace/console/server/components/boot.js:52:9
>     at async /workspace/console/node_modules/koa-mount/index.js:52:26
>     at async /workspace/console/node_modules/koa-mount/index.js:52:26
>     at async /workspace/console/node_modules/koa-mount/index.js:52:26
>     at async /workspace/console/node_modules/koa-mount/index.js:52:26>     at async /workspace/console/node_modules/koa-compress/index.js:43:5
> ```
