### ISSUE TITLE
Incorrect verification rule

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2569]
**Describe the bug**
Incorrect verification rule

![image](https://user-images.githubusercontent.com/36271543/139450712-9cea5862-8da1-470d-893c-729410ad54c1.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: release-3.2
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/area logging
/kind bug
/priority Low

**Comment by xuliwenwenwen** [comment]
/assign @serenashe 
Tip text translation error.

**Comment by serenashe** [comment]
The minimum synchronization period is 180 seconds, which equals to **3** minutes. This is why it reported with error when you enter **2** seconds.

**Comment by serenashe** [comment]
> The minimum synchronization period is 180 seconds, which equals to **3** minutes. This is why it reported with error when you entered **2** minutes.

And if the tips should be varied according to the unit the users choose, I guess we need to add a few lines of code with the help of @xuliwenwenwen.

**Comment by xuliwenwenwen** [comment]
It translates to a synchronization period of at least 3 minutes and at most 24 hours. Isn't it better to understand

**Comment by serenashe** [comment]
> It translates to a synchronization period of at least 3 minutes and at most 24 hours. Isn't it better to understand

Ok, I'll change the descriptions.
