### ISSUE TITLE
Support search the pod,workload,service or other k8s source by the status.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#2592]
as title.

**Comment by wenxin-01** [comment]
Support search the pod,workload(deployments,statefulsets,daemonsets) ,job,cronjob by the status in cluster and project details.
use ks-version: `v3.3.0-rc.1`
![image](https://user-images.githubusercontent.com/68640256/172289613-39927de0-1fb6-46ac-b413-a6c8283259ab.png)
![image](https://user-images.githubusercontent.com/68640256/172289707-2311e17a-1ddb-4d5b-96c9-6281086b76c9.png)
![image](https://user-images.githubusercontent.com/68640256/172289728-2acb2e91-e307-4ee5-86c0-95dabec61699.png)
![image](https://user-images.githubusercontent.com/68640256/172289755-dc4e7115-38a3-44e0-b0c3-d9bdc6f16bf5.png)
![image](https://user-images.githubusercontent.com/68640256/172289914-c64cffe5-f551-49fc-8dbd-73695fdb8f36.png)
![image](https://user-images.githubusercontent.com/68640256/172289940-939c3dc7-4a97-4152-9bac-0855fcc36cab.png)
![image](https://user-images.githubusercontent.com/68640256/172291070-06a18318-87b8-4ad2-8a4f-169ebd1db0cf.png)
![image](https://user-images.githubusercontent.com/68640256/172291197-cb0a4087-d948-468e-b88f-7c2585e4a95f.png)
