### ISSUE TITLE
Pipeline running status and log cannot be updated automatically

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#2593]
**Describe the bug**
As I mentioned in the title. Users must refresh the browser manually to see the latest status.

/area devops
/priority high

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to the DevOps page
2. Create a Pipeline and run it.
3. Wait and check the running status and log output

**Expected behavior**
Users don't need to refresh manually.

## References
* https://kubesphere.com.cn/forum/d/5983-pipeline
* https://kubesphere.com.cn/forum/d/5994-kubesphere32devops

**Comment by JohnNiang** [comment]
Hi @harrisonliu5 , the status synchronization is `unstable`, somethings we will see the following screenshot:

![image](https://user-images.githubusercontent.com/16865714/142874880-e367c202-295f-40db-a8ed-e8f91308d0ee.png)

Test Jenkinsfile is as follows:

```groovy
pipeline {
  agent none
  stages{
    stage('Input test') {
      steps {
        input(id: 'deploy-to-prod', message: 'deploy to prod?')
      }
    }
  }
}
```

**Comment by JohnNiang** [comment]
https://github.com/kubesphere/console/issues/2593#issuecomment-975559644 might caused by PipelineRun data out of sync. I confirm that this issue has been fixed by https://github.com/kubesphere/console/pull/2594.

/close
