### ISSUE TITLE
please show kind information on view volume instance yaml page

### ISSUE THREAD

**Issue by gongysh2004** [kubesphere/console#2597]
**What would you like to be added**:
the view yaml page of volume instance is missing kind information, likely like this:

kind: PersistentVolume
apiVersion: v1

**Why is this needed**:

**Comment by liuyp2018** [comment]
I verify that the problem has been fixed
Please confirm and if so, please close

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`
![image](https://user-images.githubusercontent.com/68640256/172291694-1e3c59b9-fc9f-43ec-a45f-5981ae8907a2.png)
