### ISSUE TITLE
Invalid parameter “template” in edit mode of service

### ISSUE THREAD

**Issue by showjason** [kubesphere/console#2614]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When I create a service,  after filling the name and project, then switch to edit mode, a invalid parameter "template"
appeared in the yaml panel, as below pic:
![image](https://user-images.githubusercontent.com/27723125/141943312-1b9ed564-52cc-4218-9c25-c52f3f6eb6aa.png)
Even though this service still can be created successfully through ks-console, if I copy or download it with yaml format and execute it by "kubectl",  an error will be raised like below pic:
![image](https://user-images.githubusercontent.com/27723125/141945763-664cc226-eabd-4802-b340-55a92f1f7faa.png)

This phenomenon  may caused by function reused, which will make the  users who are not very familiar with kubernetes confused.
Perhaps, this parameter "template" should be erased from  the edit model of service.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.1
Kubernetes: v1.21.2

**Environment**
How many nodes and their hardware configuration: 

1 masters:  4cpu/16g
2 nodes: 8cpu/32g

**To Reproduce**
1. create service and fill the base info
![image](https://user-images.githubusercontent.com/27723125/141948072-7615842c-e601-4faa-a53a-bafca17926c5.png)
2. switch to edit mode
![image](https://user-images.githubusercontent.com/27723125/141948237-755c605b-c705-4c94-b611-850bea8ef799.png)

**Expected behavior**

**Comment by liuyp2018** [comment]
I verify that the problem has been fixed.
Please confirm, and if so, please close this issue
