### ISSUE TITLE
**All** is displayed for all app categories in the App Store

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#2631]
**Describe the bug**
In the App Store, **All** is displayed for all app categories, as shown in the following figure.
![image](https://user-images.githubusercontent.com/76198553/142830801-3185fdd5-0adf-4153-9864-e8d4871b7a61.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0

**Expected behavior**
![image](https://user-images.githubusercontent.com/76198553/142830890-5ddd76e2-a18b-4790-bc90-dab82dc6f05f.png)

**Comment by VioZhang** [comment]
I agree with @Patrick-LuoYu that the "ALL" should only be showed at the ALL tab.

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172323063-c040130b-8cd3-4d3d-93c5-984d6264720f.png)

![image](https://user-images.githubusercontent.com/88183150/172323160-2bf546a0-6917-4075-a7e0-f0ccad5bdbcb.png)

![image](https://user-images.githubusercontent.com/88183150/172323195-1fafabe3-b05d-46c3-8453-1a9d8c7e3266.png)

version used
kubesphere: v3.3.0-rc.1
