### ISSUE TITLE
HostPath volume name cannot be specified

### ISSUE THREAD

**Issue by serenashe** [kubesphere/console#2658]
**Describe the bug**
The name of HostPath volume cannot be specified when users mount volumes to the containers.

Screenshots that show the issue:
![image](https://user-images.githubusercontent.com/75245999/143191265-41b15587-84d5-4da3-af40-2a29e50b8e6a.png)
![image](https://user-images.githubusercontent.com/75245999/143191396-5c8c10cd-3a9e-4c12-8248-40f418150c8b.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.2.0

**Environment**
This is a multi-cluster environment.

**To Reproduce**
1. Go to **Cluster Management** > **Application Workloads** > **Workloads** > **Deployment**.
2. Click **Create**.
3. On the **Volume Settings** page, select **Mount Volume** > **HostPath Volume**.
4. Enter a volume name and click **√** in the lower-right corner.
5. On the **Volume Settings** page, you'll see the the name of the HostPath volume is autogenerated rather than the one you have specified.

**Expected behavior**
The volume name should be in accordance with the one users specified.
Please take a look, thanks!

**Comment by weili520** [comment]
This problem has been resovled in this [pr](https://github.com/kubesphere/console/pull/2656).
