### ISSUE TITLE
We can't jump to the correct component page of what we selected form the cluster status page.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#2666]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
We can't jump to the page of what we selected.For example,we click the logging,we will be leaded to the KubeSphere component status page and i think we should be leaded to the logging page.
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/41519383/143373987-8474c273-e478-4ca2-9b27-1d45af4a1417.png)
![image](https://user-images.githubusercontent.com/41519383/143374042-fe27a6ab-d2e9-4f38-b08e-f0b93bf1c6d8.png)

**Comment by liuyp2018** [comment]
fixed
/close
