### ISSUE TITLE
前端使用的ui框架是？自己写的吗？

### ISSUE THREAD

**Issue by wuchencm** [kubesphere/console#2675]
**What would you like to be added**:

**Why is this needed**:

**Comment by weili520** [comment]
The ui library we used is: [kube-design](https://github.com/kubesphere/kube-design.git).

**Comment by LinuxSuRen** [comment]
IMO, the response from @weili520 is good enough for the question. By the way, the GitHub issue is not a perfect place to ASK questions. Instead, users or contributors will report issues of the project.

And, this definitely is not a feature request. I'm going to remove the label `kind/feature`.

/kind-remove feature
/kind support
/close
