### ISSUE TITLE
prompt is missing a period

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2680]
**Describe the bug**
![image](https://user-images.githubusercontent.com/36271543/143816530-17c5f4e8-7ce0-4ef0-b3f7-5ead69af5e2a.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @Patrick-LuoYu

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172282729-ab3eda84-eb79-45a9-8284-e2c552e47821.png)
