### ISSUE TITLE
Devops projects that are not successfully created are not shown in grey disabled mode

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2713]
**Describe the bug**

After Jenkins service is abnormal, the Devops project created should be displayed as disabled in grey
![image](https://user-images.githubusercontent.com/36271543/144200406-273a2c53-d35b-47d5-8fa5-97f7ea324d12.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1-rc.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/priority Low
/assign @harrisonliu5

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172283446-e369f04d-c7d9-432b-b7b8-e7895bc00812.png)
