### ISSUE TITLE
Request to add a tip that s2i and b2i do not support containerd container runtime

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#2714]
At present(KubeSphere 3.2.0), s2i and b2i do not work well on containerd container runtime.

Please see:

- https://kubesphere.com.cn/forum/d/6195-kubespshere-32kubernetes1215/3 [In Chinese]

If we want s2i and b2i to support containerd container runtime, we can't do it in a short time. Therefore, I request to add a tip that s2i and b2i do not support containerd container runtime until we do that.

/area devops
/cc @kubesphere/sig-devops

**Comment by weili520** [comment]
How about add tips in here

![截屏2021-12-02 11 48 06](https://user-images.githubusercontent.com/33231138/144354379-5a18dea4-d076-4d33-a8c2-a165f0e6cf00.png)

**Comment by LinuxSuRen** [comment]
Looks good to me. But please only show the tip when the runtime is containerd.

**Comment by weili520** [comment]
> Looks good to me. But please only show the tip when the runtime is contained.

I plan to use this path to get the runtime info: `/api/v1/nodes`, it's correct?

**Comment by LinuxSuRen** [comment]
> I plan to use this path to get the runtime info: /api/v1/nodes, it's correct?

Sounds good to me.

**Comment by JohnNiang** [comment]
I've verified this issue, please refer to https://github.com/kubesphere/console/pull/2734#pullrequestreview-823231155.
/close
