### ISSUE TITLE
edit gateway error

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2723]
**Describe the bug**
error occurred when modifying the gateway
![image](https://user-images.githubusercontent.com/36271543/144365853-d0d37bd3-2ed5-4ba2-b8fb-503c134c14c6.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/kind bug
/priority high

**Comment by wenxin-01** [comment]
Issue fixed in `v3.2.1`
