### ISSUE TITLE
close button doesn't work

### ISSUE THREAD

**Issue by showjason** [kubesphere/console#2726]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When I try to close the window of deleting pod, click the close button , the window can not be closed. I also try other resources' deleting window  such as namespace, configmap etc. , they are also not working.

![image](https://user-images.githubusercontent.com/27723125/144367545-8bf594a5-b233-4f79-aa57-0b26cc9575a5.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0 and v3.1.1
Kubernetes: v1.19.0 and v1.21.2

**Environment**
How many nodes and their hardware configuration: 

1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by weili520** [comment]
Hi @showjason, thanks for your attention, and it's just a tip icon, user can only close this dialog by clicking the cancel button.

**Comment by showjason** [comment]
> Hi @showjason, thanks for your attention, and it's just a tip icon, user can only close this dialog by clicking the cancel button, maybe this is a bit confusing.

Ok，I will close this issue!
