### ISSUE TITLE
Update time of pipeline is displayed as' Invalid date '

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2732]
**Describe the bug**
1. Set the pipeline not to allow concurrent builds
2. Run 2 pipelines
3. Update time of the second pipeline is displayed as' Invalid date '.

![image](https://user-images.githubusercontent.com/36271543/144393358-7ba47f1f-7fff-4a13-98dd-cc8043a78032.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1-rc.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @harrisonliu5 
/kind bug
/priority Low

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`
