### ISSUE TITLE
error occurs when reduce copies of gateway in upgraded cluster

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2740]
**Environment**
cluster: 1 host + 1 member 
version: kubesphere v3.1.1

**Describe the bug**
1. upgrade cluster to ksv3.2.1-rc.1
2. in multi cluster project, add  the number of gateway copies to 2
3. Reduce the number of gateway copies to 1
4. error occurs

![image](https://user-images.githubusercontent.com/36271543/144568863-c6c7ed4a-5bf4-4a8a-a1e0-736c01030f7b.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1-rc.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/priority Medium
/milestone v3.2.1
/assign @harrisonliu5

**Comment by wenxin-01** [comment]
issue fixed in `v3.2.1`
