### ISSUE TITLE
The branch names are not escaped which makes some resources inaccessible

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#2747]
**Describe the bug**

The branch names are not escaped which makes some resources inaccessible.

![image](https://user-images.githubusercontent.com/16865714/144751157-1d96e2a1-8349-431f-9cf9-848b90371103.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0

**To Reproduce**
1. Create Multi-branch Pipeline, using repo https://gitlab.com/johnniang/jenkinsfile-multi-demo.
2. Click `Branches` tab
3. Go into branch `feat/featureA`
3. See error

**Expected behavior**

All places about branch names need to be escaped and then spliced into the URL. Below is an example:

```diff
- http://demo:30880/kapis/devops.kubesphere.io/v1alpha3/namespaces/demolq7ng/pipelines/branch-test/branches/feat/featureA
+ http://demo:30880/kapis/devops.kubesphere.io/v1alpha3/namespaces/demolq7ng/pipelines/branch-test/branches/feat%252FfeatureA
```

```js
branch.name = "feat%2FfeatureA"
escape(branch.name) = "feat%252FfeatureA"
```

This issue is part of https://github.com/kubesphere/ks-devops/issues/397.

/kind bug
/milestone v3.2
/priority high
/cc @kubesphere/sig-devops

**Comment by luoyuctl** [comment]
so here we go again , some fronted problem should be solved😂

**Comment by LinuxSuRen** [comment]
hi @mangoGoForward thanks for taking the initiative. We are going to release v3.2.1. And it is good to fix this issue as soon as possible. I'm not sure if you have time to do this. Please let us know if it's not.

**Comment by luoyuctl** [comment]
> hi @mangoGoForward thanks for taking the initiative. We are going to release v3.2.1. And it is good to fix this issue as soon as possible. I'm not sure if you have time to do this. Please let us know if it's not.


When do we plan to release 3.21?

**Comment by LinuxSuRen** [comment]
> When do we plan to release 3.21?

It should happen this week.

**Comment by JohnNiang** [comment]
> /kind need-to-verify

Please refer to https://github.com/kubesphere/console/pull/2753#pullrequestreview-823588176.
/cose
