### ISSUE TITLE
The text is not displayed in Chinese

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2760]
**Describe the bug**
The text is not displayed in Chinese
![image](https://user-images.githubusercontent.com/36271543/144962910-6d291926-ba12-4a00-b8c7-d3daba23671e.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1-rc.2
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @Patrick-LuoYu 
/priority Medium
/area documentation

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/144994253-2c48f295-cea8-4b03-9d69-d43bfde8c1fb.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/145000812-2b079477-8768-449a-9474-55bfbd42dd1d.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/145008578-5087ab58-54cf-40a0-b7e1-12ef3706c3b4.png)

**Comment by liuyp2018** [comment]
![image](https://user-images.githubusercontent.com/36271543/145014331-239ffe80-f28f-40c9-87ab-9dca8bda93b0.png)

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-rc.1`
