### ISSUE TITLE
Add options for multiple languages.

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#2771]
The KubeSphere localization project has been launched at [https://crwd.in/kubesphere](https://crwd.in/kubesphere). Though the localization project has just started, we need to add options for multiple languages in **User Settings** so that contributors can preview translations.

![image](https://user-images.githubusercontent.com/76198553/145160763-7ea09bdb-2bf1-476b-89fc-dd848d8fed9a.png)
![image](https://user-images.githubusercontent.com/76198553/145160995-d1bb67b6-35d8-485e-85c9-1471332dd9ce.png)

/assign @zryfish @harrisonliu5 @xuliwenwenwen

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172277683-9c33e17a-db2d-446e-adf5-e1b8d43b738a.png)
