### ISSUE TITLE
The data is empty when modifying the stateful service

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2774]
**Describe the bug**
1. In multi-cluster projects, create composing applications
2. Add a stateless service and a stateful service on the service setting page
3. Modify the stateful services

Expected Results:
The service data is the setting data 
Actual results:
The service data is empty

![image](https://user-images.githubusercontent.com/36271543/145162685-efa43aec-94e8-42d0-993b-eb7ef49d236e.png)

![image](https://user-images.githubusercontent.com/36271543/145163548-71567e49-f191-434e-9a68-92f3a6b0d7e1.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @harrisonliu5 
/priority Medium

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`
