### ISSUE TITLE
 the position of the operation button and the replicas counts need to adjusted 

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2776]
**Describe the bug**
In multi-cluster environment, the position of the operation button and the replicas counts need to adjusted on the create composing Application -->Service Settings page

https://user-images.githubusercontent.com/36271543/145166627-61b33384-f046-40cd-aafd-5699e9e7a77c.mp4

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @VioZhang 
/kind design

**Comment by XiaohuiSept** [comment]
Drawing design as follow:
https://www.figma.com/file/G6LDkjRMGtHq1NGkr5bIyI/Design-Requirements-Pool?node-id=924%3A341518
/cc @harrisonliu5

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-rc.1`

![Uploading image.png…]()
