### ISSUE TITLE
Request to disable "Stop" button when Pipeline record is in "Not Run" status

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#2780]
Request to disable "Stop" button when Pipeline record is in "Not Run" status, or backend would complain an error like below:

![image](https://user-images.githubusercontent.com/16865714/145172741-37d1d113-f4f7-4614-a4a8-36afe9b90c1f.png)

/area devops
/cc @kubesphere/sig-devops 
/kind bug
/priority high
/milestone v3.2

**Comment by harrisonliu5** [comment]
There is no run id when clicking the stop button. @JohnNiang

**Comment by JohnNiang** [comment]
> There is no run id when clicking the stop button. @JohnNiang

Yup. What I want is disabling or hiding the operation button on the right of a PipelineRun if the run id is missing. : )

**Comment by JohnNiang** [comment]
This issue has been fixed by #2804, please see https://github.com/kubesphere/console/pull/2804#pullrequestreview-827244737.
/close
