### ISSUE TITLE
Need to add input box validation

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2790]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/145182787-f16c4d33-c9bf-47b9-9bda-e8a8df9e1857.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @weili520 
/priority Low

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`
