### ISSUE TITLE
The url of 'User Manual' and 'API Documents' are error 

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#2791]
**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.2.1-rc.2`
**To Reproduce**
![image](https://user-images.githubusercontent.com/68640256/145185663-97f755d6-bb39-4a71-9cbb-a97a6d98f601.png)

/kind bug
/priority high
/cc @kubesphere/sig-console

**Comment by liuyp2018** [comment]
verified and fixed
/close
