### ISSUE TITLE
The quantity unit of the container group quota is incorrect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2797]
**Describe the bug**
The quantity unit of the container group quota is incorrect
![image](https://user-images.githubusercontent.com/36271543/145323521-5d303741-8e07-4da4-a3fc-8121a515e6cd.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @weili520 
/priority Low

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172287896-c2da86f4-09ad-496c-a337-faa0ed998f7b.png)
