### ISSUE TITLE
The user-defined resource quota is not displayed on the page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2798]
**Describe the bug**

The user-defined resource quota is not displayed on the page

https://user-images.githubusercontent.com/36271543/145324911-1f63a72e-d487-4de0-8661-9907abd82100.mp4

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @weili520 
/kind bug
/priority Low

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172518377-5d613611-ea11-4333-8941-933b7b6e660a.png)

![image](https://user-images.githubusercontent.com/88183150/172518441-456f622e-1c8d-4aff-9a22-02102cd3bdac.png)

version used
kubesphere: v3.3.0-rc.1
