### ISSUE TITLE
Event search enhancements & bugs

### ISSUE THREAD

**Issue by benjaminhuo** [kubesphere/console#280]
Below are items that needs to be adjusted for event search in ks v3.0:
- [x] Workspace search is missing
![image](https://user-images.githubusercontent.com/18525465/82794282-cc70ef80-9ea4-11ea-8c11-d31f06b04350.png)

Workspace （企业空间） workspace_filter/workspace_search

Namespace （项目）involved_object_namespace_filter / involved_object_namespace_search

- [x] invokeObject.namespace is displaced after invokeObject.kind, actually invokeObject.name should be displayed after invokeObject.kind

![image](https://user-images.githubusercontent.com/18525465/82854475-1e645480-9f3b-11ea-95c5-e3e429bc3a5a.png)

- [x] add Namespace(项目, invokeObject.namespace) after category(类别)

- [ ] The info on the second tab is incorrect
The first tab contains correct data:
![image](https://user-images.githubusercontent.com/18525465/83030910-85325c80-a066-11ea-96b9-f5ed473460ec.png)

The second tab contains incorrect data:
![image](https://user-images.githubusercontent.com/18525465/83031058-b3b03780-a066-11ea-9ddb-829f9e4de6c6.png)

**Comment by junotx** [comment]
The following bugs are waiting for being fixed:
- Here marked should be events count, not buckets count
![image](https://user-images.githubusercontent.com/49136171/82787942-12748600-9e9a-11ea-885f-f90b744e2a54.png)
- Here marked should be `involvedObject.name`, not `involvedObject.namespace`
![image](https://user-images.githubusercontent.com/49136171/82787816-d6412580-9e99-11ea-85bf-dbbd88f03cf5.png)

**Comment by leoendless** [comment]
- [ ] should add empty state if there are no events.
![image](https://user-images.githubusercontent.com/8739949/82789537-0c33d900-9e9d-11ea-8a2b-af4f32b3696a.png)

- [ ] The tab "窗口 1" should be removed. and the search input should be fixed on the top of the modal body, and the pagination should be fixed ob the bottom of the modal body. The event detail card's height should be the same with the modal body.
![image](https://user-images.githubusercontent.com/8739949/82790105-16a2a280-9e9e-11ea-8ff5-466f111c2a67.png)

- [ ] Another user ``tester`` with the same globalrole ``global-admin``, can't fetch any events. @junotx 

- [ ] Search by keyword call wrong API.

- [ ] Event type should be filterable.

**Comment by cw514102209** [comment]
Already read

**Comment by cw29112358** [comment]
![a](https://user-images.githubusercontent.com/62153598/83354147-c5a51980-a389-11ea-8bd9-352b5af0291a.png)
[] name to Resource Name

![c](https://user-images.githubusercontent.com/62153598/83354286-2896b080-a38a-11ea-9f39-2514927dcde1.png)
[] message_search as key_word_search
[] Highlight message_search
[] The list changes to scroll loading

![d](https://user-images.githubusercontent.com/62153598/83354306-63004d80-a38a-11ea-9477-576743df8a67.png)
[] fix Operation Details Field

**Comment by benjaminhuo** [comment]
@cw514102209 Would you submit a PR for this after modification like below?
Thanks

- 最早开始时间 => 最早发生时间
- 最近开始时间 => 最近发生时间

**Comment by benjaminhuo** [comment]
- [ ] English Name on Chinese UI， resource should be changed to `资源` on Chinese UI. Same changes should be made for Audit search.
![image](https://user-images.githubusercontent.com/18525465/85125490-515de780-b25e-11ea-8532-3fe8de49c121.png)

- [ ] The detail panel should be under the title row（title row is where 时间，类别，原因，消息 etc locate）
![image](https://user-images.githubusercontent.com/18525465/85125648-93872900-b25e-11ea-83b1-dc18e5c12ec1.png)

- [ ] Status code needn't to be translated to Chinese. All English is ok for both Chinese and English UI
![image](https://user-images.githubusercontent.com/18525465/85126192-8c144f80-b25f-11ea-9484-49512c04dc5f.png)

**Comment by wanjunlei** [comment]
In the cluster selection drop-down menu on the auditing query page, clusters that are not enable auditing are not displayed. This modification should also be reflected in the event query.
