### ISSUE TITLE
Can not access container info in resource status of nodeport gateway

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#2803]
**Versions used(KubeSphere/Kubernetes)**
KubeSphere: `v3.2.1-rc.2`
Kubernetes: (If KubeSphere installer used, you can skip this)

**To Reproduce**

Gateway type: `NodePort`

https://user-images.githubusercontent.com/68640256/145330139-6e3dbbfe-bc87-41ec-9fb4-38d5a31516e1.mov

![image](https://user-images.githubusercontent.com/68640256/145330298-678cd71e-947d-4399-91f8-92a92b7be609.png)

/kind bug
/priority high
/cc @kubesphere/sig-console

**Comment by liuyp2018** [comment]
fixed 
/close
