### ISSUE TITLE
The snapshot status is incorrect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2811]
**Describe the bug**

![image](https://user-images.githubusercontent.com/36271543/145368145-43958c90-d287-46cd-b25c-31a027c7699c.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1-rc.2
Kubernetes: (If KubeSphere installer used, you can skip this)

/kind bug
/assign @weili520 
/priority Low

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172525134-37c9e5fc-3990-4b17-9fec-9ea3ec45ff21.png)

version used
kubesphere: v3.3.0-rc.1
