### ISSUE TITLE
The ”value“ of secrets / configmaps needs to fit the box when editting setting

### ISSUE THREAD

**Issue by XiaohuiSept** [kubesphere/console#2835]
**Describe the bug**
When editing the setting of secrets / configmaps, the ”value“ of data overflow the box.

https://user-images.githubusercontent.com/72596911/145555324-53766c7d-87dc-4e78-bf29-32d788b999fe.mov

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @XiaohuiSept 
/kind design

**Comment by weili520** [comment]
It has beed fixed on v3.2.1-rc.2.

![截屏2021-12-13 11 17 18](https://user-images.githubusercontent.com/33231138/145747132-65b1c867-e692-475e-8a30-5bc7d9740201.png)
