### ISSUE TITLE
suggestion that adding a prompt for the button on the log page

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2850]
**Describe the bug**
The button does not have any prompt information. Users do not know the function of this button. It is advised to add a prompt information for the button.
![image](https://user-images.githubusercontent.com/36271543/146148515-0a6bcf5d-babb-4112-83fe-59acc2066dcd.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1-rc.3
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @weili520
/kind bug
/priority low

**Comment by weili520** [comment]
How about this tip?

![image](https://user-images.githubusercontent.com/33231138/147333219-272d12fb-58b0-4b3d-bd42-0f2e5cf1758e.png)

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172526513-a00d54ac-d7f8-40e4-a8d4-6bd4ce6aec26.png)

version used
kubesphere: v3.3.0-rc.1
