### ISSUE TITLE
Failed to create mirror warehouse secert for multi-cluster project

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2853]
**Describe the bug**
The cluster host is set to “test-host” when multiple clusters are turned on
1、Click Create Key, set the name, select the mirror warehouse secert, set the correct warehouse information, 
2、click verify, and the page will report an error

![image](https://user-images.githubusercontent.com/88183150/146155208-dd992003-59f1-4107-b6a5-1a11add6974e.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.1-rc.3

/kind bug
/@kubesphere/sig-console
/priority high

**Comment by weili520** [comment]
It seems not a big problem or a front-end problem and it will disappear if we rebuild a secret later. I can't reproduce it.

**Comment by jioce** [comment]
issue is fixed in v3.3.0-rc.1
