### ISSUE TITLE
List editing configuration dictionary and confidential dictionary failed

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2854]
**Describe the bug**

1、Enter the multi-cluster project, click the config, click the three points behind the list
 2、select edit settings, change the config information, click save, the page reports an error

![image](https://user-images.githubusercontent.com/88183150/146162864-b6787bc4-4751-4618-bf3f-f888479bd9fd.png)

1、Enter the multi-cluster project, click the secret, click the three points behind the list
2、select edit settings, change the secret information, click save, the page reports an error

![image](https://user-images.githubusercontent.com/88183150/146162942-3b3e832b-25e8-4946-87c2-873758c1534e.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.1-rc.3

/kind bug
/@kubesphere/sig-kubesphere
/priority high

**Comment by weili520** [comment]
kind need-to-verify

**Comment by jioce** [comment]
The problem of editing the configmaps still exists

![image](https://user-images.githubusercontent.com/88183150/147025709-b7d288d2-9ba8-4856-ba8c-be9d4c0c3600.png)

version used:
ks-console: nightly-20211221

**Comment by jioce** [comment]
issue fixed
version used: ks-console:nightly-20211223
