### ISSUE TITLE
Deleting all routing rules does not take effect

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#2855]
**Describe the bug**

Click Edit routing rules, delete all routing rules, click OK, save successfully, cluster routing rules still exist
![image](https://user-images.githubusercontent.com/88183150/146178535-70917dbe-2b0a-45a2-9d27-2220e013932f.png)

![image](https://user-images.githubusercontent.com/88183150/146178601-d8efc221-7676-4eb3-b1d6-cb7067f83a27.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.1-rc.3

/kind bug
/@kubesphere/sig-console
/priority medium

**Comment by jioce** [comment]
Create a route rr, there are two routing rules, as follows：

![image](https://user-images.githubusercontent.com/88183150/146179264-5c00dc82-8548-422e-b886-20196dacff25.png)

Delete the route of the member cluster, click save, the route is not deleted

![image](https://user-images.githubusercontent.com/88183150/146179370-6f71080e-fd61-40ac-b9cc-26146719f683.png)

![image](https://user-images.githubusercontent.com/88183150/146179410-f0ef929f-bed6-45cb-8e27-1a75bfa433eb.png)

**Comment by weili520** [comment]
I think,  this problem is caused by the Ingress lets every route must have `rules` or `defaultBackend` field, otherwise, we should delete that route. @harrisonliu5

**Comment by iawia002** [comment]
When a cluster is deselected, the cluster data in the `federatedingresses` API is not updated

<img width="744" alt="Screen Shot 2021-12-21 at 5 53 56 PM" src="https://user-images.githubusercontent.com/9134003/146910624-bdd162e9-1d37-447b-90f5-ed091ccb0252.png">

**Comment by jioce** [comment]
issue fixed 
version used: ks-console:nightly-20211223
