### ISSUE TITLE
Use kubectl apply workload yaml failed. 

### ISSUE THREAD

**Issue by weili520** [kubesphere/console#2870]
**General remarks**

**Describe the bug**

+ If we use `kubectl apply -f 1.yaml`, it will field with an error that `unknown field "gpu" in io.k8s.core.v1.ResourceRequirements; if you choose to ignore these errors, turn validation off with --validate=false`. 

+ the `1.yaml`  config is `copied from` the console workload YAML

![image](https://user-images.githubusercontent.com/33231138/147058721-ddfb81a6-94bc-45dc-a038-48d9dcd54d72.png)

+ copied from here

![截屏2022-01-06 16 55 14](https://user-images.githubusercontent.com/33231138/148356864-2fcefb06-95c5-4bc1-adf7-b7af73fb82db.png)

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: v3.2.1

**Environment**

It's not important.

**To Reproduce**
1. create a workload, and switch to edit yaml mode, then you will get the workload object config.
2. Use the kubectl toolbox in the lower right corner, and touch a file names 1. yaml.
3. copy the workload yaml config into the 1.yaml and save
4. use `kubectl apply -f 1.yaml`, you will get an error: `unknown field "gpu" in io.k8s.core.v1.ResourceRequirements; if you choose to ignore these errors, turn validation off with --validate=false`

**Expected behavior**

create a workload successfully

**Comment by jioce** [comment]
issue is fixed in v3.3.0-rc.1
