### ISSUE TITLE
The number of worker nodes is  incorrect

### ISSUE THREAD

**Issue by liuyp2018** [kubesphere/console#2875]
**Describe the bug**
The number of worker nodes is  incorrect
![image](https://user-images.githubusercontent.com/36271543/147342174-e76be469-30a7-49d4-9a40-ffa8c08e1880.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @weili520
/kind bug
/priority low

**Comment by wenxin-01** [comment]
Issue fixed https://github.com/kubesphere/kubesphere/issues/4783
