### ISSUE TITLE
Change the prompt for the shell to access the node interface

### ISSUE THREAD

**Issue by lynxcat** [kubesphere/console#2902]
**What would you like to be added**:
Modify the appropriate prompt in the shell to access interface
![image](https://user-images.githubusercontent.com/2222701/148742481-d6b7c040-f14d-454e-902a-83a05a8c1a35.png)

**Why is this needed**:
In the function of shell access to node, I used the kubectl component, the original prompt of this component is not suitable for this function

**Comment by weili520** [comment]
I will deal with it.

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-installer:nightly-20220524`
