### ISSUE TITLE
Invalid API request of persistentvolumeclaims in  member cluster environment 

### ISSUE THREAD

**Issue by xuliwenwenwen** [kubesphere/console#2925]
**Describe the bug**

Invalid API request of persistentvolumeclaims in  member cluster environment.
```bash
https://console.kubesphere.io/api/v1/namespaces/test-12/persistentvolumeclaims/hellos-cxzc-0
```

![image](https://user-images.githubusercontent.com/74528885/150750351-744035ec-7ca4-44eb-bc25-3e847e9b6a76.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0-89+77d14fe4dce0e8
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
Multi-cluster environment

**To Reproduce**

**Expected behavior**
The correct API should be as below:

```diff
- https://console.kubesphere.io/api/v1/namespaces/test-12/persistentvolumeclaims/hellos-cxzc-0
+ https://console.kubesphere.io/api/clusters/rohan/v1/namespaces/test-12/persistentvolumeclaims/hellos-cxzc-0
```

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172545562-62405507-96bc-4e6c-9834-e6e156feaaa1.png)

version used
kubesphere: v3.3.0-rc.1
