### ISSUE TITLE
Request to support manage GitOps resource deploy request

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#2966]
**What would you like to be added**:
Currently, we're using Argo CD  to deploy the applications. Please see the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/156093171-b3bfda80-e1a4-448e-9b59-25ad48903a43.png)

![image](https://user-images.githubusercontent.com/1450685/156093209-89e97155-d35c-4b4a-a7e2-da413c49a730.png)

![image](https://user-images.githubusercontent.com/1450685/156094279-61efc0a9-eda9-409c-88a8-210bd3451918.png)

![image](https://user-images.githubusercontent.com/1450685/156093335-b69195b9-e937-4cf8-8022-946136126855.png)

![image](https://user-images.githubusercontent.com/1450685/156093831-c54910be-7121-4004-8c3e-d246df062cc2.png)

![image](https://user-images.githubusercontent.com/1450685/156094019-5cb2920c-cb80-4932-bce9-c68af499c35d.png)

See more details from https://github.com/kubesphere/ks-devops/issues/63

**Why is this needed**:

/area devops
/priority high

**Comment by LinuxSuRen** [comment]
Below are the screenshots of the list or details pages:

![image](https://user-images.githubusercontent.com/1450685/156094652-95d25433-4bb3-411e-99c2-e2d7f8d93a62.png)

![image](https://user-images.githubusercontent.com/1450685/156095352-3723a1bd-aaac-4ed4-985d-cc720afc6aa0.png)

![image](https://user-images.githubusercontent.com/1450685/156095647-bea10b43-729a-4fbe-af61-819b9a1799b5.png)

![image](https://user-images.githubusercontent.com/1450685/156096236-3cd45146-3d1d-4209-90df-4f93837e223a.png)

**Comment by codering** [comment]
Great ! When will this be released ?

**Comment by LinuxSuRen** [comment]
hi @codering , glad to see you here. We will have the alpha version on April 1.

**Comment by LinuxSuRen** [comment]
This feature is finished.
