### ISSUE TITLE
Remove the **Schedulable** field in cluster node details and edge node details.

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#2971]
The **Schedulable** field in cluster node details and edge node details is redundant because when the node is unschedulable, its **Status** will become **Unschedulable**. Therefore, the **Schedulable** field should be removed.

![image](https://user-images.githubusercontent.com/76198553/156494671-58b04f82-9564-4f2b-a640-164f91e5eaa7.png)

/assign @VioZhang @harrisonliu5

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-nightly20220524`
![image](https://user-images.githubusercontent.com/68640256/170231550-a3f29efd-26d6-4126-9db1-e4157d86ba12.png)
![image](https://user-images.githubusercontent.com/68640256/170231602-3f9b4b05-a42e-41c5-bf08-aa32bfdf4470.png)
