### ISSUE TITLE
Optimize the UI of deleting resource.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#2982]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/41519383/157411917-faaf297e-698c-480c-ae4d-66b7852d2b1d.png)

**Comment by VioZhang** [comment]
![image](https://user-images.githubusercontent.com/41519383/157834819-a985d54d-3fea-4bd4-b19a-e04034afd67d.png)
![image](https://user-images.githubusercontent.com/41519383/157834904-02b9a24d-7cd2-4b2f-9719-cc416c6f6385.png)
![image](https://user-images.githubusercontent.com/41519383/157834980-de2aee5e-1bb3-4ae9-8c9e-709ce26705a7.png)

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/170235272-cf7704c0-2888-42ef-b95b-43c772aaefda.png)

version used
v3.3.0-rc.0
