### ISSUE TITLE
Remove the Version field on the Revision Records tab page.

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#2987]
**Describe the bug**

The **Version** field on the **Revision Records** tab page is only a label of a deployment. It does not indicate the versions of different revisions and cannot be changed after a deployment is created. In addition, it is misleading. Users may tend to believe this field indicates the version of each revision. Therefore, we should remove the **Version** field.

![image](https://user-images.githubusercontent.com/76198553/157795531-63e5e06a-8416-4cc9-bb76-8cbb1f4a4a09.png)

/assign @zryfish @VioZhang @harrisonliu5

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:nightly-20220605`

![image](https://user-images.githubusercontent.com/68640256/172127602-3b89d0e7-cf38-44f4-809a-b4a36e3b3742.png)
