### ISSUE TITLE
Remove the duplicate function on the service account list page

### ISSUE THREAD

**Issue by serenashe** [kubesphere/console#3000]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
There's a redundant functional area in the service account list page.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/75245999/158509725-dd1c6f7f-c2dc-4704-951d-3e495c48c53f.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**To Reproduce**
1. Log in to the KubeSphere web console.
2. In the upper-left corner, select **Platform > Cluster Management**.
3. On the left nevigation pane, select **Configuration > Service Accounts**.
4. Click the three dots on the right of a service account, and then select **Edit**.
5. In the **Edit Information** dialog box, you can change the role of a service account.
However, in the **Change Role** dialog box, you can perform exactly the same action.

**Expected behavior**
Therefore, the **Project Role** section in the **Edit Information** dialog box is redundant and needs to be removed to keep the UI simple and clear.

/assign @weili520 Please take a look and help fix this issue, thanks!

**Comment by weili520** [comment]
ok.
