### ISSUE TITLE
Request to add event tab for a pipeline run record

### ISSUE THREAD

**Issue by JohnNiang** [kubesphere/console#3003]
**What would you like to be added**:

As I mentioned in the title, I request to add event tab for a pipeline run record to tell users what happened in the past, please see:

![image](https://user-images.githubusercontent.com/16865714/158540726-4f548414-896c-4508-a04a-eb400acc72f2.png)

You can refer to:

![image](https://user-images.githubusercontent.com/16865714/158540811-f25c957f-4ab0-448c-ac28-05f87bea7da8.png)

**Why is this needed**:

It's very useful when a pipeline run fails.

/area devops
/cc @kubesphere/sig-devops

**Comment by JohnNiang** [comment]
This issue has been fixed by 
- #3012 

Please see https://github.com/kubesphere/console/pull/3012#pullrequestreview-921293335.

/close

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.0`
