### ISSUE TITLE
Failed to mount the PVC in the order shown in the video

### ISSUE THREAD

**Issue by klj890** [kubesphere/console#3009]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

https://user-images.githubusercontent.com/19380605/159639290-d05aff1d-dec5-4da4-827e-6ec7a4eff3e1.mp4

Failed to mount the PVC in the order shown in the video

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.2.1

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172126586-2bfd11bb-fb36-43d2-b42a-994f936a2b6e.png)
