### ISSUE TITLE
It will fail if we create the pvc through dragging the scrollbar.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#3015]
![944b3cc6127e7be2d1176139b70a18e](https://user-images.githubusercontent.com/41519383/160104049-dd685420-f1ed-466e-b7fc-2a2fe04e95c9.png)
![c0b713fc81a66255880a8fc3ad8ef87](https://user-images.githubusercontent.com/41519383/160104072-f1e3a558-a6bb-478a-8a07-0c90b584c6f6.png)
![7da348d508e2aa50eab4d39c987bbd9](https://user-images.githubusercontent.com/41519383/160104100-8d0a551a-91e9-4b08-a5f0-15eb71d0bd8b.png)

**Comment by weili520** [comment]
This problem has been resolved in the previous pull request.

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:nightly-20220605`
