### ISSUE TITLE
The drop-down list on the container terminal page is not working

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#3040]
**Describe the bug**

The drop-down list on the container terminal page is not working, as shown in the following figures.

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/76198553/161002095-d71b898b-0a84-4723-9231-cbbd97236c3b.png">

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/76198553/161002213-1fe0b3a7-e706-46bb-a22b-3bb3ce0d6745.png">

**Expected behavior**

When another container is selected, the container terminal should be changed.

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/172547557-85cebea7-0171-4465-9e1f-cc8c48948a74.png)

![image](https://user-images.githubusercontent.com/88183150/172547619-eb8bc369-9fcc-46bc-956f-56cf29ae7ce7.png)

version used
kubesphere: v3.3.0-rc.1
