### ISSUE TITLE
Optimize the 'Service Type' and 'External Access' columns of the service list

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#3046]
![image](https://user-images.githubusercontent.com/76198553/161371482-c71c2d03-9e4b-4269-a4f9-e21e5056d46c.png)

The 'Service Type' and 'External Access' columns are quite misleading. My suggestions are as follows:

* Change the header 'Service Type' to 'Internal Access', and display internal access modes (VirtualIP or Headless) and internal addresses (virtual IP addresses or domain names) in the column.
* Do not display virtual IP addresses in the 'External Access' column because virtual IP address cannot be accessed from outside the cluster.
* Remove the concepts 'Custom Service', 'Stateful Service', and 'Stateless Service' because they are concepts unique to KubeSphere and are misleading.
* As to ExternalName services, I recommend that 'ExternalName', service domain names, and target domain names be displayed in the 'Internal Access' column, where target domain names be displayed in pop-up bubbles. And I invite suggestions from the design team, other developers, and other users on this issue.

/assign @zryfish @harrisonliu5 @VioZhang

**Comment by jioce** [comment]
issue is not fixed
![image](https://user-images.githubusercontent.com/88183150/170231133-2bc51e26-f58b-4b2d-8dc3-162f9adc8e88.png)

version used
nightly-20220524

**Comment by wenxin-01** [comment]
Issue fixed in `console: harrisonliu5/ks-console:master`


![image](https://user-images.githubusercontent.com/68640256/170618307-1a5bd92e-e8c9-43b0-b97f-55581e07f66b.png)
