### ISSUE TITLE
Service session affinity is not working

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#3047]
**Describe the bug**

Service sticky session (session affinity) settings are not synchronized with the service YAML, as shown in the following figures:

![image](https://user-images.githubusercontent.com/76198553/161374451-38dc1e74-a514-4710-9b40-142166f9b763.png)

![image](https://user-images.githubusercontent.com/76198553/161374487-2c8895d4-5f88-4ac0-b4fe-b703cd58ed80.png)

**Expected behavior**

`sessionAffinity: ClusterIP` is displayed in the YAML settings. 

/assign @zryfish @weili520

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/170230597-243d0bed-a46e-4d79-a863-add1b1b318f4.png)

version used
nightly-20220524
