### ISSUE TITLE
Display route description in the route list

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#3057]
The description of a route is not displayed in the route list. Displaying description in the route list could be helpful for users.

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/76198553/161957485-5c63f190-6649-49dd-acce-1c6b397ae9af.png">

/assign @zryfish @weili520

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:nightly-20220605`

![image](https://user-images.githubusercontent.com/68640256/172120323-cdcb45ca-1bc5-4a39-bc0f-f5a814435328.png)
