### ISSUE TITLE
It should show the usage of the CPU or memory ,but not the percentage.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#3068]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

For UI issues please also add a screenshot that shows the issue.
It should show the usage of the CPU or GPU,but not the percentage.And the node moniting page shows the wrong target while the deployment moniting page shows the right target.
The deployment moniting page which is right:
![image](https://user-images.githubusercontent.com/41519383/162674500-39b5d9e7-979d-42f5-aa76-d16f6bc3c0ac.png)
The node moniting page which is wrong:
![image](https://user-images.githubusercontent.com/41519383/162674636-db206a11-4e18-4053-af28-ac6ac179472e.png)

/cc @kubesphere/sig-console

**Comment by junotx** [comment]
For node, the usage value cannot express the memory and cpu stress, but the percentage may make more sense.
