### ISSUE TITLE
The worker node count and node role displayed on the node list page are incorrect when there is only one node

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/console#3079]
When there is only one node in the cluster, the worker node count ("0") and node role ("Control plane") displayed on the node list page are incorrect, which should be "1" and "Control plane/Worker" respectively.

<img width="793" alt="image" src="https://user-images.githubusercontent.com/76198553/162892859-18d9aa0b-d545-49e8-ad82-cc07e9f2efe8.png">

/assign @harrisonliu5 @VioZhang

**Comment by VioZhang** [comment]
consistent with cc
![image](https://user-images.githubusercontent.com/41519383/211484484-e21fabb1-b352-4e34-871b-3d42c97baec6.png)

**Comment by VioZhang** [comment]
> consistent with cc ![image](https://user-images.githubusercontent.com/41519383/211484484-e21fabb1-b352-4e34-871b-3d42c97baec6.png)

Is there any way by which we can get the information of the node's role from cc? It seems that we can not get it and only can get the number from the interface from the label " node-role.kubernetes.io/master". @zheng1 @pixiake

**Comment by VioZhang** [comment]
Delete the "work node".

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-installer:release-3.3`

![image](https://user-images.githubusercontent.com/68640256/212819895-3935513c-bc39-41a8-ac31-a1c392439e63.png)
