### ISSUE TITLE
Incorrect placeholder of the code repository on the project setting page

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#3085]
**Describe the bug**
As I mentioned in the titile.

![image](https://user-images.githubusercontent.com/1450685/162899770-6636c376-a156-4505-b3b3-789cef345f81.png)

/area devops
**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-alpha.0

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to DevOps project
2. Go to the prjoect setting page
3. Add a new repo
4. See errors

**Expected behavior**
Have a correct placeholder.

**Comment by jioce** [comment]
issue is fiixed 
![image](https://user-images.githubusercontent.com/88183150/170224976-010675b7-c6f6-4708-8f35-15d67c429e39.png)

version used
nightly-20220524
