### ISSUE TITLE
"undefined" is displayed in the automatically generated domain name of a route

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/console#3090]
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/76198553/162924110-a3f2968b-54d3-44bf-8741-c5bcc081baf3.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.3.0 alpha0

**Expected behavior**
The project name is displayed instead of "undefined".

**Comment by weili520** [comment]
This name was created by the k8s.

The requested URL is: `/apis/clusters/host/networking.k8s.io/v1/namespaces/dddd/ingresses/nginx`

The response:

![截屏2022-04-13 16 33 27](https://user-images.githubusercontent.com/33231138/163135086-24c281f7-95aa-4065-93dc-6f99902247b8.png)

**Comment by hongzhouzi** [comment]
The host value is not automatically generated in version ks 3.3, so there is no longer this problem.
