### ISSUE TITLE
next page display items which displayed in prev page (分页显示不正确BUG)

### ISSUE THREAD

**Issue by mikexu-github** [kubesphere/console#31]
Total 12 records, first page 10 items,  so next page should display left 2 items, but  what i'got are 2 items displayed in prev.  page.
(共有12条记录，分两页。第一页显示10-条，第二页显示2页，但点击第二页时，看到的却是在第一页上看到的记录)
![BUG-显示排序-1](https://user-images.githubusercontent.com/58680457/70413983-b9ec3080-1a93-11ea-8801-60e312d8232a.png)
![BUG-显示排序-2](https://user-images.githubusercontent.com/58680457/70413987-bbb5f400-1a93-11ea-8e0d-d65521f57c94.png)

**Comment by leoendless** [comment]
@wansir 应该是后端api 返回异常

**Comment by leoendless** [comment]
Fixed in v2.1.1
