### ISSUE TITLE
Service topology map traffic monitoring information displays errors

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#3103]
**Describe the bug**
1、There is an application that contains a service that continuously accesses the service
![image](https://user-images.githubusercontent.com/88183150/163116983-068e9855-4b89-4b4f-8302-efc1fd5c8e8d.png)

![image](https://user-images.githubusercontent.com/88183150/163117300-5da91eca-dc17-46ba-b16f-6583592f99c1.png)

2、Enter the service topology map page, click the service name，click Traffic ，information is empty
![image](https://user-images.githubusercontent.com/88183150/163117225-a4383505-3c37-49b6-bee4-d3b50049aa59.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-alpha.0

/kind bug
/priority Medium

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/163356353-cc84fa8a-2ed2-48ed-86e6-102298c38a74.png)
 
the data is empty!

**Comment by renyunkang** [comment]
Enabling the service topology will consume a lot of resources. Therefore, it is not recommended to enable service topology by default.
If you need it, you can start the service topology in the following ways:
● Enable the weave-scope topology by editing the daemonset weave-scope-agent container args. _(delete `- '--probe.processes=false'`)_
● Remove read-only access to volumeMounts._(delete `readOnly: true`)_
