### ISSUE TITLE
Residual data is displayed when custom monitoring dashboards are created consecutively

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#3115]
**Describe the bug**
When I create a custom monitoring dashboard after another custom monitoring dashboard was created, data of the previous custom monitoring dashboard is displayed.

<img width="1428" alt="image" src="https://user-images.githubusercontent.com/76198553/163334196-9011c64f-0ec4-42d9-b588-fc3efcfab15d.png">

<img width="948" alt="image" src="https://user-images.githubusercontent.com/76198553/163334311-b66948da-2c8c-4a91-8cdd-c71ccf75564a.png">

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/76198553/163334356-a7fd7a37-e22c-45b3-8982-3ef12cc977d8.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.3 alpha0

**To Reproduce**
1. Create a custom monitoring dashboard using the template `Custom`.
2. Do not refresh the page and create another one using the template `Custom`. Data of the previous custom monitoring dashboard is displayed.

**Expected behavior**
Data the previous custom monitoring dashboard is not displayed.

/assign @zryfish @harrisonliu5 @kubesphere/sig-observability

**Comment by jioce** [comment]
isue is fixed in v3.3.0-rc.1
