### ISSUE TITLE
Bars of a custom monitoring dashboard exceed the boundary

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#3118]
**Describe the bug**
Bars of a custom monitoring dashboard exceed the boundary when the data sampling interval is set to 1 hour.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.3 alpha0

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/76198553/163373616-9119cf2b-7ad4-4f65-a241-b64e3082d4ac.png">

**Expected behavior**
All bars are within the boundary of the chart.

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172523671-db8370de-818e-461e-88cf-2910ac64aabe.png)

version used
kubesphere: v3.3.0-rc.1
