### ISSUE TITLE
Editing a network watcher to understand the error

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#3139]
**Describe the bug**
1、Create a gateway, select a load balancer, select OpenBL for the provider, do not set annotations, click create
2、The creation is successful, click Edit, and the annotation is displayed as the default annotation of qingcloud Kubernetes Engine
![image](https://user-images.githubusercontent.com/88183150/163766629-cafddbf9-3fba-4357-b27b-70d968fa3885.png)

![image](https://user-images.githubusercontent.com/88183150/163766670-2dbd5a86-5f9f-4a59-9ac2-dabe511c7317.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-alpha.1

**Expected behavior**
should appear empty

/kind bug
/priority Medium

**Comment by jioce** [comment]
Edit Annotation key not showing
![image](https://user-images.githubusercontent.com/88183150/165242457-f742bb5c-6211-4896-be91-c10c01088bf3.png)

Select the load balancer provider openelb again, the desired key is displayed
![image](https://user-images.githubusercontent.com/88183150/165242526-8af190e9-bbd9-44a4-a12d-8ce9ccb48ac2.png)

**Comment by wenxin-01** [comment]
@harrisonliu5

**Comment by wenxin-01** [comment]
https://github.com/kubesphere/console/issues/3410
