### ISSUE TITLE
Should not able to see the CD menu if only have the code repository permission

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#3146]
**Describe the bug**
As I mentioned in the title. See the following screenshot:

![image](https://user-images.githubusercontent.com/1450685/163781772-67ba4fae-0e1e-43c3-8e2f-bbb30fd8f894.png)

/area devops
/priority high
**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-alpha1

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Create a new role that only has the code repository permission on the DevOps page
2. Create a user who have that role, and put it into a DevOps project
3. Login with this user
4. See the errors

**Expected behavior**
They cannot see the CD menu if a user only has the code repository permission.

**Comment by harrisonliu5** [comment]
![image](https://user-images.githubusercontent.com/17872673/163784127-b749671f-2357-4897-b233-a8ad6ec66392.png)

**Comment by LinuxSuRen** [comment]
hi @harrisonliu5 , thanks for helping do the troubleshooting. This problem should caused by  the backend.

**Comment by jioce** [comment]
issue fixed 
![image](https://user-images.githubusercontent.com/88183150/170221987-ec6c991a-56b6-4084-aea1-396002e2f627.png)


version used
nightly-20220524
