### ISSUE TITLE
Content is occluded

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3150]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68640256/163795199-7c242193-38c3-4b93-9bd5-31629468d864.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0-alpha.1`

/priority medium
/assign @kubesphere/sig-console

**Comment by weili520** [comment]
Now:
![截屏2022-04-19 11 22 33](https://user-images.githubusercontent.com/33231138/163913825-aeb9be37-3712-4cc3-96c3-89c84fd09c5a.png)

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-alpha.2`
![image](https://user-images.githubusercontent.com/68640256/166853816-bb3d3628-67c2-4ddc-9553-86c50ade8d54.png)
