### ISSUE TITLE
Deployment location is required

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3154]
**Describe the bug**

https://user-images.githubusercontent.com/68640256/163915299-fb12aa6d-c1fa-442b-bc5c-ba5eb397980c.mov

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0-alpha.1`

/priority medium
/assign @kubesphere/sig-console

**Comment by harrisonliu5** [comment]
could `kapis/gitops.kubesphere.io/v1alpha1/clusters` be replaced by `kapis/tenant.kubesphere.io/v1alpha2/clusters`?

@LinuxSuRen @wansir

**Comment by LinuxSuRen** [comment]
> could `kapis/gitops.kubesphere.io/v1alpha1/clusters` be replaced by `kapis/tenant.kubesphere.io/v1alpha2/clusters`?

For this case, we can only use the previous one. Users might integrate different cluster with argo.

**Comment by wenxin-01** [comment]
issue fixed in `v3.3.0-alpha.2`
