### ISSUE TITLE
Code repository option status shows error

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3156]
**Describe the bug**

The same repository address is used to create multiple code repositories，
I suspect that the front end uses the repository address instead of the repository name when selecting the code repository.

https://user-images.githubusercontent.com/68640256/163917295-45f4c159-9b6a-473e-896a-f2e9f51b61c2.mov

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0-alpha.1`

**To Reproduce**

/priority medium
/assign @kubesphere/sig-console

**Comment by harrisonliu5** [comment]
There are the same RepoURL?

**Comment by wenxin-01** [comment]
issue not fixed in `v3.3.0-alpha.2`
![image](https://user-images.githubusercontent.com/68640256/166853533-9e38e986-1f68-4f38-999a-de64cb7d8365.png)

**Comment by wenxin-01** [comment]
> There are the same RepoURL?

yes

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0-rc.0`
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/68640256/169693130-3ca9a071-37e3-44ce-8b05-f6e7100e11b0.png">
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/68640256/169693164-a43c6a22-7c94-4d52-b6b0-b67f6caf43d1.png">
