### ISSUE TITLE
Optimize the description of the configmap variables where we edit the env of the workload

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#3157]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
Optimize the description of the configmap variables where we edit the env of the workload
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/41519383/163927549-6cd4c80e-3c7a-4f7e-b9a1-c8959b0047e9.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:3.3.0 alpha 1
Kubernetes: (If KubeSphere installer used, you can skip this)

/cc @kubesphere/sig-console

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/170223105-33700742-3ee1-4238-b042-d2d1878a63ab.png)

version used
nightly-20220524
