### ISSUE TITLE
Can't open alert pages

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#316]
can't open alerting message and alerting policies pages
<img width="1106" alt="Screen Shot 2020-06-02 at 2 39 10 PM" src="https://user-images.githubusercontent.com/28859385/83488182-fea2d280-a4de-11ea-92a1-55e14cb1e3a3.png">

**Comment by zryfish** [comment]
It's a configuration issue, not a bug, already fixed in dev env

**Comment by rayzhou2017** [comment]
verified
