### ISSUE TITLE
In a multi-cluster scenario, after weave-scope is enabled in the member cluster, after logging in to the console of the host cluster and switching to the member cluster, the service topology tab on the service page cannot be seen.

### ISSUE THREAD

**Issue by smallersoup** [kubesphere/console#3165]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

In a multi-cluster scenario, after weave-scope is enabled in the member cluster, after logging in to the console of the host cluster and switching to the member cluster, the service topology tab on the service page cannot be seen.

The following screenshot is the service page you see after switching to the member cluster after logging in to the host cluster console:
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/21979752/164179420-3a420dfd-bde4-4b93-8737-2d7751b5ccca.png">

The following screenshot is the service page you see when you log in directly to the console of the member cluster:
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/21979752/164179872-65a1e9de-7986-42a3-b4b3-6c85f4355169.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.1.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**

**Expected behavior**

**Comment by weili520** [comment]
This problem not reproduced in v3.3.1.

* This is the `ClusterConfiguration` for member cluster:
![截屏2023-01-11 14 30 22](https://user-images.githubusercontent.com/33231138/211734604-301054ec-fa46-4d98-a1a9-90782974003a.png)

* The `lcj-multi` is a multi-cluster workspace, the `mem-pro` project is belongs to member cluster: 
![截屏2023-01-11 14 33 29](https://user-images.githubusercontent.com/33231138/211734737-615909f1-c6f7-4589-bc79-7de2a4266666.png)

* The service topology tab of  `mem-pro` is show normal:
![截屏2023-01-11 14 35 54](https://user-images.githubusercontent.com/33231138/211735270-c525a796-b0ca-40c4-aea3-b2323462072b.png)

**Comment by wenxin-01** [comment]
I reproduced the problem in `ks v3.3.1`  @weili520 

![image](https://user-images.githubusercontent.com/68640256/212845901-18d0d967-ea03-426e-86c6-41d4fa36d8f8.png)

![image](https://user-images.githubusercontent.com/68640256/212846056-0b51cb8d-9430-48c9-8fc5-6086235635b9.png)

**Comment by wenxin-01** [comment]
Can't reproduce this issue.
