### ISSUE TITLE
The front-end of the edgeruntime component is not displayed when it is turned on

### ISSUE THREAD

**Issue by wenchajun** [kubesphere/console#3182]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

For UI issues please also add a screenshot that shows the issue.

In kubespherev 3.3, I started the `edgeruntime` component, but there is no interface displaying the edge nodes in the front-end.But you can see that the relevant containers and namespaces have been deployed.
![1650607689(1)](https://user-images.githubusercontent.com/39892300/164616167-1eed3dea-57d6-4f73-b1ae-d043be34ac91.png)
![1650607731(1)](https://user-images.githubusercontent.com/39892300/164616188-8b9074a1-915a-40d3-af64-f7c71602609a.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.3-alpha1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/8g

(and other info are welcomed to help us debugging)

**To Reproduce**

**Expected behavior**

**Comment by jioce** [comment]
issue fixed in v3.3.0-alpha.2
