### ISSUE TITLE
Screenshield the "auto generate" of the route setting and the other page influenced.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#3184]
Screenshield the "auto generate" of the route setting and the other page influenced.
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/41519383/164619974-d7b81265-7df7-49f6-8750-808440c80292.png)
![image](https://user-images.githubusercontent.com/41519383/164624276-5e28186f-d0ce-4bd7-898e-cd42a6a989ef.png)

**Why is this needed**:
For the policy requirement
/cc @kubesphere/sig-console

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/170222475-1ed090c4-ad75-41ec-aed6-0bbf9dda76a6.png)

version used 
nightly-20220524
