### ISSUE TITLE
Optimize display of pod IP pool data

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#3192]
* **Mask** does not need to be displayed because **Network Segment** already shows the number of mask bits.
* **.0** for **Start IP Address** is incorrect because **.0** addresses cannot be assigned to pods.

  <img width="381" alt="image" src="https://user-images.githubusercontent.com/76198553/164955927-ae24c295-620e-4fbd-ba0c-4aca41a4a809.png">

* **256** for **Available IP addresses** is incorrect because **192.168.0.0** and **192.168.0.255** cannot be used.

  <img width="947" alt="image" src="https://user-images.githubusercontent.com/76198553/164956021-0d5997ab-6f61-4063-8dd8-1d151ef620e7.png">

/assign @harrisonliu5 @VioZhang @zheng1

**Comment by renyunkang** [comment]
Calico is fully routed, so all IP address within a Calico pool are usable as private IP addresses to assign to a workload. This means addresses commonly reserved in a L2 subnet, such as IPv4 addresses ending in .0 or .255, are perfectly okay to use.[ FAQ.](https://projectcalico.docs.tigera.io/reference/faq)

**Comment by Patrick-LuoYu** [comment]
> Calico is fully routed, so all IP address within a Calico pool are usable as private IP addresses to assign to a workload. This means addresses commonly reserved in a L2 subnet, such as IPv4 addresses ending in .0 or .255, are perfectly okay to use.[ FAQ.](https://projectcalico.docs.tigera.io/reference/faq#can-calico-containers-use-any-ip-address-within-a-pool-even-subnet-networkbroadcast-addresses)

In this case, **End IP Address** should be **.255** rather than **.254**.

<img width="358" alt="image" src="https://user-images.githubusercontent.com/76198553/165727934-4fd80de4-809c-4ac5-9ae1-e24f5ae53e86.png">

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:nightly-20220605`
![image](https://user-images.githubusercontent.com/68640256/172118543-fa0bf607-9914-473a-9582-7c494da6e0cb.png)
