### ISSUE TITLE
右下角的工具箱有时候无法进入，且无法退出

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/console#32]
KubeSphere: 2.1.1
Kubernetes: 1.13.7
**To Reproduce(复现步骤)**
1.使用GitHub上前端代码编译替换之前的前端镜像发现
2.右下角工具箱有时候无法进入到终端，报错如下图
![1210](https://user-images.githubusercontent.com/28557169/70505997-52ea7c80-1b64-11ea-8f6f-5efae406da89.png)

3.就算进入点击X按钮也无法退出，截图如下
![12102](https://user-images.githubusercontent.com/28557169/70506021-5c73e480-1b64-11ea-9516-39e749529f98.png)
4.编译的log
yarn run v1.19.1
$ rimraf dist
$ yarn build:client && yarn build:server
$ yarn lego && webpack -p --config scripts/webpack.prod.js --display errors-only
$ webpack -p --config scripts/webpack.lego.js
✔ success webpack compiled in 779ms
Hash: 0f19b80ca984b9617454
Version: webpack 4.30.0
Time: 788ms
Built at: 2019-12-10 07:51:11
   Asset       Size  Chunks                    Chunk Names
lego.css    370 KiB       0  [emitted]  [big]  lego
 lego.js  932 bytes       0  [emitted]         lego
Entrypoint lego [big] = lego.css lego.js
[0] ./src/scss/lego.theme.scss 39 bytes {0} [built]
    + 1 hidden module
Child mini-css-extract-plugin node_modules/cache-loader/dist/cjs.js!node_modules/css-loader/index.js??ref--4-2!node_modules/postcss-loader/src/index.js??postcss!node_modules/sass-loader/lib/loader.js!src/scss/lego.theme.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/cache-loader/dist/cjs.js!./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js!./src/scss/lego.theme.scss 370 KiB {0} [built]
        + 1 hidden module
Happy[jsx]: Version: 5.0.1. Threads: 3
Happy[jsx]: All set; signaling webpack to proceed.

✔ success webpack compiled in 1m 24s 913ms
Webpack Bundle Analyzer saved report to /mnt/dist/report.html

 SMP  ⏱  
General output time took 1 min, 32.53 secs

 SMP  ⏱  Plugins
WebpackBarPlugin took 17.026 secs
MiniCssExtractPlugin took 10.11 secs
OptimizeCssAssetsWebpackPlugin took 9.57 secs
BundleAnalyzerPlugin took 7.6 secs
CopyPlugin took 0.89 secs
ChunksRenamePlugin took 0.484 secs
DefinePlugin took 0.477 secs
HappyPlugin took 0.191 secs

 SMP  ⏱  Loaders
cache-loader took 1 min, 9.27 secs
  module count = 3087
happypack took 1 min, 0.825 secs
  module count = 1097
mini-css-extract-plugin, and 
cache-loader, and 
css-loader, and 
postcss-loader, and 
fast-sass-loader took 56.4 secs
  module count = 491
cache-loader, and 
css-loader, and 
postcss-loader, and 
fast-sass-loader took 51.55 secs
  module count = 491
cache-loader, and 
@svgr/webpack, and 
url-loader took 4.53 secs
  module count = 9
mini-css-extract-plugin, and 
cache-loader, and 
css-loader took 2.79 secs
  module count = 3
modules with no loaders took 1.56 secs
  module count = 5
cache-loader, and 
css-loader took 1.4 secs
  module count = 3
file-loader took 0.274 secs
  module count = 18

$ webpack -p --config scripts/webpack.server.js --display errors-only
Done in 122.89s.

**Comment by leoendless** [comment]
在开发模式下( yarn start )和本地 serve (yarn build && yarn serve)时，有同样的问题吗

**Comment by guoh1988** [comment]
@leoendless 
一样的两种情况都试了的

**Comment by justahole** [comment]
@guoh1988 正在抢修，请稍后

**Comment by zhengxh247** [comment]
更新了代码报错：

ERROR in ./src/stores/terminal.js
Module build failed (from ./node_modules/happypack/loader.js):
SyntaxError: /data/console/kubesphere-console/src/stores/terminal.js: Unexpected token (87:0)

**Comment by justahole** [comment]
@zhengxh247 打包失败？

**Comment by zhengxh247** [comment]
@justahole 是的

**Comment by justahole** [comment]
@zhengxh247 那需要另开一个issue哦，因为与本issue无关
