### ISSUE TITLE
Optimize the inform of the same name of the project.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#3204]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/41519383/165259054-f2269b48-c942-4291-95a6-69531954b1f0.png)

**Why is this needed**:
Some users may be confused about it because there is no project belongs to the workspace,and we could note the user "There has been a project of which the name is same with it,and please input another name" which in Chinese is "在其他企业空间下已存在相同名称的项目，请重新输入一个名称"
/cc @kubesphere/sig-console

**Comment by patrickluoyu** [comment]
Fixed in [3644](https://github.com/kubesphere/console/pull/3644).
