### ISSUE TITLE
kubectl connection error

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#3220]
**Describe the bug**
1、Log in to the console, click the toolbox, click kubectl, the interface is wrong
![image](https://user-images.githubusercontent.com/88183150/165879406-0cfa0239-d5e8-4119-a98b-347a591c1a60.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-alpha.2

/kind bug
/priority medium

**Comment by weili520** [comment]
I think this is not a problem, we will connect to the cluster via multiple paths, so there maybe has an error.

**Comment by jioce** [comment]
issue fixed in v3.3.0-rc.0
