### ISSUE TITLE
Hide "#" of service details in Service Topology

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3247]
**Describe the bug**

![image](https://user-images.githubusercontent.com/68640256/167232992-11f8a6d1-4c0d-40cb-b561-37e10357a38b.png)

![image](https://user-images.githubusercontent.com/68640256/167233021-77702d97-44b6-4c42-9836-0829a9d18e84.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0-alpha.2`

/priority low
/assign @kubesphere/sig-console

**Comment by weili520** [comment]
This label name  is created by the backend.

![截屏2022-05-07 09 58 14](https://user-images.githubusercontent.com/33231138/167233480-c9181c0a-14bf-4360-a7dc-5aca978c79ec.png)

**Comment by wenxin-01** [comment]
@weihongzhoulord Please hide this "#".

**Comment by mangoGoForward** [comment]
Hi,  @weili520 

Seems backend solve this problem is difficult, because ks-apiserver just forward the request and received response from `weaveworks/scope`, and the label of Pods in`ServiceMetadataTemplates`  is `# Pods`.

https://github.com/weaveworks/scope/blob/fc518cb6024d42c65ba73b2d4fab0e70a75f97d2/probe/kubernetes/reporter.go#L49-L57

**Comment by weili520** [comment]
> Hi, @weili520
> 
> Seems backend solve this problem is difficult, because ks-apiserver just forward the request and received response from `weaveworks/scope`, and the label of Pods in`ServiceMetadataTemplates` is `# Pods`.
> 
> https://github.com/weaveworks/scope/blob/fc518cb6024d42c65ba73b2d4fab0e70a75f97d2/probe/kubernetes/reporter.go#L49-L57

OK, thanks.

**Comment by wenxin-01** [comment]
issue fixed in `master`
![image](https://user-images.githubusercontent.com/68640256/168194066-63c53600-765c-410e-8a91-47c8c2a087fc.png)
