### ISSUE TITLE
Project role 'operator' permission error

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#3261]
**Describe the bug**
1、There is a project pro, click Project Settings - "Project Role, click operator, enter the role details
2、permission is empty
![image](https://user-images.githubusercontent.com/88183150/167386695-855192d2-7aef-4174-b531-45800c75221d.png)

![image](https://user-images.githubusercontent.com/88183150/167386631-eee625ed-5fdc-4681-aac7-62b829aea107.png)
3、Log in with a user associated with the operator role without corresponding permissions
![image](https://user-images.githubusercontent.com/88183150/167386987-55934b89-5b9f-4ba8-8c51-abe7d9a6676d.png)

![image](https://user-images.githubusercontent.com/88183150/167387101-ad22c8bd-6ef2-4003-8855-8d107891bcbf.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-alpha.2

/kind bug
/priority high

**Comment by jioce** [comment]
Same problem with devops engineering role "operator"
![image](https://user-images.githubusercontent.com/88183150/167388425-e0454ff5-1802-4894-914f-f1587f47e7b2.png)

**Comment by wansir** [comment]
@jioce 
Seems ks-controller-manager not working well, could you provide more information about this.

**Comment by wenxin-01** [comment]
> Same problem with devops engineering role "operator" ![image](https://user-images.githubusercontent.com/88183150/167388425-e0454ff5-1802-4894-914f-f1587f47e7b2.png)

same as https://github.com/kubesphere/ks-devops/issues/575

**Comment by wansir** [comment]
Regression bug, already fixed in https://github.com/kubesphere/ks-installer/pull/1968.

/kind need-to-verify

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/167763670-b5c0b666-5a33-4d71-8049-3e92e332c7b5.png)

![image](https://user-images.githubusercontent.com/88183150/167763737-561e722a-aeb3-467c-9e34-6f7e521dd278.png)

 Versions used
kubespheredev/ks-installer:nightly-20220509
