### ISSUE TITLE
Can't log in when setting Chinese characters as password

### ISSUE THREAD

**Issue by f10atin9** [kubesphere/console#3271]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When the user changes the last digit of the password to Chinese characters such as `P@88w0rd）` , the change will pass, but the user will not be able to log in.

**Expected behavior**
Disable Chinese characters or fix stuck at login

**Comment by harrisonliu5** [comment]
We will ban Chinese characters in passwords later.
