### ISSUE TITLE
开发前端页面没有示例账号/密码，用以查看界面修改效果

### ISSUE THREAD

**Issue by luomoyisheng** [kubesphere/console#33]
使用的是doc/development-with-docker.md进行部署的。
![image](https://user-images.githubusercontent.com/30659251/70589050-a82c9980-1c09-11ea-9a8f-5695803f3bdc.png)

**Comment by leoendless** [comment]
这个同你连接的 kubesphere cluster 一样的登录密码。
如何连接后端服务：https://github.com/kubesphere/console/blob/master/docs/access-backend.md

**Comment by luomoyisheng** [comment]
好的，谢谢，我目前已经安装您给的这个文档暴露gateway了，但是访问404，是需要还做什么操作吗？

**Comment by leoendless** [comment]
检查下集群所在主机的防火墙, 看是否有开放 gateway service 的端口

**Comment by luomoyisheng** [comment]
防火墙和selinux都是关闭的，而且这个是可以访问到的，不过是404，没找到页面。

**Comment by leoendless** [comment]
可以按一下步骤来检查问题所在
1. 确保主机上可以访问 ks 集群里的 gateway service
2. 确保你的本地环境可以访问集群所在主机的外网 ip

**Comment by luomoyisheng** [comment]
恩恩，您说的这些问题我可以确定是没问题的，但我的问题是按照文档暴露ks-apigateway后，访问
![image](https://user-images.githubusercontent.com/30659251/70686284-d59b4500-1ce6-11ea-966a-bdd2b9acbab9.png)
node_ip:30881访问到的是404页面，是我的访问路径有问题吗？

**Comment by leoendless** [comment]
后面接 /kapis/v1alpha1/configz 看看能否正常返回数据

**Comment by luomoyisheng** [comment]
![image](https://user-images.githubusercontent.com/30659251/70686963-b2719500-1ce8-11ea-97e5-bd8134673f30.png)
可以访问到的
![image](https://user-images.githubusercontent.com/30659251/70687013-df25ac80-1ce8-11ea-9e65-c8fa145584e3.png)
这个也是可以访问da到的

**Comment by leoendless** [comment]
那就可以直接写到 server/local_config.yaml 里了

**Comment by luomoyisheng** [comment]
这个我已经写进去了，并且重新yarn start了

**Comment by leoendless** [comment]
现在有什么问题呢

**Comment by luomoyisheng** [comment]
![image](https://user-images.githubusercontent.com/30659251/70687219-7985f000-1ce9-11ea-8131-89795aeb0dfc.png)k刚才图片是不是没显示出来，我重发一下

**Comment by luomoyisheng** [comment]
目前是这个问题
![image](https://user-images.githubusercontent.com/30659251/70687263-99b5af00-1ce9-11ea-8545-77c23bfd7c75.png)

**Comment by leoendless** [comment]
现在你在本地起开发环境，登录后就行了

**Comment by leoendless** [comment]
> 目前是这个问题
> ![image](https://user-images.githubusercontent.com/30659251/70687263-99b5af00-1ce9-11ea-8545-77c23bfd7c75.png)

这个是因为没有登录，api 返回401 是正常的

**Comment by luomoyisheng** [comment]
嗯嗯，谢谢，是本地起console前端的开发环境吧，起动后，我通过访问哪个url去登陆？用户名/密码是哪个？

**Comment by leoendless** [comment]
一般是 http://localhost:8000, 环境默认登录方式是
用户名：admin
密码：P@88w0rd

**Comment by luomoyisheng** [comment]
好的，非常感谢您的帮助。

**Comment by Luckywannnnng** [comment]
{ code: 401,
  statusText: 'Unauthorized',
  message: '401 Unauthorized\n' } 登录控制台报错，如何解决

**Comment by Luckywannnnng** [comment]
{ code: 401,
  statusText: 'Unauthorized',
  message: '401 Unauthorized\n' }请问登录控制台报这个如何解决

**Comment by leoendless** [comment]
> { code: 401,
> statusText: 'Unauthorized',
> message: '401 Unauthorized\n' } 登录控制台报错，如何解决

请提个新的 issue, 并补充详细的信息
