### ISSUE TITLE
App routes are not deleted after deleting the sample app

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#3331]
**Describe the bug**
1、The project pro exists, the gateway is enabled, and the sample application is deployed
2、Delete the sample application, check the application route after the deletion is successful, the application route still exists
![image](https://user-images.githubusercontent.com/88183150/171115179-509794fe-3049-459b-9cf3-8ea9a5670f82.png)

![image](https://user-images.githubusercontent.com/88183150/171115249-bb0ab0c5-fc2d-416e-babf-2e99c4d8bd50.png)

![image](https://user-images.githubusercontent.com/88183150/171115299-8880e137-400c-4b74-a021-c947cc21518f.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-rc.1

**Expected behavior**
Application routes should be removed

/kind bug
/priority low

**Comment by wenxin-01** [comment]
Issue fixed in `v3.3.0`
