### ISSUE TITLE
Create a snapshot of the storage volume, the page is not refreshed

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#3336]
**Describe the bug**
1、Go to the cluster details page, click Storage->Storage Volume Snapshot, and click Create
2、Select a storage volume, enter a name, select a snapshot type, and click Create
3、Wait for a while, the newly created snapshot is not displayed, the page is not refreshed
![image](https://user-images.githubusercontent.com/88183150/171349081-95b9ac8a-452a-4ddf-82be-c5f5d3cf3e31.png)

![image](https://user-images.githubusercontent.com/88183150/171349176-232eb67e-3fff-43cb-874f-67b5f4f9e213.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-rc.1

/kind bug
/priority low
/assign @weili520

**Comment by wenxin-01** [comment]
Issue not fixed in 'kubespheredev/ks-console:nightly-20220605'
@weili520

**Comment by jioce** [comment]
issue is fixed

version used
ks-console: weili520/project_list:latest
