### ISSUE TITLE
Remove the 'Manager' field on the 'Basic Information' page of a workspace 

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/console#3337]
The 'Manager' field on the 'Basic Information' page of a workspace is useless and should be removed. The `ws-admin` role can be assigned to any users on the 'Workspace Members' page and we do not need a duplicate feature on the 'Basic Information' page. 

<img width="1423" alt="image" src="https://user-images.githubusercontent.com/76198553/171349443-209fc84f-292e-4044-99c3-796ef637ee57.png">

<img width="673" alt="image" src="https://user-images.githubusercontent.com/76198553/171349406-ff22b24c-c9ab-4f28-ae4a-00fb0b97beee.png">

/assign @VioZhang @harrisonliu5 @wansir

**Comment by luqiaoshi** [comment]
issue fixed in `ks v3.4.0-rc.0`
![image](https://github.com/kubesphere/console/assets/24789703/bd6efcad-aa33-45a7-8e81-facdca1fc259)
