### ISSUE TITLE
Can not select image registry when create workload

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3342]
**Describe the bug**

![image](https://user-images.githubusercontent.com/68640256/171548563-753c0c50-ac5e-499b-95fa-ee4da125eafe.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.3.0-rc.1`

**Comment by exuan** [comment]
`pointer-events: none;`
clicking does not modify  `DropdownContent` css class `is-active`

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172548846-e8e4bc30-5a21-476b-bed3-2779519892de.png)

version used
ks-console:nightly-20220607
