### ISSUE TITLE
Workspace members with only the 'App Template Viewing' permission are allowed to replace Helm charts

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/console#3347]
**Describe the bug**
Workspace members with only the 'App Template Viewing' permission are allowed to replace Helm charts.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-rc.0

**To Reproduce**
1. Create a user and assign the role 'platform-regular' to the user.
2. In a workspace, create a role 'test' and assign only the permission 'App Template Viewing' to the role.
3. Invite the user to the workspace and assign the role 'test' to the user.
4. Log in as the user and go to the app template details page. The user is allowed to click 'Upload' and change the Helm chart of an app version.

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/76198553/172126080-9e6c5172-6e0f-4b98-ab6b-3b55ce813710.png">

**Expected behavior**
Workspace members with only the 'App Template Viewing' permission should not be allowed to replace Helm charts.

/assign @harrisonliu5 @wansir

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`
