### ISSUE TITLE
The prompt message is wrong when the end time is not selected

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3350]
**Describe the bug**

![image](https://user-images.githubusercontent.com/68640256/172305683-ea40c07e-60ac-4dd1-b4e8-94b863880ad9.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0-rc.1`
Kubernetes: (If KubeSphere installer used, you can skip this)

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/172572808-c2b2d32c-a7fe-43e2-9676-6a672d56a2f5.png)

version used
ks-console:maste
