### ISSUE TITLE
Display a prompt message when a user without continuous deployment permissions accesses the CD through the url

### ISSUE THREAD

**Issue by wenxinll** [kubesphere/console#3354]
**Describe the bug**

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0-rc.1`

![image](https://user-images.githubusercontent.com/68640256/172347012-9974a940-1047-432d-8252-acd75a382169.png)

![image](https://user-images.githubusercontent.com/68640256/172347840-b950228c-ad9a-457a-907e-a404d13092e8.png)

**Comment by chilianyi** [comment]
<img width="1437" alt="截屏2023-05-24 18 05 53" src="https://github.com/kubesphere/console/assets/5917832/f88d573a-dec0-49f5-8481-d015c253dd5b">

**Comment by wenxinll** [comment]
`kse v3.4.0`
在没有查看持续部署时，前端没有请求接口 ‘/kapis/gitops.kubesphere.io/v1alpha1/namespaces/dev7q6pd/applications?limit=10’，故不会显示报错信息。 符合预期
