### ISSUE TITLE
incorrect parameters were created by glusterfs storageclass 

### ISSUE THREAD

**Issue by stoneshi-yunify** [kubesphere/console#3362]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
the glusterfs storageclass created on console has incorrect parameters (field names).

created: 
![image](https://user-images.githubusercontent.com/70880165/173015426-0b7bc856-c206-4ad7-aaf9-5f85681b781b.png)

expected:
- https://kubernetes.io/docs/concepts/storage/storage-classes/#glusterfs

there is no underline in each field name.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.3
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**
- go to storage -> storage class
- create storage class and choose glusterfs
- input some values then click submit

**Expected behavior**
create correct storageclass

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.0
![image](https://user-images.githubusercontent.com/88183150/184832229-00f5d642-d439-40d4-8d0b-170dbf12f9c2.png)
