### ISSUE TITLE
When enabled multi-cluster, ks-console display the info of `default` cluster.

### ISSUE THREAD

**Issue by xyz-li** [kubesphere/console#3365]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When enabled multi-cluster, ks-console display the info of `default` cluster. But the `default` cluster not exists. There is just one `host` cluster.
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/6263928/173037292-43e1680a-0e5c-4ff3-8312-0826e5cb0229.png">
<img width="1664" alt="image" src="https://user-images.githubusercontent.com/6263928/173037382-879e72eb-2fb0-4050-a1f5-69fa91dcc27a.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-rc.2
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**
1.  Setup a cluster with multi-cluster disabled.
2.  View the page /clusters/default/overview
3.  Enable the option multi-cluster. 
4. Refresh current page and login.

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`
