### ISSUE TITLE
No traffic show even the API response has the data

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#3367]
**Describe the bug**
As I mentioned, you can see the following screenshot.

![image](https://user-images.githubusercontent.com/1450685/173229372-9ff65e47-a4a5-4ce0-bf5d-6c67365f06e5.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-rc.2

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Enable the Weave Scope feature
2. Create a service
3. Visit the service address
4. See the traffic

**Expected behavior**
The UI could show the corresponding data.

**Comment by jioce** [comment]
Enabling the service topology will consume a lot of resources. Therefore, it is not recommended to enable service topology by default.
If you need it, you can start the service topology in the following ways:
● Enable the weave-scope topology by editing the daemonset weave-scope-agent container args. (delete - '--probe.processes=false')
● Remove read-only access to volumeMounts.(delete readOnly: true)

**Comment by jioce** [comment]
After opening the service topology map, there is traffic displayed
![image](https://user-images.githubusercontent.com/88183150/173731400-3b333d4d-c7a8-4e5c-bf5e-5c992d6cc61a.png)

version used 
kubesphere: v3.3.0-rc.2

**Comment by LinuxSuRen** [comment]
Got you. So, I guess this is not a bug. Right? Please feel free to close this issue if it's.

**Comment by wenxin-01** [comment]
I will close this issue. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/68640256/173752382-485de8bf-c41f-4fd1-9e6e-5d29d47c427c.png">
