### ISSUE TITLE
Incorrect column width

### ISSUE THREAD

**Issue by Patrick-LuoYu** [kubesphere/console#3376]
The column width is incorrect on 14-inch display.

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/76198553/173326424-16ffbf21-3def-4d52-8695-b66f9a83d6d0.png">

/assign @harrisonliu5

**Comment by jioce** [comment]
issue is fixed
![image](https://user-images.githubusercontent.com/88183150/174558521-c6b6abfc-58d9-4873-a0bb-9a5c218f6bd4.png)

version used
kubesphere: v3.3.0-rc.3
