### ISSUE TITLE
The user's login password can be seen in the front-end code

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3399]
**Describe the bug**

![image](https://user-images.githubusercontent.com/68640256/174514599-1ade28fd-884e-400b-bd87-687012d73590.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0-rc.2`

**Comment by enraiha0307** [comment]
Hi, I was searching for issues, saw this one, and searched on the internet. Apparently, it's not possible to hide field value in the view source, but the workaround suggested is that we encrypt the password using MD5 or SHA hash. 
https://stackoverflow.com/questions/30013032/prevent-user-to-find-password-through-firebug-chrome-dev-tools

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`
