### ISSUE TITLE
Storage class auto-scaling settings not translated

### ISSUE THREAD

**Issue by jioce** [kubesphere/console#3403]
**Describe the bug**
1、There is storage class ss, set automatic extension, click OK, the page shows that some setting items are not translated
![image](https://user-images.githubusercontent.com/88183150/174741793-da827422-9bdb-4ad9-b596-3b9f6d8f8aa9.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0-rc.3

/kind bug
/priority high
/assign @Patrick-LuoYu

**Comment by Patrick-LuoYu** [comment]
Fixed in PR [3404](https://github.com/kubesphere/console/pull/3404).

**Comment by jioce** [comment]
issue is fixed 
![image](https://user-images.githubusercontent.com/88183150/174925797-bf3aae71-a507-4469-abf9-afbeebbd5e8f.png)

version used
kubespheredev/ks-console: master
