### ISSUE TITLE
Can not save without 'Select Specific Keys'

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3417]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68640256/176064278-5d513971-66e3-4613-b2a9-c8e7b4b5f977.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.3.0-rc.3`

**Comment by harrisonliu5** [comment]
fixed in https://github.com/kubesphere/console/pull/3416

**Comment by wenxin-01** [comment]
issue fixed in `ks v3.3.1-rc.0`
