### ISSUE TITLE
About the status service volumeClaimTemplates shows an error

### ISSUE THREAD

**Issue by yuweni99** [kubesphere/console#3418]
kubesphere version: 3.3.0
Error details: When the Status service uses volumeClaimTemplates, viewing does not display correctly after creation is done
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/41253364/176336270-31e3a69d-7597-42e0-81c7-4b244270e832.png">
<img width="990" alt="image" src="https://user-images.githubusercontent.com/41253364/176336311-0c7b9ad1-c315-44cc-a8d2-1a20d23c057e.png">

**Comment by harrisonliu5** [comment]
This issue has explains this problem https://github.com/kubesphere/kubesphere/issues/4196 .

**Comment by wenxin-01** [comment]
Issue fixed in `ks v3.3.1-rc.0`
![image](https://user-images.githubusercontent.com/68640256/185358928-2ed23e7b-78a6-491b-8b82-73b1a60b469f.png)
![image](https://user-images.githubusercontent.com/68640256/185359102-bc4a74ea-2384-4c78-a278-e29ca17c8144.png)
