### ISSUE TITLE
Network Policys-Spelling Issue

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#342]
![图片](https://user-images.githubusercontent.com/65327072/83855290-71fc4c80-a74a-11ea-8ff4-ee530a7fbc78.png)
It seems that the spelling issue cannot be fixed directly. "Network Policys" cannot be found in the console directory,

**Comment by Sherlock113** [comment]
@leoendless Please have a look at this when you are available. Thx.

**Comment by rayzhou2017** [comment]
verified
