### ISSUE TITLE
Incorrect app repository sync interval unit

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere/console#3421]
**Describe the bug**
As you can see from the following screenshot. The app repository sync interval unit is incorrect.

![image](https://user-images.githubusercontent.com/1450685/177112339-cb42efe9-b6c0-4a0e-997d-dad185fe4004.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.3.0

**Environment**
This is not an environmental issue.

**To Reproduce**
1. Go to `App Management->App Repository` page
2. Try to add a repository
3. Type the value of `Sync Interval` to be `3`
4. See the errors

**Expected behavior**
Provide a reasonable time unit.

**Comment by harrisonliu5** [comment]
This is not a problem that maybe somebody enters a value like 5400 seconds
