### ISSUE TITLE
The create container state and event state are not synchronized

### ISSUE THREAD

**Issue by yinmin2020** [kubesphere/console#3424]
**Describe the Bug**
After the container is created, the command line is running properly, and the UI is still in the container creation state

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/65068467/177712006-7cd2f702-2f98-455b-87d6-740fabcb7b5e.png)

**Versions Used**
KubeSphere: 3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration:

For example: CentOS 7.5 / 3 masters:  8cpu/8g; 3 nodes: 8cpu/16g
(and other info are welcomed to help us debugging)

**How To Reproduce**
1. Create a container
2. Viewing the event is complete
3. The Container Group interface displays creating containers

**Expected behavior**
You want the UI to be consistent with the event state

**Comment by weili520** [comment]
I can't repreduced this problem in `v3.3.1`, the websoket for this deployment is works well.

**Comment by wenxin-01** [comment]
I can't repreduced this problem in `v3.3.1` and `kubespheredev`
