### ISSUE TITLE
中文语言文件翻译错误

### ISSUE THREAD

**Issue by blacklad** [kubesphere/console#3429]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
中文语言文件翻译不正确  ，文件：/locales/zh/l10n-multiclusterProjects-applicationWorkloads-deployments-list.js
NVIDIA_COM_GPU: '无效的GPU'

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:
Kubernetes: (If KubeSphere installer used, you can skip this)
3.3.0

**Environment**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**

**Expected behavior**

**Comment by weili520** [comment]
It has bee resolved it in here: [crowdin](https://crowdin.com/translate/kubesphere/2983/en-zhcn?filter=basic&value=0).

**Comment by harrisonliu5** [comment]
This issue is been fixed
