### ISSUE TITLE
 can not input & edit chinese in new secret item'data section.

### ISSUE THREAD

**Issue by isyes** [kubesphere/console#3437]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
 can not input & edit chinese in new secret item'data section.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.2.0

**Environment**

**To Reproduce**
1. Go to 'Secrets'
2. Click on 'Create'
3. Add item & input chinese data section. 
4. save, but  no response, See browser's console error.

**Expected behavior**
Save the secret item success.

**Comment by moweiwei** [comment]
![1](https://user-images.githubusercontent.com/40727882/191156511-09c05fcc-ea92-43d0-b4a2-e1ea2b49d398.png)
/assign moweiwei

**Comment by wenxin-01** [comment]
Issue fixed in `ks v3.3.1-rc.3` 
![image](https://user-images.githubusercontent.com/68640256/194757056-b0d08730-68c2-4c1c-8923-3e0c70a09465.png)
