### ISSUE TITLE
When you do not select key or path to save, there is no prompt information on the page.

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3465]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68640256/181156315-51559194-5118-4ee3-acfc-fea56286fb11.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:   `v3.3.0`

**Expected behavior**
`Prompt to enter key or path.`

**Comment by wenxin-01** [comment]
issue not fixed in `ks v3.3.1-rc.0`
@weili520

**Comment by wenxin-01** [comment]
Text not showing. @harrisonliu5 
![image](https://user-images.githubusercontent.com/68640256/187109692-dfecb57e-fc18-4825-b0e0-fe6250ae02a1.png)

**Comment by wenxin-01** [comment]
@patrickluoyu

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.2
![image](https://user-images.githubusercontent.com/88183150/190584667-44604433-f846-487a-8945-e12e1cf838b1.png)
