### ISSUE TITLE
登陆前端显示用户名和密码错误

### ISSUE THREAD

**Issue by luomoyisheng** [kubesphere/console#35]
我暴露gateway端口后，不小心获取了token
![image](https://user-images.githubusercontent.com/30659251/70692842-329ef700-1cf7-11ea-9ade-7b9047cef25c.png)，我现在访问http://localhost:8000/使用默认的用户名和密码登陆显示账号和密码错误，我该怎么操作。

**Comment by minghaoye** [comment]
看一下本地terminal的报错

**Comment by luomoyisheng** [comment]
![image](https://user-images.githubusercontent.com/30659251/70704119-5587d600-1d0c-11ea-96c8-34a1411d8351.png)

**Comment by luomoyisheng** [comment]
{ code: 401,
  message: 'LDAP Result Code 49 "Invalid Credentials": ',
  statusText: 'Unauthorized' }

**Comment by minghaoye** [comment]
再次确认下账号密码

**Comment by luomoyisheng** [comment]
账号密码是使用的默认的，
![image](https://user-images.githubusercontent.com/30659251/70704468-02625300-1d0d-11ea-8d02-696a6f08bf03.png)我是执行完make dev访问的。是不是因为这是开发环境，所以没有账号和密码。

**Comment by minghaoye** [comment]
有账号密码的，在线版可以登录么

**Comment by luomoyisheng** [comment]
我试一下吧，因为我们这边想开发前端，所以想使用的dev环境来开发

**Comment by luomoyisheng** [comment]
在线的没问题

**Comment by leoendless** [comment]
开发问题的化可以参考下这个https://github.com/kubesphere/console/issues/33

**Comment by luomoyisheng** [comment]
好的，谢谢
