### ISSUE TITLE
Does the cluster/project gateway monitor display the wrong unit?

### ISSUE THREAD

**Issue by shenhonglei** [kubesphere/console#3537]
**Describe the bug**
Are the units of Average Latency, P50 Latency, P95 Latency, and P99 Latency of the cluster gateway correct? Help verify and correct

For UI issues please also add a screenshot that shows the issue.
<img width="1436" alt="1" src="https://user-images.githubusercontent.com/20896372/182806629-bce19599-7754-4588-b1ca-afa246a045d1.png">
**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.2.0-9+8e88147a44197e

is a bug discovered by a customer during stress testing

**Comment by shenhonglei** [comment]
Thanks to @iawia002  for helping to verify, please find the corresponding developer to help fix it in time

**Comment by iawia002** [comment]
Ref to https://github.com/kubesphere/kubesphere/blob/master/pkg/simple/client/monitoring/prometheus/promql.go#L178-L181, the units of these metrics should be **seconds**, not **milliseconds**.

cc @harrisonliu5
