### ISSUE TITLE
please be compatible with browser edge, especially when using the toolbox feature

### ISSUE THREAD

**Issue by shenhonglei** [kubesphere/console#3552]
**What would you like to be added**:

Please be compatible with browser edge
The problems found so far are as follows:
1. The toolbox is in low resolution and cannot be scrolled
2. When the Container Log Search in the analysis tool is used, it seems that there is a problem with the scroll bar displayed in the front-end log, and the screen will keep flickering.
![1](https://user-images.githubusercontent.com/20896372/183554620-d272a92f-988b-4654-b022-301e6257e783.png)
![2](https://user-images.githubusercontent.com/20896372/183554672-9a04f05d-1f24-465e-bd4f-cda1145d5713.png)

**Why is this needed**:
Customers will often use edge 

browsers at work, as important as chrome

**Comment by yazhouio** [comment]
![动画](https://user-images.githubusercontent.com/17949154/211475692-bb2add09-8159-4caf-aa2b-d34c573c6643.gif)
No scrollbar flicker detected

**Comment by wenxin-01** [comment]
No scrollbar flicker detected in `kubespheredev/ks-console:release-3.3`
