### ISSUE TITLE
Logging setting shows in the platform settings for minimal installation

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#356]
The logging setting should not show in the minimal installation
![Screen Shot 2020-06-08 at 9 28 50 AM](https://user-images.githubusercontent.com/28859385/83985204-d0077a80-a96a-11ea-891f-904c873fd9e5.png)

**Comment by rayzhou2017** [comment]
I think it should work like this way: @leoendless @benjaminhuo 
1. The logging setting should show for user to configure the external es.
2. Once the es is configured, the toolbox should show the logging search tool.

**Comment by benjaminhuo** [comment]
ES consumes the most resource of logging component. 
It's ok for logging component to install fluentbit only and show the log setting UI.
@huanggze , by default input and filter plugin has been installed for fluentbit  and no output plugin, right? And is it possible to find out if es output plugin exists and provide an API for frontend ?

**Comment by rayzhou2017** [comment]
verified
