### ISSUE TITLE
Should not use same path in 'Select specific keys'

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3567]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68640256/185063803-539e433d-314b-4768-b36f-dd782f84897c.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.3.1-rc.0`

**Expected behavior**
Prompt `The mount path is already in use. Please enter another mount path.`

**Comment by wenxin-01** [comment]
Hint text not showing in `ks3.3.1-rc.1`. @patrickluoyu 
![image](https://user-images.githubusercontent.com/68640256/187115644-155e9a74-40d3-407c-8f64-efae32a2db5e.png)

**Comment by patrickluoyu** [comment]
Fixed in [3644](https://github.com/kubesphere/console/pull/3644).

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.2
![image](https://user-images.githubusercontent.com/88183150/190582289-9745dc50-fb24-4167-b0a0-a6282d854494.png)
