### ISSUE TITLE
When setting the route, the cancel button will save the setting content

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3598]
**Describe the bug**
After edit routing rules, click on 'cancel'. The content will be saved.

![image](https://user-images.githubusercontent.com/68640256/186092903-564050f2-e5ed-4298-93ce-c4597b7d200d.png)
![image](https://user-images.githubusercontent.com/68640256/186092938-98e62e64-8b36-49fb-8c76-0dfe817561b7.png)
![image](https://user-images.githubusercontent.com/68640256/186092980-29d24597-5b95-4acb-9a95-356e822f80fd.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.3.0`

**Comment by wenxin-01** [comment]
When you click Cancel, the modified content will not be saved, but when you create it(or click previous and click next), the modified content is used.
![image](https://user-images.githubusercontent.com/68640256/187111867-950e1d1e-c4f0-4851-9a39-217ade2f054d.png)

**Comment by wenxin-01** [comment]
@harrisonliu5

**Comment by weili520** [comment]
It's merged two days ago.

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.2
