### ISSUE TITLE
edit role resource authorization

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#361]
In Chrome, clicking the checkbox does not work, but it works to click on the whole box.
<img width="1187" alt="Screen Shot 2020-06-08 at 10 18 43 AM" src="https://user-images.githubusercontent.com/28859385/83987085-a1d96900-a971-11ea-87a8-69508e98a2e8.png">

**Comment by rayzhou2017** [comment]
Also the edit access should be dependent on the view access.

**Comment by leoendless** [comment]
The dependencies missing in global role settings. 
@wansir

**Comment by rayzhou2017** [comment]
what about the click area problem as describe above?

**Comment by rayzhou2017** [comment]
verified
