### ISSUE TITLE
Hide the 'Edit kubeconfig' option for clusters added over proxy

### ISSUE THREAD

**Issue by patrickluoyu** [kubesphere/console#3611]
kubeconfig is not required when a cluster is added over proxy. Therefore, 'Edit kubeconfig' should not be displayed for clusters added over proxy.

<img width="1412" alt="image" src="https://user-images.githubusercontent.com/76198553/186629579-f48c399b-31ab-41d0-b034-f7ba7c4bf8f0.png">

/assign @harrisonliu5

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.1
![image](https://user-images.githubusercontent.com/88183150/187178187-eb34878b-bb17-4715-8787-dd429b6220aa.png)
