### ISSUE TITLE
The list ofconfigmap is not displayed correctly

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3638]
**Describe the bug**
![image](https://user-images.githubusercontent.com/68640256/187119073-6a6a2f1c-1f13-4f64-960b-a2e2d7a94dac.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.3.1rc.1`

browser: Safari 16.0

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.2
![image](https://user-images.githubusercontent.com/88183150/190552073-1651a249-8c70-464e-ac75-e87a69994466.png)
