### ISSUE TITLE
Custom Resources page cannot set pagination

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3640]
**Describe the bug**
1、Default number per page shows error.
2、Can not set the number of per page.

![image](https://user-images.githubusercontent.com/68640256/187148678-03355ad2-b3f4-477f-bc69-c5c0323c7884.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.3.1-rc.1`

**Comment by jioce** [comment]
issue is fixed in v3.3.1-rc.2
![image](https://user-images.githubusercontent.com/88183150/190576437-0c99df04-8a14-46b6-8b9f-ec56a4e630f5.png)
