### ISSUE TITLE
Optimize the description of the application.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#3651]
**What would you like to be added**:

- [ ] Optimize the description of the application which the svc belongs to and if the svc doesn't belong to any app there should be NULL.
- [ ] There should be "charts" showed at the Apps list and rather not the "App".

**Why is this needed**:
![image](https://user-images.githubusercontent.com/41519383/188117511-744ce52f-43c4-4b5a-9e2c-6bc34a7922bc.png)
![image](https://user-images.githubusercontent.com/41519383/188117623-99e25550-0f11-448e-8458-769100c796e7.png)

**Comment by wenxin-01** [comment]
It is recommended to increase the jump from the service page to the application.
![image](https://user-images.githubusercontent.com/68640256/188120230-9004e2f6-7467-42b0-974b-6b72a911aaa8.png)

**Comment by wenxin-01** [comment]
When creating the service, no app is specified, the front end should not pass this parameter `app: "xxx"`.
![image](https://user-images.githubusercontent.com/68640256/188120906-49334d3d-6d34-4ddf-868e-8049762ab387.png)

**Comment by harrisonliu5** [comment]
> It is recommended to increase the jump from the service page to the application. ![image](https://user-images.githubusercontent.com/68640256/188120230-9004e2f6-7467-42b0-974b-6b72a911aaa8.png)

can not jump from the service page to the application, because there is no type data of the application in service data.

**Comment by wenxin-01** [comment]
The name of sample app did not display. @harrisonliu5 
![image](https://user-images.githubusercontent.com/68640256/191151613-ee39196d-8b31-46e5-9fa2-035375d8c642.png)

**Comment by wenxin-01** [comment]
> The name of sample app did not display. @harrisonliu5 ![image](https://user-images.githubusercontent.com/68640256/191151613-ee39196d-8b31-46e5-9fa2-035375d8c642.png)

Issue fixed in `kubespheredev/ks-console:nightly-20221009`
