### ISSUE TITLE
User does not enter the page when logged out last time

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#379]

**Comment by rayzhou2017** [comment]
> User will enter the dashboard if they log in after they log out manually. But if the page directed to the login page because of token expired, the last page will be remembered.

You mean if user log out manually, it will log the user in the overview/landing page? On the other hand, if session times out, the log the user into the last visited page. Am I right?

**Comment by leoendless** [comment]
Yes

**Comment by leoendless** [comment]
Does the problem fix?

**Comment by rayzhou2017** [comment]
verified
