### ISSUE TITLE
Cluster visibility

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#383]
The column title should be `user` or `username` not `name` which is too general. I am confused at first sight.
<img width="1010" alt="Screen Shot 2020-06-08 at 4 46 38 PM" src="https://user-images.githubusercontent.com/28859385/84010933-f4ce1300-a9a7-11ea-9661-75b97b6fb21d.png">

**Comment by Carlosfengv** [comment]
名称(name) => 企业空间(workspace)

**Comment by rayzhou2017** [comment]
> 名称(name) => 企业空间(workspace)

The cluster is assigned to workspace? not to user?

**Comment by rayzhou2017** [comment]
OK, I got it. So the name needs to change to avoid confusion.

**Comment by rayzhou2017** [comment]
If it is that case, wouldn't it better to show the admin of the workspace in the list?

**Comment by Carlosfengv** [comment]
A cluster can add a user as the administrator of a cluster, This user can then authorize the cluster to the required workspace.

**Comment by rayzhou2017** [comment]
verified
