### ISSUE TITLE
Email server configuration moved to cluster?

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#384]
It is moved from platform setting to the cluster setting? What's the reason?
<img width="246" alt="Screen Shot 2020-06-08 at 4 53 23 PM" src="https://user-images.githubusercontent.com/28859385/84011449-b6852380-a9a8-11ea-8886-c6def83b7190.png">

**Comment by Carlosfengv** [comment]
The back end does not implement platform-level Settings
