### ISSUE TITLE
wrong password prompt

### ISSUE THREAD

**Issue by wenxin-01** [kubesphere/console#3916]
**Describe the bug**
<img width="833" alt="image" src="https://user-images.githubusercontent.com/68640256/198525649-b9753124-6ef4-42c8-ba9b-36a7d144746c.png">

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/68640256/198525699-201dced6-f73c-4217-bc8d-438b0dbcf588.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  `v3.3.1`

**Expected behavior**
Contain at latest 8 characters

**Comment by wenxin-01** [comment]
> Hi, is this bug still there? Because just now I installed kubesphere on my system and there it says Contain at latest 8 characters. ![Kubesphere](https://user-images.githubusercontent.com/26249973/206902476-293f88dd-c73f-43ea-a773-178fdb336604.png)

Hi, what's your version of kubesphere?

**Comment by enraiha0307** [comment]
Its v3.3.1

**Comment by enraiha0307** [comment]
ok, thanks

**Comment by VioZhang** [comment]
fixed
