### ISSUE TITLE
There are some entries to be translated。

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#4042]
`SERVICE_MONITORING_EXPORTER (EXPORTER_SERVICE_PORTS)`
`SCRAPE_INTERVAL_MIN`

version: `kse v3.3.1`

![image](https://user-images.githubusercontent.com/68640256/209777258-dc4625cd-c7e7-4d17-9121-6afa79818b7d.png)

`STORAGE_CLASSS`

![image](https://user-images.githubusercontent.com/68640256/210495530-704d02b4-4a51-46f3-9eb4-f98727395501.png)

**Comment by Bettygogo2021** [comment]
@harrisonliu5 Liu Xin, as these entries are hardcoded, pls help me put the correct entries, and then I will translate them ASAP. 3ks

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:release-3.3`
![image](https://user-images.githubusercontent.com/68640256/212612040-c174fddf-9baa-4551-a5e0-6f5ed4478b13.png)
![image](https://user-images.githubusercontent.com/68640256/212612366-a50ee77d-b28e-4f34-aa49-7be608366eba.png)
