### ISSUE TITLE
Show the cluster where the system-woekspace is.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#4043]
![image](https://user-images.githubusercontent.com/41519383/199185051-12701968-cbe6-4ae4-8a3c-c312f5364679.png)

**Comment by VioZhang** [comment]
设计图 https://www.figma.com/file/q3urPSh20JziH7RYn8v8Ox/KubeSphere-3.3.0?node-id=2943%3A432632&t=6X5rECHWA07tl21a-4

**Comment by wenxin-01** [comment]
Issue not fixed in `ks-consoe v3.3.2-rc.0`
![image](https://user-images.githubusercontent.com/68640256/215418567-741eee7f-1a78-4e20-b9d7-b7b4c5756a7f.png)

**Comment by wenxin-01** [comment]
The Chinese environment is displayed as English in `kubespheredev/ks-console:nightly-20230131`

![image](https://user-images.githubusercontent.com/68640256/215964905-637ffee4-885e-4fbc-8c9d-dc102c53857f.png)

**Comment by wenxin-01** [comment]
Issue fixed in `kubespheredev/ks-console:v3.3.2-rc.2`

![image](https://user-images.githubusercontent.com/68640256/216241568-20f81a00-a912-4a00-8912-c324b90906f2.png)
