### ISSUE TITLE
Limit the length of cluster names.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#4058]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/41519383/212287839-660a091f-eecf-46ca-9838-105f5aa1ca36.png)

**Why is this needed**:

**Comment by wenxin-01** [comment]
Issue fixed in  `kubespheredev/ks-console:release-3.3`


![Image](https://user-images.githubusercontent.com/68640256/212619211-e5ce8f8d-5547-46dc-9d56-d81024a5e5d1.png)
