### ISSUE TITLE
No Login Record Displayed

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#408]
**Describe the bug**

I created my account last week and used it to log in many times. However, I could not see any record here. For "Last Login Time", it says "Not Logged in yet". I also checked other accounts and found the same thing.

![图片](https://user-images.githubusercontent.com/65327072/84457722-f93f4800-ac95-11ea-9137-4072bcdef4e7.png)

**Environment**

Development Environment

**To Reproduce**
1. Go to 'Workbench'
2. Click on 'Accounts'
3. Select any account
4. Check the login record and you will get nothing

**Comment by rayzhou2017** [comment]
same as #495

**Comment by rayzhou2017** [comment]
duplicated with #495
