### ISSUE TITLE
Add a note of  kubesphere.io/imagepullsecrets when applying yaml.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#4080]
**What would you like to be added**:
![7cd4ebeb8be0216e7003d6a1cb204b1](https://user-images.githubusercontent.com/41519383/215432725-8e7e371d-44f9-40e4-adc9-32e79969f456.png)
**Why is this needed**:
KubeSphere uses kubesphere.io/imagepullsecrets to associate with the secret and if users want to use the yaml we should add a note of it.

**Comment by Bettygogo2021** [comment]
Resolved in https://github.com/kubesphere/website/pull/2819. Pls help me review it. 3ks

**Comment by wenxin-01** [comment]
Fixed
