### ISSUE TITLE
进入项目的某个服务页面不显示

### ISSUE THREAD

**Issue by fangyajun** [kubesphere/console#4093]
![image](https://user-images.githubusercontent.com/43130239/219314642-1626942c-3f49-4a14-b39e-a85e3dc414d7.png)

**Comment by fangyajun** [comment]
![image](https://user-images.githubusercontent.com/43130239/219317392-fd20131d-9412-49c5-8d7f-c6cadcf4ae2b.png)

**Comment by wenxinll** [comment]
在ks3.3.1 已经修复了
https://github.com/kubesphere/console/pull/3455/files
