### ISSUE TITLE
进入企业空间的项目/服务/资源状态 点击更多操作，点击编辑外网访问/编辑配置文件 无法打开对话框

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/console#41]
KubeSphere: 2.1.0
Kubernetes: 1.13.7
To Reproduce(复现步骤)
1.使用GitHub上前端代码编译替换之前的前端镜像发现
2.进入企业空间的项目/服务/资源状态 点击更多操作，点击编辑外网访问/编辑配置文件 无法打开对话框
![鏈嶅姟](https://user-images.githubusercontent.com/28557169/71234043-7961a200-2332-11ea-9080-8605ac4f4f62.png)

**Comment by leoendless** [comment]
编译完镜像后可以使用 ./docker-run 脚本再本地用 docker 运行。看下页面是否正常吧

**Comment by leoendless** [comment]
请问下你的 ks-console 是多副本的吗，每个副本的 container image 是一样的吗，建议尝试新的镜像时，重新起一个新的 deployment 和 service，不要覆盖原有稳定版 的 ks-console 服务。

**Comment by guoh1988** [comment]
@leoendless 
.编译的log
yarn run v1.19.1
$ rimraf dist
$ yarn build:client && yarn build:server
$ yarn lego && webpack -p --config scripts/webpack.prod.js --display errors-only
$ webpack -p --config scripts/webpack.lego.js
✔ success webpack compiled in 779ms
Hash: 0f19b80ca984b9617454
Version: webpack 4.30.0
Time: 788ms
Built at: 2019-12-10 07:51:11
Asset Size Chunks Chunk Names
lego.css 370 KiB 0 [emitted] [big] lego
lego.js 932 bytes 0 [emitted] lego
Entrypoint lego [big] = lego.css lego.js
[0] ./src/scss/lego.theme.scss 39 bytes {0} [built]
+ 1 hidden module
Child mini-css-extract-plugin node_modules/cache-loader/dist/cjs.js!node_modules/css-loader/index.js??ref--4-2!node_modules/postcss-loader/src/index.js??postcss!node_modules/sass-loader/lib/loader.js!src/scss/lego.theme.scss:
Entrypoint mini-css-extract-plugin = *
[0] ./node_modules/cache-loader/dist/cjs.js!./node_modules/css-loader??ref--4-2!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js!./src/scss/lego.theme.scss 370 KiB {0} [built]
+ 1 hidden module
Happy[jsx]: Version: 5.0.1. Threads: 3
Happy[jsx]: All set; signaling webpack to proceed.

✔ success webpack compiled in 1m 24s 913ms
Webpack Bundle Analyzer saved report to /mnt/dist/report.html

SMP stopwatch
General output time took 1 min, 32.53 secs

SMP stopwatch Plugins
WebpackBarPlugin took 17.026 secs
MiniCssExtractPlugin took 10.11 secs
OptimizeCssAssetsWebpackPlugin took 9.57 secs
BundleAnalyzerPlugin took 7.6 secs
CopyPlugin took 0.89 secs
ChunksRenamePlugin took 0.484 secs
DefinePlugin took 0.477 secs
HappyPlugin took 0.191 secs

SMP stopwatch Loaders
cache-loader took 1 min, 9.27 secs
module count = 3087
happypack took 1 min, 0.825 secs
module count = 1097
mini-css-extract-plugin, and
cache-loader, and
css-loader, and
postcss-loader, and
fast-sass-loader took 56.4 secs
module count = 491
cache-loader, and
css-loader, and
postcss-loader, and
fast-sass-loader took 51.55 secs
module count = 491
cache-loader, and
@svgr/webpack, and
url-loader took 4.53 secs
module count = 9
mini-css-extract-plugin, and
cache-loader, and
css-loader took 2.79 secs
module count = 3
modules with no loaders took 1.56 secs
module count = 5
cache-loader, and
css-loader took 1.4 secs
module count = 3
file-loader took 0.274 secs
module count = 18

$ webpack -p --config scripts/webpack.server.js --display errors-only
Done in 122.89s.

**Comment by guoh1988** [comment]
@leoendless 
在开发模式下( yarn start )和本地 serve (yarn build && yarn serve)时，都有同样的问题，我这边使用的是单管理节点，不存在镜像不一样的情况

**Comment by leoendless** [comment]
麻烦贴一下 yarn start 时页面的报错吧

**Comment by guoh1988** [comment]
r: _this$props$options$f is undefined[详细了解]  common.js%20line%202967%20%3E%20eval:83:11
	BtnGroup/_this.handleMoreClick webpack:///./src/core/containers/Base/Detail/BaseInfo/BtnGroup/index.jsx?:83:11
	Menu/< webpack:///./node_modules/@pitrix/lego-ui/lib/components/Menu/Menu.js?:97:9
	MenuItem/< webpack:///./node_modules/@pitrix/lego-ui/lib/components/Menu/MenuItem.js?:81:7
	callCallback webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:149:9
	invokeGuardedCallbackDev webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:199:7
	invokeGuardedCallback webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:256:3
	invokeGuardedCallbackAndCatchFirstError webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:270:3
	executeDispatch webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:561:3
	executeDispatchesInOrder webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:580:7
	executeDispatchesAndRelease webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:680:5
	executeDispatchesAndReleaseTopLevel webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:688:10
	forEachAccumulated webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:662:5
	runEventsInBatch webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:816:3
	runExtractedEventsInBatch webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:824:3
	handleTopLevel webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:4820:5
	batchedUpdates$1 webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18932:12
	batchedUpdates webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:2150:12
	dispatchEvent webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:4899:5
	interactiveUpdates$1 webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18987:12
	interactiveUpdates webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:2169:10
	dispatchInteractiveEvent webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:4876:3
	bound dispatchInteractiveEvent self-hosted:957:17
Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.  vendor.js:210:19
	invokeGuardedCallbackDev webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:210:19
	invokeGuardedCallback webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:256:3
	invokeGuardedCallbackAndCatchFirstError webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:270:3
	executeDispatch webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:561:3
	executeDispatchesInOrder webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:580:7
	executeDispatchesAndRelease webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:680:5
	executeDispatchesAndReleaseTopLevel webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:688:10
	forEachAccumulated webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:662:5
	runEventsInBatch webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:816:3
	runExtractedEventsInBatch webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:824:3
	handleTopLevel webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:4820:5
	batchedUpdates$1 webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18932:12
	batchedUpdates webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:2150:12
	dispatchEvent webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:4899:5
	interactiveUpdates$1 webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:18987:12
	interactiveUpdates webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:2169:10
	dispatchInteractiveEvent webpack:///./node_modules/react-dom/cjs/react-dom.development.js?:4876:3
	bound dispatchInteractiveEvent self-hosted:957:17
