### ISSUE TITLE
Can't config node list.

### ISSUE THREAD

**Issue by VioZhang** [kubesphere/console#4171]
For UI issues please also add a screenshot that shows the issue.

version:3.4.0

https://github.com/kubesphere/console/assets/41519383/41f017da-b533-4e7f-b20f-bd9a7ece27b6

**Comment by zjpjly** [comment]
this issue has been resolved



![Image](https://github.com/kubesphere/console/assets/18654693/871aa796-08e0-4d44-9ebc-f85482aaaa5e)
