### ISSUE TITLE
【BUG】在最新3.4版本中，所有容器组列表关于CPU和内存的图表都不见了。

### ISSUE THREAD

**Issue by resetsix** [kubesphere/console#4175]
![图片](https://github.com/kubesphere/console/assets/85431995/7669132c-f4cb-4d93-800b-f2a2aa7caa0c)

![图片](https://github.com/kubesphere/console/assets/85431995/bd2f7292-6e57-4d33-8c75-c17299d7546b)

**Comment by studyingwang23** [comment]
Wait for a period of time to see the chart information.

**Comment by zjpjly** [comment]
this issue has been resolved


![Image](https://github.com/kubesphere/console/assets/18654693/b4659f76-34d5-49ae-b1d1-02e4c581f37a)
