### ISSUE TITLE
 When creating a routing configuration rule, it cannot be successfully created when entering the routing rule path.

### ISSUE THREAD

**Issue by studyingwang23** [kubesphere/console#4177]
**Describe the bug**

https://github.com/kubesphere/console/assets/109194125/03de51c7-2988-42de-8ab6-2b715f9a0fb5

KubeSphere: V3.4.0

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/console/assets/18654693/17dd6a9d-8d56-4c58-98e8-aeaae3e729ce)
