### ISSUE TITLE
The API version not matched when set notification channel

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#4178]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
> [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/zt-1ilxbsp39-t4ES4xn5OI0eF5hvOoAhEw)

**Describe the bug**

When creating notification channel, the API version is v2beta1, but the CRD version is v2beta2, this will course the data lost.

For UI issues please also add a screenshot that shows the issue.

<img width="414" alt="企业微信截图_16917477235133" src="https://github.com/kubesphere/console/assets/53003665/1b557529-f07d-4410-b565-3047a7e8469b">

<img width="418" alt="企业微信截图_16917477507175" src="https://github.com/kubesphere/console/assets/53003665/0fe8cd7b-7d68-403c-9e99-58dc245b955c">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.4.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

For example:
3 masters:  8cpu/8g
3 nodes: 8cpu/16g

(and other info are welcomed to help us debugging)

**To Reproduce**

**Expected behavior**

**Comment by zjpjly** [comment]
![Image](https://github.com/kubesphere/console/assets/18654693/288d4303-a14d-453b-8265-7b7fbab21267)


![Image](https://github.com/kubesphere/console/assets/18654693/b6ea85b6-9183-4a65-9b65-2c372e4976f5)
