### ISSUE TITLE
修改弹性伸缩的副本提示一定要输入内存限制数（第一次保存时没有输入）

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/console#42]
KubeSphere: 2.1.0
Kubernetes: 1.13.7
To Reproduce(复现步骤)
1.点击工作负载，选择一个工作负载，点击更多操作，选择弹性伸缩，填入CPU百分比和最大副本数，点击确认（不要填入内存限制数）
2.点击弹性伸缩，修改最大副本数，发现如下报错，提示一定要输入内存限制数

![HPA](https://user-images.githubusercontent.com/28557169/71234470-03f6d100-2334-11ea-8040-56f5c6c1bc63.png)

**Comment by minghaoye** [comment]
如果没有内存限制需要把自动填充的0给删掉，稍后修复一下
