### ISSUE TITLE
Allows to skip verification when adding an image repository

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#422]
**What would you like to be added**:

![image](https://user-images.githubusercontent.com/43693241/84727311-4fc3c380-afc1-11ea-9b00-9b42eb27110a.png)

Allow skipping when adding an image repository/

**Why is this needed**:

It may not be the same node that verifies and uses the images secret. It brings a  bad experience.

![image](https://user-images.githubusercontent.com/43693241/84727160-070c0a80-afc1-11ea-9bf8-0a5791314238.png)

/enhancement

**Comment by harrisonliu5** [comment]
what is the keyword of the checkbox

/assign @shaowenchen

**Comment by shaowenchen** [comment]
@Carlosfengv Please help us to design this feature.
