### ISSUE TITLE
3.4.1 无法添加gitlab仓库，也无法通过gitlab建立多分支流水线

### ISSUE THREAD

**Issue by GitHubLoveKe** [kubesphere/console#4272]
![image](https://github.com/kubesphere/console/assets/17232388/23effdc9-989b-4a70-888d-b1905ceba244)

![image](https://github.com/kubesphere/console/assets/17232388/c81cc18f-41a3-48d7-a0ec-276a7f4e6c14)

**Comment by GitHubLoveKe** [comment]
添加gitlab代码的时候窗口闪退，通过yaml导入的代码仓库，无法创建多分支流水线，在正常流水线中可以正常拉取代码

**Comment by yudong2015** [comment]
same issue: kubesphere/ks-devops#1039
and has been fixed by #4270

**Comment by yudong2015** [comment]
In v3.4.1 , you can create multi-branch pipeline with `git` repo.

**Comment by GitHubLoveKe** [comment]
thanks
