### ISSUE TITLE
Should throw correct error message

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#43]
* [ ] When no backend service of KubeSphere is configured, it throws internal error. It should never throw such error to end user.
![Screen Shot 2019-12-20 at 3 41 31 PM](https://user-images.githubusercontent.com/28859385/71238500-2b9f6680-233f-11ea-8ce0-382656077b33.png)

**Comment by yunkunrao** [comment]
By applying pr #103 , this issue was fixed in dev env, and need to be verfied finally in 2.1.1 official release.

**Comment by yunkunrao** [comment]
Verified with release-2.1 image tag.

**Comment by yunkunrao** [comment]
Verified with release-2.1 image tag.
