### ISSUE TITLE
Default node label doesn't exist in DevOps

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#431]
**What would you like to be added**:

![image](https://user-images.githubusercontent.com/43693241/84848484-d6da6f80-b085-11ea-9266-e011c9d88302.png)

`default` should be replaced by `base`

**Why is this needed**:

If the user can‘t modify the label，it will result in the runtime error.

/area devops
/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
This problem has been fixed, but the current environment has not been updated
