### ISSUE TITLE
Scm pipeline doesn't need graphical editor in DevOps

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#437]
**Describe the bug**

Scm pipeline defines pipeline by jenkinfile in source repo.  It don't need graphical editor in DevOps

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0

**Expected behavior**

- [ ] don't show the page when creating scm pipeline

![image](https://user-images.githubusercontent.com/43693241/84863947-6e50ba00-b0a8-11ea-9dec-d6f9db41bba8.png)

- [ ] hidden that button

![image](https://user-images.githubusercontent.com/43693241/84864007-8b858880-b0a8-11ea-9fe4-bc011a123a33.png)

/area devops
/milestone 3.0.0
/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
in this API don't return the scmSource
/kapis/clusters/gondor/devops.kubesphere.io/v1alpha2/devops/asdasdkx2xq/pipelines/scm/

![image](https://user-images.githubusercontent.com/17872673/84864796-cb993b00-b0a9-11ea-8a1d-47fd832baa63.png)

\assign @shaowenchen

**Comment by shaowenchen** [comment]
This is reasonable. It caused by the error Jenkinsfile path. In this case, graphical editor is not needed.

In addition, the content of the editing page is wrong.

![image](https://user-images.githubusercontent.com/43693241/84866969-0e104700-b0ad-11ea-8bdc-6b6171d9d2cf.png)

![image](https://user-images.githubusercontent.com/43693241/84867017-208a8080-b0ad-11ea-9ecc-5c4f2ecf82f1.png)

**Comment by harrisonliu5** [comment]
Display repo selection, need to judge whether there is multi_branch_pipeline in the data

**Comment by shaowenchen** [comment]
fixed
/close
