### ISSUE TITLE
need a inital name of stage in DevOps

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#438]
**Describe the bug**

There is not initial name provided to stage cause an error message.

![image](https://user-images.githubusercontent.com/43693241/84865043-2cc10e80-b0aa-11ea-8447-96214c8bd483.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0

**Expected behavior**

give an initial name to stage, like stage-name-xxxxx

/area devops
/milestone 3.0.0
/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
Solution: 
Each time you add a stage, get the length of the current stage list and use the length for the default name of the current stage, such as stage-0
