### ISSUE TITLE
activities have no paged in DevOps

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#440]
**Describe the bug**

![image](https://user-images.githubusercontent.com/43693241/84870184-8f69d880-b0b1-11ea-9443-74834c4775e0.png)

The activities of pipeline have no paged.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0

/area devops
/milestone 3.0.0
/assign @harrisonliu5  @shaowenchen

**Comment by shaowenchen** [comment]
Frontend paging is needed here.

**Comment by harrisonliu5** [comment]
1. [GET]https://console.kubesphere.io/kapis/clusters/gondor/devops.kubesphere.io/v1alpha2/devops/test0118z8rs/pipelines/pipe001/runs/?start=0&limit=10

2. [GET]https://console.kubesphere.io/kapis/clusters/gondor/devops.kubesphere.io/v1alpha2/devops/test0118z8rs/pipelines/pipe002/branches/?filter=pull-requests&start=0&limit=10

需要返回 total_count 字段用于分页

**Comment by harrisonliu5** [comment]
pipeline list have paged

**Comment by harrisonliu5** [comment]
when you add the total_count, the pagination of activities in the pipeline will be ok @shaowenchen

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/88250852-6f928980-ccdb-11ea-98bf-c508e2383dd0.png)

The button cannot be clicked

**Comment by rayzhou2017** [comment]
It is normal since you have only one page. You can increase the items into more than one page.

**Comment by shaowenchen** [comment]
https://github.com/kubesphere/kubesphere/pull/2585 fixed it
