### ISSUE TITLE
docs link error in DevOps

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#442]
**Describe the bug**

![image](https://user-images.githubusercontent.com/43693241/84872866-ff2d9280-b0b4-11ea-9223-bf1034f302c1.png)

replace https://kubesphere.io/docs/v2.1/zh-CN/devops/pipeline/
by https://kubesphere.io/docs/zh-CN/devops/pipeline/

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0

**Expected behavior**

Please search the keyword `2.1` to enable no similar errors.

/area devops
/milestone 3.0.0
/assign @harrisonliu5 @shaowenchen

**Comment by shaowenchen** [comment]
The different language has a different link

**Comment by harrisonliu5** [comment]
The document address is configured uniformly, it is not recommended to modify the current one alone
