### ISSUE TITLE
pipeline status still no running in DevOps

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#443]
**Describe the bug**

![image](https://user-images.githubusercontent.com/43693241/84873383-bde9b280-b0b5-11ea-8d64-c27a6fdf2347.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0

**Expected behavior**

display the status of the pipeline from the latest pipeline

/area devops
/milestone 3.0.0
/assign @harrisonliu5 @shaowenchen

**Comment by harrisonliu5** [comment]
The latestRun is missing from the returned data

https://console.kubesphere.io/kapis/clusters/gondor/devops.kubesphere.io/v1alpha2/search?q=type%3Apipeline%3Borganization%3Ajenkins%3Bpipeline%3Adsaddzcpp%2F%2A%3BexcludedFromFlattening%3Ajenkins.branch.MultiBranchProject%2Chudson.matrix.MatrixProject%26filter%3Dno-folders
