### ISSUE TITLE
The download URL of the artifacts may be wrong

### ISSUE THREAD

**Issue by harrisonliu5** [kubesphere/console#446]
**Describe the bug**
![image](https://user-images.githubusercontent.com/17872673/84876835-466a5200-b0ba-11ea-849b-b5d544b073fd.png)

Download artifacts failed

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0

**Expected behavior**

please check the URL of the download artifacts
/area devops
/milestone 3.0.0
/assign @harrisonliu5 @shaowenchen

**Comment by shaowenchen** [comment]
/kind-remove need-to-verify

in single cluster 

 I got /kapis/clusters/default/jenkins.kubesphere.io/v1alpha2/jenkins/job/aaaam489l/job/aaaaa/2/artifact/newfile.txt

But I need /kapis/jenkins.kubesphere.io/v1alpha2/jenkins/job/aaaam489l/job/aaaaa/2/artifact/newfile.txt

**Comment by shaowenchen** [comment]
OK

/close
