### ISSUE TITLE
docs/quick-start/jenkinsfile-out-of-scm, click the buttons but no response: "Add nesting steps" and so on

### ISSUE THREAD

**Issue by TikWind** [kubesphere/console#449]
**General remarks**
docs/quick-start/jenkinsfile-out-of-scm, click the buttons but no response: "Add nesting steps" and so on.

**Describe the bug**
I follow the steps: https://kubesphere.io/docs/quick-start/jenkinsfile-out-of-scm/#stage-ii-unit-test

In this step:"4.2.2. Click Add Step and select container, name it maven, then click OK.", it is no response after I click the buttons:"Add nesting steps", "Add conditions", "Add step" and the icon button.

![image](https://user-images.githubusercontent.com/65604564/84972087-b4f9ef00-b150-11ea-836c-12cfbce186f7.png)

And it doesn't send any request.

![image](https://user-images.githubusercontent.com/65604564/84972352-3fdae980-b151-11ea-971e-adececadce28.png)

So, why? What's up?

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 2.1.1

**Environment**
1 masters: 12cpu/64g
2 nodes: 12cpu/32g

**Comment by shaowenchen** [comment]
In my case, it's OK. There is no request while editing. Can you view  Console Tab，any errors?

**Comment by TikWind** [comment]
There is no error : 
![image](https://user-images.githubusercontent.com/65604564/84987680-32cef200-b173-11ea-918f-48af6eb20f2d.png)
@shaowenchen

**Comment by shaowenchen** [comment]
Maybe, you have missed the error message. Can you open the Debug Panel,  refresh the page and try again?

**Comment by TikWind** [comment]
I have refreshed the page and tried again, but it is the same.
@shaowenchen

**Comment by shaowenchen** [comment]
It can't be repeated.

/close
