### ISSUE TITLE
Adding cluster seems not refresh automatically

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#464]
After adding a new cluster using direct connect, it seems hung as shown below. But it should be already added successfully since I clicked workbench, then clusters, it showed correctly.
<img width="982" alt="Screen Shot 2020-06-20 at 1 29 27 PM" src="https://user-images.githubusercontent.com/28859385/85193380-9df70080-b2fa-11ea-98e8-1fa9b501706e.png">

**Comment by rayzhou2017** [comment]
Adding the host cluster itself had no such problem.

**Comment by leoendless** [comment]
/kind/need-to-verify

**Comment by rayzhou2017** [comment]
verified
