### ISSUE TITLE
View the task log interface in the build image returns 404: Page Not Found

### ISSUE THREAD

**Issue by harrisonliu5** [kubesphere/console#473]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17872673/85246266-bf7ff580-b47c-11ea-8614-067921f75645.png)

API:
[GET] https://console.kubesphere.io/kapis/logging.kubesphere.io/v1alpha2/namespaces/project001/pods/service001-s2i-u9n8-0bv-cd8b6aeb2a93-job-4smpp?size=300&from=0&sort=asc

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0(2020-06-22)

**Comment by harrisonliu5** [comment]
**API**
[GET] https://console.kubesphere.io/kapis/clusters/shire/resources.kubesphere.io/v1alpha2/namespaces/project001/s2iruns?conditions=labels.devops.kubesphere.io%2Fbuilder-name%3Ds2i-java-simple-s2i-n0hm&paging=limit%3D10%2Cpage%3D1&orderBy=createTime&reverse=true

可以获取日志数据。

[GET] https://console.kubesphere.io/kapis/clusters/shire/logging.kubesphere.io/v1alpha2/namespaces/project001/pods/s2i-java-simple-s2i-n0hm-xzo-212382819d94-job-trvx7?size=300&from=0&sort=asc

接口 404

**Comment by shaowenchen** [comment]
There are no cluster parameters in URL  
![image](https://user-images.githubusercontent.com/43693241/87929809-983b3900-cab9-11ea-9b05-c39941ccc1fe.png)

fixed

/close
