### ISSUE TITLE
500 is returned when viewing the details of the credentials in devops

### ISSUE THREAD

**Issue by harrisonliu5** [kubesphere/console#480]
**Describe the bug**
![image](https://user-images.githubusercontent.com/17872673/85373182-79eb2780-b565-11ea-81ff-a14441a38da8.png)

api:
[GET] https://console.kubesphere.io/kapis/clusters/shire/devops.kubesphere.io/v1alpha2/devops/devops002tn56c/credentials/111/usage

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0(2020-06-23)

/assign @shaowenchen

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/85379051-e36f3400-b56d-11ea-8abb-6dbc251e84b7.png)

review token failed
/assign @wansir

**Comment by turtlechang** [comment]
另外在3.0.0 不能用kubesphere的帳號登入Jenkins webui 會登入錯誤，煩請修正，謝謝!!

**Comment by shaowenchen** [comment]
> 另外在3.0.0 不能用kubesphere的帳號登入Jenkins webui 會登入錯誤，煩請修正，謝謝!!

Please describe your question in other issues. @turtlechang 

/close
