### ISSUE TITLE
Locales missing

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#485]
The English description below needs a translation into Chinese.
<img width="1215" alt="Screen Shot 2020-06-24 at 11 14 53 AM" src="https://user-images.githubusercontent.com/28859385/85494857-149e4180-b60c-11ea-8713-a12cfd88d954.png">

**Comment by Sherlock113** [comment]
![图片](https://user-images.githubusercontent.com/65327072/85498341-1408a980-b612-11ea-8816-47fa0ba9d2dd.png)
I think the English descriptions of these roles are already listed here? Maybe it is hard coded somewhere but I cannot them in the locale file directly.

**Comment by rayzhou2017** [comment]
verified
