### ISSUE TITLE
after refreshing the pipeline page , it jumps to the activity page

### ISSUE THREAD

**Issue by shaowenchen** [kubesphere/console#486]
**Describe the bug**

![image](https://user-images.githubusercontent.com/43693241/85496655-4369e700-b60f-11ea-8b8f-b330d1c07fba.png)

after refreshing

![image](https://user-images.githubusercontent.com/43693241/85496720-5e3c5b80-b60f-11ea-9673-1c1e68dfb077.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0

/area devops
/assign @harrisonliu5 @shaowenchen

**Comment by harrisonliu5** [comment]
The reason is the same as #441
