### ISSUE TITLE
构建镜像功能中，无法删除条目

### ISSUE THREAD

**Issue by leowucn** [kubesphere/console#49]
**Describe the bug(描述下问题)**
构建镜像功能中，选择条目进行删除，本来是要填写条目名然后确定删除，现在是在填写条目名时对话框迅速自动切换为确认框，完全没法填写条目，这种情况下，点击确认框的确认按钮，无反应。
我随后点击那个条目，进去后，在左上角下拉菜单里删除了这个条目
<img width="1632" alt="Snipaste_2019-12-23_15-24-12" src="https://user-images.githubusercontent.com/16133390/71342637-50dae180-2598-11ea-8028-f4c5d8da3847.png">

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by minghaoye** [comment]
谢谢反馈，已复现，正在更新的任务选中后，更新状态后选中状态会丢失。可以在右侧按钮删除
![Screen Shot 2019-12-23 at 5 34 46 PM](https://user-images.githubusercontent.com/22934997/71349902-01ea7780-25ab-11ea-91ce-63386053f277.png)

2.1.1会修复
