### ISSUE TITLE
The link "How to get kubeconfig" on page cluster add jump to the page cluster add

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#493]
Describe the bug
The link "How to get kubeconfig" on page cluster add jump to the page cluster add

For UI issues please also add a screenshot that shows the issue.
<img width="733" alt="1593310153(1)" src="https://user-images.githubusercontent.com/53003665/85935873-d8c6ed00-b927-11ea-9d40-8a7d219a0550.png">

Versions used(KubeSphere/Kubernetes)
KubeSphere: 3.0.0(2020-06-28)

**Comment by leoendless** [comment]
@zryfish  Can you provide a link?

**Comment by weili520** [comment]
This problem has been resolved, so we should close it.

https://user-images.githubusercontent.com/33231138/158123137-421f1053-eb04-4ebb-aba8-0aba56afcfa1.mov
