### ISSUE TITLE
Wrong display when turn on real-time logging of container

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#497]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

It is a wrong dispaly when turn on real-time logging of container (The content displayed is not real logs)
![image](https://user-images.githubusercontent.com/49136171/85936926-a1f5d480-b931-11ea-96e1-884bdcf0c773.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:  3.0.0(2020/6/28)

**Environment**

dev env

**Expected behavior**

Show in real-time with correct log content when turn on real-time logging of container

**Comment by leoendless** [comment]
Fixed

**Comment by junotx** [comment]
verified
