### ISSUE TITLE
OP back button does not work

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#498]
I clicked the back icon or the text, didn't work. Also the layout seems strange.
![Screen Shot 2020-06-28 at 11 30 15 AM](https://user-images.githubusercontent.com/28859385/85937093-d4540180-b932-11ea-94cf-7d4478042c78.png)

**Comment by leoendless** [comment]
The back button is under the header. The header‘s background should be changed more eartly

**Comment by leoendless** [comment]
Fixed

**Comment by rayzhou2017** [comment]
verified
