### ISSUE TITLE
Locales issue

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#503]
The base locale files should be `en`, not `cn`. Why I see different from `en` and `cn` folders? For instance, "'Select file': '选择文件'" is in Chinese app.js, but I can't find the key "'Select file'" in `en` app.js. It should be an exact mapping in terms of key in the folders.

**Comment by Sherlock113** [comment]
In fact, I think all the js. files in the locales\en only contain capitalized keys followed by their English UI. For other short phrases (e.g. Select file), they cannot be found in locales\en. I think these files were designed this way at the beginning. @leoendless Is that correct?

I think this is understandable as these short phrases are English themselves. Unlike capitalized keys which are not readable texts, these short phrases can be understood and they do not need to be translated again in locales\en. In code, they appear as t ('').

**Comment by leoendless** [comment]
@Sherlock113 Yes, ``t`` will return the key if no corresponding value is found.

**Comment by rayzhou2017** [comment]
I know what you mean. But it is not good for localization. En should be the base.

**Comment by leoendless** [comment]
En is the base, but not in locales/en.

**Comment by Sherlock113** [comment]
When partners do the translation, they need to refer to the English UI, which is their source language. However, I do not recommend they copy all js. files in locales/en in their own language folder as these files do not have simple words or phrases in the UI.

Of course, they can do this and they can translate capitalized keys in it. But for simple words or phrases, they have to find them one by one in the UI and add those words themsevles in these js. files, which is so complicated.

My suggestion is that they copy all files in locales/zh directly which contain all UI, delete Chinese, and translate based on the En in these js. files.

**Comment by rayzhou2017** [comment]
It is better to clarify why is that in the localization readme. People will not understand why choose zh, then refer to en.

**Comment by Sherlock113** [comment]
Sure, I will add some explanations for the Console Localization Guide.
