### ISSUE TITLE
应用管理->应用分类界面 不方便点击下一页

### ISSUE THREAD

**Issue by leowucn** [kubesphere/console#51]
**Describe the bug(描述下问题)**
在浏览器页面上下翻动时，往上翻页下一页按钮和工具按钮很容易混在一起，往下翻页下一页按钮就跑到页面底部看不到了。导致很难点击下一页按钮。希望能优化下，谢谢
<img width="1632" alt="Snipaste_2019-12-23_18-11-11" src="https://user-images.githubusercontent.com/16133390/71351820-9fe04100-25af-11ea-845a-5fb4287a4863.png">

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
How many nodes and their hardware configuration: 

For example:
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by Carlosfengv** [comment]
工具按钮是可以拖动的，可以移开

**Comment by leowucn** [comment]
哈哈哈，好吧
