### ISSUE TITLE
page not refresh automatically after adding cluster

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#511]
The page still hung but the cluster is actually added since I can open the page using a different browser. It is using agent connection.
![Screen Shot 2020-06-29 at 4 51 30 PM](https://user-images.githubusercontent.com/28859385/85993533-12335180-ba29-11ea-8a70-b1dbdc369dc2.png)

**Comment by leoendless** [comment]
![image](https://user-images.githubusercontent.com/8739949/85996187-229cf980-ba34-11ea-83a5-0e0b302dc4c6.png)
You need to check if the console running the latest image, and if the modified messages have been pushed to the console by WebSocket.

**Comment by rayzhou2017** [comment]
verified
