### ISSUE TITLE
lack of desc for cluster authorization

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#516]
The first tip is lack of description
<img width="494" alt="Screen Shot 2020-06-29 at 8 56 12 PM" src="https://user-images.githubusercontent.com/28859385/86008256-15d7d000-ba4b-11ea-8418-987c01b7c052.png">

**Comment by Sherlock113** [comment]
I will add a description for the Engish text here.

**Comment by rayzhou2017** [comment]
verified
