### ISSUE TITLE
cluster status

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#517]
* [ ] Not --> Not Enabled?
* [ ] Why I can't find etcd monitoring?
* [ ] Why etcd is yellow?
<img width="1224" alt="Screen Shot 2020-06-29 at 9 05 58 PM" src="https://user-images.githubusercontent.com/28859385/86009175-77e50500-ba4c-11ea-9022-de8adedee8a4.png">

**Comment by leoendless** [comment]
etcd healthy check API missing. @huanggze

**Comment by leoendless** [comment]
@rayzhou2017 You need to enable etcd monitoring in ``cm`` ks-installer

**Comment by huanggze** [comment]
true, etcd monitoring is off. 

no idea why etcd status shows yellow. It should be green as what I see from resource  componenthealth API @leoendless

**Comment by rayzhou2017** [comment]
> @rayzhou2017 You need to enable etcd monitoring in `cm` ks-installer

It is not enabled by default?

**Comment by rayzhou2017** [comment]
verified
