### ISSUE TITLE
Match field is not correct for the output plugin of events added by the new UI setting

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#523]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**

The match field is not correct for the output plugin added by the new UI setting
![image](https://user-images.githubusercontent.com/49136171/86093272-44a08580-bae1-11ea-99a9-bdcada1e61e4.png)
events should match `kube_events` not `kube.*`
In addition, auditing should match `kube_auditing` 

**Versions used(KubeSphere/Kubernetes)**

KubeSphere: 3.0.0(2020/6/30)

**Environment**

allinone: 4cpu/8g

**Expected behavior**

events should match `kube_events` not `kube.*`
In addition, auditing should match `kube_auditing`

**Comment by benjaminhuo** [comment]
@wanjunlei

**Comment by junotx** [comment]
verified for events.

@wanjunlei , you can verify auditing's

**Comment by wanjunlei** [comment]
verified for auditing
