### ISSUE TITLE
role description not translated

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#528]
<img width="1218" alt="Screen Shot 2020-06-30 at 8 49 55 PM" src="https://user-images.githubusercontent.com/28859385/86127996-56028580-bb13-11ea-81d4-304ade41cc2b.png">

**Comment by Sherlock113** [comment]
![图片](https://user-images.githubusercontent.com/65327072/86137245-a4b61c80-bb1f-11ea-8be0-5bf7e3655e52.png)
![图片](https://user-images.githubusercontent.com/65327072/86137337-c6170880-bb1f-11ea-8b69-22eb50b70c9c.png)
This sentence was already translated in the locales folder. I think the UI text has not been updated for this part.

**Comment by leoendless** [comment]
These two roles will no longer be preset in the cluster.

**Comment by rayzhou2017** [comment]
I don't understand. ws manager may not belong to cluster level (instead, it belong to the platform level), but cluster-regular also does not belong to cluster?

**Comment by leoendless** [comment]
There are only two preset cluster roles(cluster-admin and cluster-viewer).
