### ISSUE TITLE
cluster status font

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#529]
The font in the middle of the screen seems too big, doesn't it? Is it as design?
<img width="1041" alt="Screen Shot 2020-06-30 at 9 51 39 PM" src="https://user-images.githubusercontent.com/28859385/86134289-03799700-bb1c-11ea-8f30-6b74ee05c8ce.png">

**Comment by Carlosfengv** [comment]
![image](https://user-images.githubusercontent.com/23092051/86312248-dc72b080-bc54-11ea-91b3-29bfd0f574d4.png)
@leoendless

**Comment by leoendless** [comment]
Where is the design?

**Comment by leoendless** [comment]
I found the same style in the v2.1.1 console. So it was originally designed like this.
