### ISSUE TITLE
monitoring sorting is not correct

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#541]
The asc seems not working
![Screen Shot 2020-07-01 at 2 54 15 PM](https://user-images.githubusercontent.com/28859385/86212514-cc05fb80-bbaa-11ea-813a-2ac824ffce2d.png)

**Comment by leoendless** [comment]
@huanggze 
`sort_type: asc` and `sort_type: desc` returned the same result.

**Comment by rayzhou2017** [comment]
verified
