### ISSUE TITLE
Some APIs errors in custom monitoring templates include saving templates

### ISSUE THREAD

**Issue by harrisonliu5** [kubesphere/console#544]
**Describe the bug**

![image](https://user-images.githubusercontent.com/17872673/86232988-59efdf80-bbc7-11ea-968e-0dacb4606ba2.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0(2020-07-01)

/assign @leoendless

**Comment by leoendless** [comment]
This problem has been fixed
