### ISSUE TITLE
where is  '@pitrix/lego-ui'  doc ?

### ISSUE THREAD

**Issue by PmcFizz** [kubesphere/console#545]
I see this project import this node_module '@pitrix/lego-ui' 
 
I dont discover what its doc

can  you tell me ? @duanjiong @zheng1

**Comment by zheng1** [comment]
@leoendless  can answer this question

**Comment by leoendless** [comment]
There are no docs published on the internet. But we are building a component library [kube-design](https://github.com/kubesphere/kube-design) to replace `@pitrix/lego-ui` .

**Comment by PmcFizz** [comment]
兄弟啊 这就有点坑了吧.
