### ISSUE TITLE
It always return empty when search jobs with 'Last Executed Time' on the page jobs of clusters.

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#553]
**Describe the bug**

It always return empty when search jobs with 'Last Executed Time' on the page jobs of clusters.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:3.0.0(2020-07-02)

**Comment by leoendless** [comment]
It’s a mistake to search with 'Last Executed Time'. Should be removed.

**Comment by wanjunlei** [comment]
verified
