### ISSUE TITLE
Rerun job error

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#554]
**Describe the bug**
If i rerun job on the page jobs of clusters, it is no response. If i rerun job on the page records of  jobs of clusters, there is a 404 error

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:3.0.0(2020-07-02)

/assign @leoendless

**Comment by leoendless** [comment]
@wansir @zryfish 

GET /kapis/clusters/gondor/resources.kubesphere.io/v1alpha2/namespaces/test/jobs/ddd?action=rerun&resourceVersion=10968282 

return 404

**Comment by wanjunlei** [comment]
verified
