### ISSUE TITLE
It always return empty when search jobs with 'Status=Completed'

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#555]
**Describe the bug**
It always return empty when search jobs with 'Status=Completed'

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:3.0.0

**Comment by wanjunlei** [comment]
The parameter should be 'status=complete', not 'status=completed'

**Comment by leoendless** [comment]
Why change the completed job status value? @wansir

**Comment by wanjunlei** [comment]
This bug does not be fixed.

**Comment by leoendless** [comment]
Mistake operation of `need-to-verify`. This issue hasn't been fixed. @zryfish Please take a look.

**Comment by wanjunlei** [comment]
verified

**Comment by zryfish** [comment]
/close
Due to verification passed
