### ISSUE TITLE
It will waiting for a long time if the image name does not exist when create job

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#558]
**Describe the bug**
It will waiting for a long time if the image name does not exist when create job.
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/86334153-6afc2780-bc7f-11ea-8838-e7e60f0e85f6.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:3.0.0

**Comment by leoendless** [comment]
It is not a blocking operation. You can submit the sub-form without the image search result
