### ISSUE TITLE
Pods page arrange error

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/console#559]
**Describe the bug**
From pods interface, chosen "All Projects" to show all pods in all projects, then turn over to page 4 which exceeded the page number of one project, then chosen one project to filter pods in this project which will not reach page 4, then it will display no pods, must turn over to page 1 to show it.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/38337958/86334088-5455d080-bc7f-11ea-8482-5dd3847dc122.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Expected behavior**
Refresh page info and show filtered pos correctly.

**Comment by leoendless** [comment]
Should reset the page if project selected.

**Comment by leoendless** [comment]
@harrisonliu5 Could you help to fix the bug?

**Comment by harrisonliu5** [comment]
ok
