### ISSUE TITLE
创建资源时，镜像名功能优化的建议

### ISSUE THREAD

**Issue by leowucn** [kubesphere/console#56]
**Describe the bug(描述下问题)**
我在测试灰度发布功能时，不小心把镜像名后面的空格也复制了并粘贴到了设置窗口中，然后就review v2服务就一直起不来，只能进集群查看replicaset才能发现问题。镜像名后面多一个空格本来就是一个错误，希望前端在接受用户输入时把镜像名前后的空格都去掉
<img width="731" alt="Snipaste_2019-12-24_16-09-40" src="https://user-images.githubusercontent.com/16133390/71402606-51db4400-2668-11ea-9d80-8e385de38ff3.png">

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by leoendless** [comment]
Fixed in the latest v3.0 dev.
