### ISSUE TITLE
Query pod by application return no result, query with no field selected, don't know which search field is used

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/console#560]
**Describe the bug**
Query pod with application can not get result, query with name is ok, query with no field selected shows no result and can not understand which field is used in query.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/38337958/86335539-338e7a80-bc81-11ea-9e37-aee5637e5b64.png)
![image](https://user-images.githubusercontent.com/38337958/86335569-3f7a3c80-bc81-11ea-9449-56d7b9d453fe.png)
![image](https://user-images.githubusercontent.com/38337958/86335582-44d78700-bc81-11ea-9746-34d14a2a71b1.png)
![image](https://user-images.githubusercontent.com/38337958/86335596-4acd6800-bc81-11ea-8c2c-39bdfa9c667a.png)
![image](https://user-images.githubusercontent.com/38337958/86335788-89fbb900-bc81-11ea-92fd-dd865afde62b.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.0.0

**Expected behavior**
Show correct query result in application query.
Show clear meaning of result when query with no field selected.

**Comment by leoendless** [comment]
@zryfish Does the resource API support search pod by app?

**Comment by leoendless** [comment]
We remove the app search option in cluster management, but you can use it in normal project.

**Comment by Ma-Dan** [comment]
Query pod by application in a normal project is working now.
But still get empty result when query with no field selected.

**Comment by Ma-Dan** [comment]
Verified, default key is name, close issue.
