### ISSUE TITLE
It does not add Container Startup Check to the job

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#561]
**Describe the bug**
It does not add Container Startup Check to the job when  Container Startup Check was selected and set.

For UI issues please also add a screenshot that shows the issue.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:3.0.0

**Comment by leoendless** [comment]
Did yaml format wrong? Or k8s not run the startup check

**Comment by wanjunlei** [comment]
Create job and add startup check
![image](https://user-images.githubusercontent.com/53003665/86549862-5c5d8b00-bf73-11ea-8b18-5fff8590c7e0.png)

This is the yaml of pod which created by job, this is no startup check
![image](https://user-images.githubusercontent.com/53003665/86549767-17395900-bf73-11ea-8085-3755610199c0.png)

**Comment by leoendless** [comment]
Could you please re-check this issue after you update the console image to the latest version?

**Comment by wanjunlei** [comment]
The problem still exists in latest version.

**Comment by leoendless** [comment]
Please post the job's yaml

**Comment by wanjunlei** [comment]
kind: Job
apiVersion: batch/v1
metadata:
  name: job4
  namespace: job-test
  labels:
    app: job4
  annotations:
    kubesphere.io/creator: wanjunlei
    revisions: >-
      {"1":{"status":"running","desire":1,"uid":"a8850c7a-8e59-4d63-87f1-381ac23a2ff4","start-time":"2020-07-08T09:08:17Z","completion-time":"0001-01-01T00:00:00Z"}}
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 6
  selector:
    matchLabels:
      controller-uid: a8850c7a-8e59-4d63-87f1-381ac23a2ff4
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: job4
        controller-uid: a8850c7a-8e59-4d63-87f1-381ac23a2ff4
        job-name: job4
      annotations:
        kubesphere.io/containerSecrets: ''
    spec:
      containers:
        - name: container-51rebt
          image: redis
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler

**Comment by wanjunlei** [comment]
http://139.198.112.97:30885/
You can test it

**Comment by leoendless** [comment]
I found that on clusters with versions lower than 1.18, the startupProbe of the job is ignored.

**Comment by leoendless** [comment]
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

Need to check if the startupProbe feature enabled.
