### ISSUE TITLE
Chrome browser can not pop right button menu in pod list

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/console#562]
**Describe the bug**
Right click on pod list item can not pop menu, whether selected or not.
For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/38337958/86347223-92a7bb80-bc90-11ea-926e-fc2ad49db658.png)
![image](https://user-images.githubusercontent.com/38337958/86347558-08ac2280-bc91-11ea-9fec-77a30b98700c.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.0.0

**Expected behavior**
Pop up menu on right button click

**Comment by leoendless** [comment]
Sorry for that ks-console do not support right-click menu control.
