### ISSUE TITLE
Disk Log Collection is not enabled when create job

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#566]
**Describe the bug**
It will be successed if i opend Disk Log Collection when create job, but the  Disk Log Collection did not really take effect.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:3.0.0

/assign @leoendless

**Comment by leoendless** [comment]
Could you describe how did you use the disk log collection when create a job.

**Comment by wanjunlei** [comment]
First, open Disk Log Collection on the page projects advanced

![image](https://user-images.githubusercontent.com/53003665/86548992-e22c0700-bf70-11ea-9ee5-82ee2af52705.png)

Second, create a job and enable Disk Log Collection
![image](https://user-images.githubusercontent.com/53003665/86549057-1b647700-bf71-11ea-95e6-a2b742f0d234.png)

This is the pod of job, there is no logsidecar container.
![image](https://user-images.githubusercontent.com/53003665/86549112-451d9e00-bf71-11ea-8edf-0d4607d176d8.png)

This is the yaml of pod, it only has one container
![image](https://user-images.githubusercontent.com/53003665/86549240-a3e31780-bf71-11ea-9ec1-4fca493e4406.png)

This is a correctly deployment which enabled Disk Log Collection in the same ns.
![image](https://user-images.githubusercontent.com/53003665/86549312-df7de180-bf71-11ea-9483-b85a18e52219.png)

**Comment by leoendless** [comment]
you need to specify the log path to collection.

**Comment by wanjunlei** [comment]
got it
