### ISSUE TITLE
Annotations is not properly added to the job

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#567]
**Describe the bug**
Annotations is not properly added to the job when create job.

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0

/assign @leoendless

**Comment by leoendless** [comment]
Could you describe more details?

**Comment by wanjunlei** [comment]
Create a job and add some annotations.

![image](https://user-images.githubusercontent.com/53003665/86549475-50bd9480-bf72-11ea-8f3f-c3f9b2d39d03.png)

This is the yaml of pod which created by job, there is no annotations added when create job.
![image](https://user-images.githubusercontent.com/53003665/86549525-72b71700-bf72-11ea-9c62-9e6688c8751a.png)

**Comment by leoendless** [comment]
The annotations are added to the job, not pod. If you want to add an annotation to the pod, you need to edit the pod template by yaml.
