### ISSUE TITLE
Pod info does not display application field

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/console#571]
**Describe the bug**
Application info page can display application field but pod info of the same workload doesn't display.

![image](https://user-images.githubusercontent.com/38337958/86428472-6b4bff80-bd1f-11ea-8ad6-cbb62905655e.png)
![image](https://user-images.githubusercontent.com/38337958/86428579-ad754100-bd1f-11ea-91ef-106bcbdfdc07.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.0.0

**Expected behavior**
All pages contained application field display same correct value.

**Comment by leoendless** [comment]
This issue cannot be fixed in ks console, because helm didn't write the app label to the pods.
