### ISSUE TITLE
cluster name length is not limited

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#585]
Type in `b-1234567890-1234567890-1234567890-1234567890-1234567890-12345-e` or more letters. It is legal to create.

**Comment by rayzhou2017** [comment]
The max number is incorrect. It is set to 62 instead of 63 now. `b-1234567890-1234567890-1234567890-1234567890-1234567890-12345-e` is 64, I have to remove two letters to make it legal.

**Comment by leoendless** [comment]
Why not remove a `-`? The name cannot end with `-`.

**Comment by rayzhou2017** [comment]
I see. The msg did not change, so I thought it is the same reason.
