### ISSUE TITLE
Link redirection for [How to get kubeconfig?] doesn't work

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#588]
![image](https://user-images.githubusercontent.com/22350668/86511800-fbc53580-be2e-11ea-9ad1-94b39423cf08.png)

**Comment by leoendless** [comment]
@zryfish Could you provide the document link?

**Comment by FeynmanZhou** [comment]
ok, all the related links will be provided next week, I am working on it.

**Comment by rayzhou2017** [comment]
duplicate #493
