### ISSUE TITLE
cluster built-in labels

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#589]
It shows two locales here. What if we have more locales?
<img width="598" alt="Screen Shot 2020-07-04 at 8 05 00 PM" src="https://user-images.githubusercontent.com/28859385/86512121-d259d900-be31-11ea-968e-411d1b44e837.png">

**Comment by leoendless** [comment]
Need to translate these keys into the specified lang
```
  ENV_PRODUCTION: '生产环境',
  ENV_DEVELOPMENT: '开发环境',
  ENV_TESTING: '测试环境',
  ENV_DEMO: '演示环境',
```

**Comment by rayzhou2017** [comment]
I mean if there are too many locales, will you still show all of them in the dropdown menu?

**Comment by leoendless** [comment]
Only show the value and the current locale.

The white text are the values. And the tags are the values of the current locale.

**Comment by rayzhou2017** [comment]
verified
