### ISSUE TITLE
There is a 404 error on the page project overview.

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#601]
**Describe the bug**
There is a 404 error on the page project overview.

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/86548075-b9564280-bf6d-11ea-8877-fea819d4b792.png)

![image](https://user-images.githubusercontent.com/53003665/86548196-18b45280-bf6e-11ea-95be-8acb0498944a.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:2020-07-06

/assign @leoendless

**Comment by leoendless** [comment]
the problem of wrong match API.
