### ISSUE TITLE
redirect to right page after creating a fed project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#604]
When I created a fed project, it goes to the regular project page, which confuses users.. It would be better to redirect to the corresponding page.

![Screen Shot 2020-07-06 at 10 34 01 AM](https://user-images.githubusercontent.com/28859385/86550249-8794aa00-bf74-11ea-8107-86f0920e7dda.png)
![Screen Shot 2020-07-06 at 10 34 06 AM](https://user-images.githubusercontent.com/28859385/86550271-91b6a880-bf74-11ea-8926-fa9008c600f8.png)

**Comment by FeynmanZhou** [comment]
> /cc @zryfish @Sherlock113 What should we call here actually, multi-cluster project or federated project?

multi-cluster project looks more obvious, federated is more professional, I prefer the former. And we can add more description here to explain the project and multi-cluster project (or federated project).

![image](https://user-images.githubusercontent.com/40452856/86554813-317a3380-bf81-11ea-80ad-f630617345e8.png)

**Comment by Sherlock113** [comment]
I saw in the website of Rancher, they have this use for "multi-cluster" for multi-cluster apps: https://rancher.com/docs/rancher/v2.x/en/catalog/multi-cluster-apps/
