### ISSUE TITLE
redirect to corresponding cluster regular project page

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#605]
I created a regular project into cluster-01, but it loads the cluster-02 after creating.
![Screen Shot 2020-07-06 at 10 44 27 AM](https://user-images.githubusercontent.com/28859385/86550841-0d652500-bf76-11ea-9ea2-fb51ddc26b81.png)
![Screen Shot 2020-07-06 at 10 44 34 AM](https://user-images.githubusercontent.com/28859385/86550855-1655f680-bf76-11ea-94fb-d0cb52f4f449.png)

**Comment by leoendless** [comment]
What's the select cluster before you click the create button?

**Comment by rayzhou2017** [comment]
verified
