### ISSUE TITLE
The max length of a port name should be 15

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#608]
![image](https://user-images.githubusercontent.com/22350668/86551120-c62b6400-bf76-11ea-99bf-5504b77d599a.png)

![image](https://user-images.githubusercontent.com/22350668/86551132-d04d6280-bf76-11ea-95a6-9d3bef8074f7.png)

![image](https://user-images.githubusercontent.com/22350668/86551139-d7747080-bf76-11ea-9553-8b40df06889f.png)

https://github.com/kubernetes/community/blob/master/contributors/design-proposals/architecture/identifiers.md

**Comment by leoendless** [comment]
No need to restrict the rules here. It just depends on what the user inputs.
