### ISSUE TITLE
图形化创建流水线时，无法拖动任务进行排序

### ISSUE THREAD

**Issue by leowucn** [kubesphere/console#62]
**Describe the bug(描述下问题)**
如下图，当我开始编辑这个流水线时，我能拖动任务进行排序但是鼠标松开后就恢复到原来顺序了。第二次再要拖动时，那里已经固定无法操作了。
<img width="1579" alt="Snipaste_2019-12-25_18-54-41" src="https://user-images.githubusercontent.com/16133390/71443806-0b5d1680-2748-11ea-81c5-5a402e0f1306.png">

**Versions used(KubeSphere/Kubernetes的版本)**
KubeSphere: 2.1.0
Kubernetes: 1.15.7

**Environment(环境的硬件配置)**
1 masters:  4cpu/16g
3 nodes: 4cpu/16g

**Comment by minghaoye** [comment]
非嵌套的任务拖拽有bug，已提交pr

**Comment by leowucn** [comment]
好的
