### ISSUE TITLE
No need to ask user to select namespace again

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#625]
![image](https://user-images.githubusercontent.com/22350668/86563545-24683f00-bf97-11ea-9ee8-ebe72288e53e.png)

![image](https://user-images.githubusercontent.com/22350668/86563546-24683f00-bf97-11ea-9e64-291979b11a43.png)

**Comment by leoendless** [comment]
It’s necessary because the user cannot create resource in federated namespace here.
