### ISSUE TITLE
Why two [Advanced Setting] in CronJob

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#629]
This is somehow confusing. It is easy to miss the [Advanced Setting] in the first step

![image](https://user-images.githubusercontent.com/22350668/86575207-7a45e280-bfa9-11ea-89f9-fa882182f206.png)

**Comment by leoendless** [comment]
The advance settings in basic info are the detailed settings of a cronjob. And the advance settings in the tab are common settings of k8s resources.
