### ISSUE TITLE
Daemonset status search returns wrong result

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/console#636]
**Describe the bug**
Search status select updating returns no result, and search status select stopped returns updating daemonsets.
![image](https://user-images.githubusercontent.com/38337958/86589077-889ef900-bfbf-11ea-9011-792293a9cdbe.png)
![image](https://user-images.githubusercontent.com/38337958/86589098-8f2d7080-bfbf-11ea-8320-718228fa1453.png)
![image](https://user-images.githubusercontent.com/38337958/86589109-95235180-bfbf-11ea-8f33-faadfdac9c66.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: v3.0.0

**Expected behavior**
All status return correct result.

**Comment by Ma-Dan** [comment]
The issue still exists, search by status get empty result on all status.
![image](https://user-images.githubusercontent.com/38337958/88143239-7234a680-cc29-11ea-8c3a-1867648d8197.png)
![image](https://user-images.githubusercontent.com/38337958/88143266-81b3ef80-cc29-11ea-831a-11ca105ab03e.png)
![image](https://user-images.githubusercontent.com/38337958/88143285-8a0c2a80-cc29-11ea-86a5-af4981125c05.png)

**Comment by zryfish** [comment]
Please verify again

**Comment by Ma-Dan** [comment]
![image](https://user-images.githubusercontent.com/38337958/88250064-fa25b980-ccd8-11ea-920f-e1bf0a7f436c.png)
Updating filter returns "stopped" daemonset. This daemonset is actually just created and pulling images.

**Comment by Ma-Dan** [comment]
![image](https://user-images.githubusercontent.com/38337958/88250958-d44de400-ccdb-11ea-892a-08c29c2e2b06.png)
Stopped filter returns real stopped workloads.
The issue could probably be status error for creating daemonsets which status should be 'updating' not 'stopped'.

**Comment by Ma-Dan** [comment]
Fixed and verified
