### ISSUE TITLE
self-provisioner can't create fed project

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#665]
`xiaosi` is the self-provisioner of the fed workspace, but I only see the regular project available to create.
<img width="632" alt="Screen Shot 2020-07-07 at 3 44 13 PM" src="https://user-images.githubusercontent.com/28859385/86739856-c9068180-c068-11ea-9ae5-63f42e6abaa7.png">

**Comment by leoendless** [comment]
@wansir Should `self-provisioner` have the federated project permission?

**Comment by rayzhou2017** [comment]
verified
