### ISSUE TITLE
Lego-UI

### ISSUE THREAD

**Issue by Mockingbird1234** [kubesphere/console#67]
官方的Lego-UI文档打算开源么？？

**Comment by leoendless** [comment]
由于开源的维护成本较大，暂未做这方面的考虑。
目前在 npm 上可以直接使用 ``@pitrix/lego-ui``。
我们会在之后补全 lego-ui 的使用文档及 ks-console 里的组件文档。

**Comment by watermelon-brother** [comment]
ui不开源怎么二次开发了，还说啥全开源？

**Comment by leoendless** [comment]
当前版本，组件库的用法可以参考 console 里已有的用法来进行开发。
在之后的版本中，我们将维护一套公共组件库 https://github.com/kubesphere/kube-design。 当前版本中我们将主要关注于核心功能。

**Comment by rayzhou2017** [comment]
Please use English in github
