### ISSUE TITLE
Email testing title should be localized

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#684]
I am in English locale, the content is as expected, but the title is Chinese

<img width="582" alt="Screen Shot 2020-07-08 at 9 28 03 PM" src="https://user-images.githubusercontent.com/28859385/86924615-4530c000-c162-11ea-8072-a3d9d8013380.png">

**Comment by benjaminhuo** [comment]
/assign @junotx 
@junotx pls take a look at this

**Comment by junotx** [comment]
/assign @leoendless 

`Validation_title` attribute of request body  for `notification.kubesphere.io/v2/serviceconfigs/validation` should be localized

![image](https://user-images.githubusercontent.com/49136171/87648947-8fc5c400-c782-11ea-901f-51b6af1ecd93.png)

**Comment by rayzhou2017** [comment]
verified
