### ISSUE TITLE
Configmap and secret mount interface displays mount read-write mode option

### ISSUE THREAD

**Issue by Ma-Dan** [kubesphere/console#700]
![image](https://user-images.githubusercontent.com/38337958/87123645-c0f15080-c2b9-11ea-9d0d-92167d1d99ba.png)

**What would you like to be added**:
Configmap and secret can only be mounted read-only mode, so read-write mode is not needed here.

**Why is this needed**:
This option may misguide users.

**Comment by leoendless** [comment]
@harrisonliu5 Please help to remove the read-write option of configmaps and secrets.
