### ISSUE TITLE
self-provisioner can't edit project resource quota

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#717]
**Describe the bug**
The edit menu of project resource quota does not show up for self-provisioner
<img width="1047" alt="Screen Shot 2020-07-11 at 9 59 49 AM" src="https://user-images.githubusercontent.com/28859385/87214239-817c4000-c35d-11ea-89ce-3eac7c6012cf.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev

**Environment**
allinone, minimal installation

**Expected behavior**
The edit menu of project resource quota shows up for self-provisioner and self-provisioner is able to edit quotas.

**Comment by rayzhou2017** [comment]
Is it as design? If yes, who is responsible to edit the quota? platform `admin` or workspace `admin`?

**Comment by leoendless** [comment]
The user who has the permission of manage all the projects in the workspace can edit the project's quota.

**Comment by rayzhou2017** [comment]
verified
