### ISSUE TITLE
network policy issues

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#724]
**Describe the bug**
The cluster does not enable network policy. So it should not appear on/off when creating workspace or show off only. And the workspace info also should not show network policy or show off (can't editable).
<img width="617" alt="Screen Shot 2020-07-12 at 8 52 29 PM" src="https://user-images.githubusercontent.com/28859385/87246787-0791a700-c482-11ea-8af3-513741598dc7.png">
<img width="1189" alt="Screen Shot 2020-07-12 at 8 55 25 PM" src="https://user-images.githubusercontent.com/28859385/87246791-0e201e80-c482-11ea-81eb-87800ba9f175.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev

**Environment**
allinone, minimal installation

**Comment by leoendless** [comment]
Network policy should be removed when creating a workspace. Because We can't judge whether to display this selection box if no clusters related when creating a workspace.

**Comment by rayzhou2017** [comment]
verified
