### ISSUE TITLE
Devops cannot be changed to DevOps

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#736]
I noticed Devops is already changed to DevOps for this part, but the UI still displays Devops.
<img width="1432" alt="截屏2020-07-13下午2 33 50" src="https://user-images.githubusercontent.com/65327072/87278238-8d5f3200-c516-11ea-878d-6bc566a2e077.png">

For its ZH-CN, probably because Devops is only effective for this value instead of "DevOps", the Chinese value does not match it, resulting in untranslated text here:

<img width="1269" alt="截屏2020-07-13下午2 35 15" src="https://user-images.githubusercontent.com/65327072/87278327-bf709400-c516-11ea-8e5b-d55ffc42facb.png">

I changed the English back to Devops and built it locally. The Chinese text displays correctly:
<img width="1271" alt="截屏2020-07-13下午2 35 42" src="https://user-images.githubusercontent.com/65327072/87278411-f8106d80-c516-11ea-9b83-90aad872fed1.png">

Are the English UI texts "Devops Management" and "Devops View" hard coded or sth so that they (the English UI) cannot be changed? I think it is better to use "DevOps" instead of "Devops" which is clearly not the common capitalization way for this word.

**Comment by leoendless** [comment]
@wansir Please check the role-templates, and modify the text.

**Comment by Sherlock113** [comment]
Fix verified.
