### ISSUE TITLE
增加 访问记录 页面

### ISSUE THREAD

**Issue by Carlosfengv** [kubesphere/console#77]
**功能描述:**
浏览器中记录用户最近访问的  集群、企业空间、 项目、 DevOps工程。在用户开启访问记录的页面时可以快速切换之前访问的层级资源

**原型地址:**
zpl://screen?pid=5cbe7fbc2f55d8b73f56811b&sid=5e09a8be734c3d972510a296

**Comment by leoendless** [comment]
Fixed in dev.
