### ISSUE TITLE
host cluster description is not localized

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#775]
**Describe the bug**
When make the cluster as host in multi-cluster env, it will add itself automatically as the member and provide description. But it is not localized.
<img width="1063" alt="Screen Shot 2020-07-17 at 12 12 03 PM" src="https://user-images.githubusercontent.com/28859385/87747858-f997a980-c826-11ea-979d-0d162fa91c9f.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev

**Expected behavior**
The desc should be localized.

**Comment by Sherlock113** [comment]
I think this is hard coded? I cannot find this sentence in locales files.

**Comment by rayzhou2017** [comment]
yes, my mistake. It is up to user to modify the description based on her/his locale, not by the system.
