### ISSUE TITLE
Notification not shown in cluster settings

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#798]
**Describe the bug**
Enable notification, but still can't see the setting in the cluster settings. I guess the condition may be incorrect since I only enable notification (alerting, logging, monitoring are all disabled)

<img width="425" alt="Screen Shot 2020-07-19 at 7 34 21 PM" src="https://user-images.githubusercontent.com/28859385/87873829-4b8f2980-c9f7-11ea-88ab-6d96a25ee85e.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone, minimal installation with notification enbaled, redhat 7.4

**To Reproduce**
1. install minimal KubeSphere using KubeKey
2. enable notification via cluster configuration
3. go to the cluster settings
4. No email setting appear

**Expected behavior**
Email setting should appear under cluster settings.

**Comment by rayzhou2017** [comment]
As I guess, only after I enabled alerting, all work fine. But I think notification should be an independent compoent from alerting. /cc @benjaminhuo

**Comment by junotx** [comment]
Notification component can be installed witout the alert，but console cannot show email setting on cluster setting @leoendless

**Comment by rayzhou2017** [comment]
verified
