### ISSUE TITLE
volume count is incorrect

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#803]
**Describe the bug**
The volume count is always zero which is incorrect.
<img width="1233" alt="Screen Shot 2020-07-20 at 10 41 59 AM" src="https://user-images.githubusercontent.com/28859385/87894583-ba12cc80-ca75-11ea-94a8-d34e3d7f8110.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone

**Comment by leoendless** [comment]
@min-zh Please fix the API.

**Comment by rayzhou2017** [comment]
verified
