### ISSUE TITLE
Can't open CRD detailed page

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#804]
**Describe the bug**
Try to configure cluster configuration, but failed to enter the detailed page.
<img width="1166" alt="Screen Shot 2020-07-20 at 10 51 19 AM" src="https://user-images.githubusercontent.com/28859385/87895050-06aad780-ca77-11ea-8b06-959c3dce18d7.png">

<img width="1230" alt="Screen Shot 2020-07-20 at 10 51 13 AM" src="https://user-images.githubusercontent.com/28859385/87895068-10ccd600-ca77-11ea-928e-15f31b978b39.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone

**Expected behavior**
Can open the crd detailed page

**Comment by leoendless** [comment]
@zryfish GET /apis/apiextensions.k8s.io/v1/customresourcedefinitions/clusters.cluster.kubesphere.io 404

**Comment by zryfish** [comment]
@leoendless better use `v1beta1` instead of `v1` to fetch CRD, v1 is not available in kubernete v1.15.x , but v1beta1 is available in v1.18.x

**Comment by rayzhou2017** [comment]
verified
