### ISSUE TITLE
Network policy shows in project when disabled

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#809]
**Describe the bug**
Network policy is disabled, but still shows when creating project
<img width="962" alt="Screen Shot 2020-07-20 at 12 02 17 PM" src="https://user-images.githubusercontent.com/28859385/87898531-f4359b80-ca80-11ea-8442-ecfdd6944a51.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone with network policy disabled

**Expected behavior**
Network policy not shown

**Comment by leoendless** [comment]
We remove the selection here. You can enable the network policy in the project -> network policy.

**Comment by rayzhou2017** [comment]
verified
