### ISSUE TITLE
Network policy switch is missing

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#814]
**Describe the bug**
Network policy is enabled, but the switch is missing when creating a ws. It does appear in ws basic info. I think there are two conditions for showing the switch or not. One is enabled or not. The other one is if the CNI supports network policy or not. /cc @duanjiong I think it should be the backend's responsibility to provide such API for frontend.

<img width="910" alt="Screen Shot 2020-07-20 at 3 56 13 PM" src="https://user-images.githubusercontent.com/28859385/87913417-ae3cff80-caa1-11ea-8d0d-a4ea01d8141c.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone

**Expected behavior**
Network policy switch appears when creating ws.

**Comment by leoendless** [comment]
We removed the network policy settings in workspace creation and project creation. Because the cluster has not been selected. Now you can edit the network policy in the workspace's base-info or the project's network policy page.

**Comment by duanjiong** [comment]
This makes sense as a deployment configuration item. The standard CNI only does address management and network card management, network policy is not part of this. So there is no unified interface to determine whether each plug-in supports network policy, and even if the Support, if the user does not turn it on, it is useless, and there will also be adaptations to the development of different plug-ins.
