### ISSUE TITLE
Existed ingresses not showing if a project's gateway  not created

### ISSUE THREAD

**Issue by zryfish** [kubesphere/console#82]
![image](https://user-images.githubusercontent.com/3326354/72050648-9c152400-32fc-11ea-9c20-51fdb677e79a.png)

**Suggestions:**  Disable creating of new ingresses, but allow editing existed ingresses.

**Comment by Carlosfengv** [comment]
可以与Ingress的Init状态的Issue 一起优化一下
原型地址：
zpl://screen?pid=5cbe7fbc2f55d8b73f56811b&sid=5e16ed8c9a13e098670643f4
