### ISSUE TITLE
Keep searching when image is not present

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#830]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When created deployment and input image did not exist, the search continued without indication that the image cannot be found
![image](https://user-images.githubusercontent.com/49136171/88007151-e5fa8480-cb3f-11ea-8d4f-ceba1643c10f.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0(2020-07-21)

**Expected behavior**
There should be an indication that it cannot be found if the image does not exist

/assign @leoendless

**Comment by rayzhou2017** [comment]
The backend api should have timeout mechanism.

**Comment by rayzhou2017** [comment]
Or it is microservice management to take care of the timeout
