### ISSUE TITLE
not allowed to sync app repo

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#869]
**Describe the bug**
Try to sync app repo, but permission denied
![Screen Shot 2020-07-22 at 4 00 39 PM](https://user-images.githubusercontent.com/28859385/88150902-921d9780-cc34-11ea-89b5-406360711184.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12

**Environment**
allinone with openpitrix enabled

**Expected behavior**
be able to sync app repo

**Comment by wansir** [comment]
@leoendless

Use workspace scope resource API, `/kapis/openpitrix.io/v1/workspaces/{workspace}/repos/{repo}/action`

**Comment by rayzhou2017** [comment]
verified
