### ISSUE TITLE
modify cluster configuration the second time failed

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#874]
**Describe the bug**
For the member cluster, I modified the cluster role to member and forgot to update the jwtSecret. Then I open the the file to add the secret, got the error msg.
![Screen Shot 2020-07-22 at 5 47 42 PM](https://user-images.githubusercontent.com/28859385/88162253-acab3d00-cc43-11ea-9926-172474280a1d.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev
Kubernetes: 1.18.6

**Environment**
allinone, member cluster 

**Expected behavior**
Be able to update the file at any time

**Comment by leoendless** [comment]
what's the resource you modified?

**Comment by rayzhou2017** [comment]
Need to refresh the page to reload the latest yaml. It is the common issue for editing yaml file. I will down grade the priority

**Comment by leoendless** [comment]
I have fixed this problem for other resources. Maybe missing for the crd resources.


Before putting the resource, the console will fetch the latest resource detail, and update the resourceVersion value.

```javascript
  @action
  async update(params, newObject) {
    const result = await request.get(this.getDetailUrl(params))
    const resourceVersion = get(result, 'metadata.resourceVersion')
    if (resourceVersion) {
      set(newObject, 'metadata.resourceVersion', resourceVersion)
    }
    return this.submitting(request.put(this.getDetailUrl(params), newObject))
  }
```

**Comment by rayzhou2017** [comment]
verified
