### ISSUE TITLE
界面是否可以添加初始化容器（initcontainer）

### ISSUE THREAD

**Issue by guoh1988** [kubesphere/console#89]
在部署服务或者deploy的时候容器添加并没有initcontainer，感觉部署带有initcontainer的服务很不方便
![镜像](https://user-images.githubusercontent.com/28557169/72241452-df83d100-3621-11ea-95b3-511551a3e1f2.PNG)

**Comment by leoendless** [comment]
Fixed in https://github.com/kubesphere/console/pull/76. Will be released in v2.1.1.
