### ISSUE TITLE
Search result is incorrect on app store management page

### ISSUE THREAD

**Issue by yuswift** [kubesphere/console#892]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
When I search kafka, result is all instead of app name contains kafka.
When search 888, result is all instead of nothing.
This also happens on app reviews page and app category page.
<img width="1190" alt="Jietu20200724-120102" src="https://user-images.githubusercontent.com/37265389/88359564-aaf98a80-cda5-11ea-850b-445d838ee5ec.png">
![Jietu20200724-115954](https://user-images.githubusercontent.com/37265389/88359570-b0ef6b80-cda5-11ea-87ce-02d57b0568c9.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere:v3.0.0
Kubernetes: (If KubeSphere installer used, you can skip this)

**Environment**
How many nodes and their hardware configuration: 

3 masters:  4cpu/8g
3 nodes: 4cpu/16g

**Comment by rayzhou2017** [comment]
verified
