### ISSUE TITLE
本地运行项目，按照教程上配置后，输入用户名和密码后点击登录报404 page not found是什么原因呢

### ISSUE THREAD

**Issue by konglingjiao0414** [kubesphere/console#900]

**Comment by rayzhou2017** [comment]
Please using English. If prefer Chinese please go to kubesphere.com.cn/forum. Quick answer is you need to check pods to see if there is any problem first.

**Comment by konglingjiao0414** [comment]
After running the project locally and following the tutorial configuration, enter the user name and password and click on the 404 page not Found. What is the reason
