### ISSUE TITLE
Description in the image of monitoring dashboard setting cannot be localized

### ISSUE THREAD

**Issue by Sherlock113** [kubesphere/console#901]
**Describe the bug**

In the monitoring section, the description in the image cannot be localized directly.

<img width="1221" alt="截屏2020-07-24下午4 12 16" src="https://user-images.githubusercontent.com/65327072/88372547-b3af8800-cdc8-11ea-9db9-6ee9066d6041.png">

**To Reproduce**
1. Go to Custom Monitoring Dashboards.
2. Click Create
3. Enter a name to create a dashboard
4. Click Add Monitoring Item at the bottom right corner
5. You can find the image in the popup window

To add the loc, the English can be: The chart will display here.

**Comment by rayzhou2017** [comment]
Seems only English and Simple Chinse localized so far

**Comment by Sherlock113** [comment]
> Seems only English and Simple Chinse localized so far

Yes, I added the capitalized key in es and tc in https://github.com/kubesphere/console/pull/999, and gave them the notice in Slack. They will add the loc later.
<img width="669" alt="截屏2020-07-29下午2 27 50" src="https://user-images.githubusercontent.com/65327072/88764528-aff47a80-d1a7-11ea-9d82-60981cc7b3a8.png">
