### ISSUE TITLE
Deleting devops projects in batch, but the page doesn't auto refresh

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#903]
![image](https://user-images.githubusercontent.com/22350668/88374824-08550200-cdcd-11ea-8144-0e75bff430a6.png)

**Comment by harrisonliu5** [comment]
The data may not be synchronized, because Jenkins is sometimes slower

**Comment by shaowenchen** [comment]
yes，it needs a while to sync data.  you can filter data that isn't taged by DeletionTimestamp @harrisonliu5

**Comment by harrisonliu5** [comment]
There will be problems if you create a project with the same name as the previously deleted item @shaowenchen

**Comment by huanggze** [comment]
verified
