### ISSUE TITLE
Failed to run pipeline

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#908]
![image](https://user-images.githubusercontent.com/22350668/88385294-a605fc80-cde0-11ea-96b4-1baea6e9f18c.png)

**Comment by shaowenchen** [comment]
Running Multi-branch pipeline needs the parameter name, just like 

{"parameters":[{"name":"TAG_NAME","value":"v1"}]}

@harrisonliu5

**Comment by huanggze** [comment]
verified
