### ISSUE TITLE
Internal Server Error as confirming with faulty github token

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#913]
![image](https://user-images.githubusercontent.com/22350668/88391286-76f58800-cdec-11ea-96ee-f57ac368453b.png)

**Comment by huanggze** [comment]
Not fixed. When I input faulty token, still got 500.

I think it should return 400 (Bad Request)? 

Note that it is a low priority issue.

/cc @shaowenchen

**Comment by rayzhou2017** [comment]
should be fixed.

**Comment by huanggze** [comment]
verified
