### ISSUE TITLE
Got unexpected error when editing pipeline setting

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#914]
![image](https://user-images.githubusercontent.com/22350668/88391966-c7b9b080-cded-11ea-90f6-009a665b9027.png)

**Comment by shaowenchen** [comment]
The action editing repo is disabled after creating pipeline.  @harrisonliu5

**Comment by harrisonliu5** [comment]
Are there some keywords to determine whether the pipeline can be modified？ @shaowenchen

**Comment by shaowenchen** [comment]
![image](https://user-images.githubusercontent.com/43693241/88616674-57e64700-d0c7-11ea-8bbf-6fbfe01fab4a.png)

@harrisonliu5 the prompt information is not accurate.

**Comment by rayzhou2017** [comment]
what status is this one?

**Comment by huanggze** [comment]
verified
