### ISSUE TITLE
bugs for credentials list page of devops project

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#916]
**Describe the bug**
1. The list still shows all credentials when searching by name `kubeconfig`
![image](https://user-images.githubusercontent.com/49136171/88393159-ca1d0a00-cdef-11ea-883a-c81666218152.png)
2. Outliers are displayed in the search box when clicking refresh button
![image](https://user-images.githubusercontent.com/49136171/88393910-1452bb00-cdf1-11ea-99fa-31a5a1ffc8f3.png)
3. There is a problem with the paging function
![image](https://user-images.githubusercontent.com/49136171/88395354-86c49a80-cdf3-11ea-9aeb-afed8635f4d9.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere(2020-07-24)

**Environment**
allinone

/kind bug

**Comment by harrisonliu5** [comment]
kapis/clusters/gondor/devops.kubesphere.io/v1alpha3/devops/test011/credentials?start=0&limit=10&type=credential.devops.kubesphere.io%2F 

Error in data returned when there is a condition with a name or start condition of 10

/assign @shaowenchen

**Comment by shaowenchen** [comment]
Paging parameter：

?paging=limit=2,page=1  

It is necessary to add a query parameter.

**Comment by junotx** [comment]
@harrisonliu5 the up first and third bugs still exist:
1. can not search by name
2. paging problem is that there is a same credential on first and second page
![image](https://user-images.githubusercontent.com/49136171/89018153-fd125100-d34d-11ea-8152-c9a0f5832e92.png)
![image](https://user-images.githubusercontent.com/49136171/89018166-01d70500-d34e-11ea-9d53-6ff5e5f5a439.png)

**Comment by harrisonliu5** [comment]
This pr is just to modify the front-end paging and query fields, and the back-end code is not merged

**Comment by junotx** [comment]
verified
/close
