### ISSUE TITLE
Waiting time for pipeline to run is extremely long, 10 min avg.

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#917]
![image](https://user-images.githubusercontent.com/22350668/88393757-c3db5d80-cdf0-11ea-8a8f-3a1f2da479a1.png)

![image](https://user-images.githubusercontent.com/22350668/88393785-d2c21000-cdf0-11ea-8eb7-70d16deb1235.png)

![image](https://user-images.githubusercontent.com/22350668/88393793-d6ee2d80-cdf0-11ea-995b-e267cc617601.png)

**Comment by huanggze** [comment]
Seems that I need to wait for a while. Finally, I got pipeline run.

![image](https://user-images.githubusercontent.com/22350668/88394535-2da83700-cdf2-11ea-8c3a-f0a02b78eb8f.png)

**Comment by huanggze** [comment]
I don't know. It is very random. I repeated this issue, found it not working.  

![image](https://user-images.githubusercontent.com/22350668/88397107-10756780-cdf6-11ea-92f4-a13b7f620e0f.png)

**Comment by shaowenchen** [comment]
Can it be reproduced?  Maybe the connection between the node and api.github.com is unstable.

**Comment by huanggze** [comment]
Guess network is to blame. Now I increase my network bandwidth. I will close this issue until it reoccurs.
