### ISSUE TITLE
Some components' description are missing in Service Components list

### ISSUE THREAD

**Issue by FeynmanZhou** [kubesphere/console#918]
Need to gather the description for both Chinese and English:

![image](https://user-images.githubusercontent.com/40452856/88394893-c8087a80-cdf2-11ea-8a19-d9ae68dd8494.png)

**Comment by Sherlock113** [comment]
I cannot locate a place to add either ZH-CN or EN description for the component in locales files. For other components, I notice their capitalized keys of already exist so that they can be modified. How can I add description for them in locales files? @leoendless

**Comment by Sherlock113** [comment]
This is same as this one: https://github.com/kubesphere/website/issues/118. Is there a way to add description them?

**Comment by FeynmanZhou** [comment]
@Sherlock113 You can ask Leo in #sig-console directly.

**Comment by leoendless** [comment]
@zryfish Please provide descriptions for these components
