### ISSUE TITLE
Why no way to set branch discovery strategy for git repo?

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#919]
![image](https://user-images.githubusercontent.com/22350668/88395018-f8501900-cdf2-11ea-8c92-b811db431e0a.png)

![image](https://user-images.githubusercontent.com/22350668/88395072-10279d00-cdf3-11ea-9f7d-efc8ad106648.png)

**Comment by shaowenchen** [comment]
It is a feature.

/close
