### ISSUE TITLE
bugs of creating credentials for devops project

### ISSUE THREAD

**Issue by junotx** [kubesphere/console#929]
**Describe the bug**

1. No promt when credential ID repeats
1. No promt when credential ID is chinese or special characters

**Versions used(KubeSphere/Kubernetes)**
KubeSphere(2020-07-25)

/kind bug
/assign @harrisonliu5

**Comment by harrisonliu5** [comment]
you can try it later when the code pr

**Comment by junotx** [comment]
@harrisonliu5 After updating console，the first bug is solved, but the second still exists

**Comment by junotx** [comment]
verified
/close
