### ISSUE TITLE
yarn start然后报错，在线等哈

### ISSUE THREAD

**Issue by arraycto** [kubesphere/console#93]
vscode执行的时候，已经在我的电脑中配置了yarn的环境变量
yarn start然后报错如下：

PS G:\代码例子\daima\console> yarn start
yarn run v1.21.1
$ concurrently -k --raw 'yarn dev:client' 'yarn dev:server'
''yarn' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
文件名、目录名或卷标语法不正确。
''yarn' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
文件名、目录名或卷标语法不正确。
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS G:\daima\console>

**Comment by leoendless** [comment]
需要参考 https://github.com/kubesphere/console/blob/master/README.md#preparation 来搭建开发环境

**Comment by cabinhero** [comment]
你可以这样运行concurrently -k --raw 'yarn dev:client' 'yarn dev:server'

**Comment by PmcFizz** [comment]
凡是报
'yarn' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
文件名、目录名或卷标语法不正确。
''yarn' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
文件名、目录名或卷标语法不正确。

可以将package.josn 中的yarn start 命令 修改为

```concurrently -k --raw \"yarn dev:client\" \"yarn dev:server\" ```
试一下

**Comment by Caelebs** [comment]
> 凡是报
> 'yarn' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 文件名、目录名或卷标语法不正确。
> ''yarn' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> 文件名、目录名或卷标语法不正确。
> 
> 可以将package.josn 中的yarn start 命令 修改为
> 
> `concurrently -k --raw \"yarn dev:client\" \"yarn dev:server\" `
> 试一下

nice
