### ISSUE TITLE
multi cluster deployment UI problem

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#936]
**Describe the bug**
A self provisioner creates a multi-cluster project into two clusters. There are several problems
1. The project list shows zero in member cluster(cluster-01) which is incorrect since it is created in the cluster as you can see in the third screenshot.
2. The detailed project page shows only host info
3. the cluster dropdown menu does not work in the detailed project page

If log in using ws admin, everything is fine.

<img width="966" alt="Screen Shot 2020-07-25 at 8 19 32 PM" src="https://user-images.githubusercontent.com/28859385/88456931-d028ee80-ceb4-11ea-929b-7e129a9fc16c.png">
<img width="1237" alt="Screen Shot 2020-07-25 at 8 20 08 PM" src="https://user-images.githubusercontent.com/28859385/88456932-d61ecf80-ceb4-11ea-8fe1-895523578b23.png">
<img width="928" alt="Screen Shot 2020-07-25 at 8 20 53 PM" src="https://user-images.githubusercontent.com/28859385/88456933-db7c1a00-ceb4-11ea-8a58-8a7858314021.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev
Kubernetes: 1.15.12(host), 1.18.6(cluster-01)

**Comment by leoendless** [comment]
Problem 2 fixed by https://github.com/kubesphere/console/pull/939

**Comment by rayzhou2017** [comment]
How about the problems 1 and 3? Are they fixed?

**Comment by leoendless** [comment]
@wansir self-provisioner cannot access `kapis/clusters/shire/resources.kubesphere.io/v1alpha3/namespaces/fed-app/deployments?names=xxx`

**Comment by rayzhou2017** [comment]
verified
