### ISSUE TITLE
运行后localhost后的用户名和密码默认是啥？无法登陆啊

### ISSUE THREAD

**Issue by arraycto** [kubesphere/console#94]
运行后localhost后的用户名和密码默认是啥？无法登陆啊

**Comment by arraycto** [comment]
admin / P@88w0rd. 无法登陆，出现 Internal Server Error

**Comment by leoendless** [comment]
感觉像是 gateway server 的配置问题
可以参考这里：
https://github.com/kubesphere/console/blob/master/docs/access-backend.md
