### ISSUE TITLE
There is no way to look back credential content

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#944]
I want to look back the content of my credentials, but it seems no way to do that.

![image](https://user-images.githubusercontent.com/22350668/88473713-df5e7980-cf52-11ea-9e02-158cbe17ecde.png)

![image](https://user-images.githubusercontent.com/22350668/88473716-e4232d80-cf52-11ea-8c47-11c44b3374c0.png)

**Comment by Carlosfengv** [comment]
Content has a certain privacy, so it is not convenient to directly display in the details page

**Comment by huanggze** [comment]
Yes, but credential is just a k8s secret. Why treat them differently?

**Comment by LinuxSuRen** [comment]
Yes, it's just a k8s secret. But for DevOps, it could a separate component. Not like the k8s management system, I believe that does not provide this kind of level function is fair enough.

Anyway, it's totally possible to view the original content from the KubeSphere side.

**Comment by LinuxSuRen** [comment]
We will avoid users can view any secret from the DevOps platform. See https://github.com/kubesphere/console/issues/2893
/close
