### ISSUE TITLE
Pipeline failed for SVN based repo

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#946]
I chose SVN type as signle branch svn at the very beginning. After pipeline was over,  I get error saying Jenkinsfile not found. Though I do have Jenkinsfile in my repo (See the 3rd pic.)

![image](https://user-images.githubusercontent.com/22350668/88475133-cc05db00-cf5f-11ea-9822-c9b7628cc70a.png)

![image](https://user-images.githubusercontent.com/22350668/88475135-d7590680-cf5f-11ea-901b-9687ccb6d68d.png)

![image](https://user-images.githubusercontent.com/22350668/88475152-fe173d00-cf5f-11ea-9508-8b9fc302124b.png)

**Comment by huanggze** [comment]
Ok, nailed it. I changed SVN repo address from `svn://<svn_server>/<project>` to `svn://<svn_server>/<project>/trunk/`.

Is that right?

**Comment by shaowenchen** [comment]
yes .

signle branch -> /trunk or branch/test/
multi branch -> /
