### ISSUE TITLE
Drop-down options for SVN repo type is confusing

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#947]
Is it talking about "Single Branch SVN" vs. "Multiple Branch SVN"? Why "Single Branch SVN" and "svn"?

![image](https://user-images.githubusercontent.com/22350668/88475289-1a67a980-cf61-11ea-8f80-3d501519430b.png)

**Comment by shaowenchen** [comment]
`单分支 svn` needs the `svn://url/project/trunk`. It only providers a branch for the pipeline.

`svn` needs the `svn://url/project/`. It providers a multi-branch for the pipeline.
