### ISSUE TITLE
pipeline hung for 2h

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#951]
![image](https://user-images.githubusercontent.com/22350668/88478185-a5a06980-cf78-11ea-8ef7-a4f7efc343e9.png)

![image](https://user-images.githubusercontent.com/22350668/88478195-ae913b00-cf78-11ea-9407-b1b00606dbcc.png)

**Comment by shaowenchen** [comment]
Can you provide the environment, or describe how to reproduce it?

**Comment by huanggze** [comment]
Guess network is to blame. Now I increase my network bandwidth. I will close this issue until it reoccurs.

**Comment by huanggze** [comment]
Not fixed. Maven pod get stuck in the phase of ContainerCreating.

![image](https://user-images.githubusercontent.com/22350668/89120471-274c4600-d4e9-11ea-98ae-a8707a75151e.png)
