### ISSUE TITLE
Got 500 when confirming BitBucket account

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#955]
![image](https://user-images.githubusercontent.com/22350668/88479245-46deee00-cf80-11ea-8efc-dcce247e41dd.png)

![image](https://user-images.githubusercontent.com/22350668/88479280-7c83d700-cf80-11ea-9e36-4e3c0dfc971c.png)

**Comment by shaowenchen** [comment]
bitbucket server  not bitbucket.org

/close
