### ISSUE TITLE
email search does not work in ws member invitation

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#958]
**Describe the bug**
 As you can see below, email search does not work
<img width="682" alt="Screen Shot 2020-07-26 at 8 58 48 PM" src="https://user-images.githubusercontent.com/28859385/88479645-44ca5e80-cf83-11ea-9048-96f14a3b3e3d.png">
<img width="685" alt="Screen Shot 2020-07-26 at 8 58 59 PM" src="https://user-images.githubusercontent.com/28859385/88479646-48f67c00-cf83-11ea-8993-ec19bc20972d.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev

**Comment by rayzhou2017** [comment]
The problem still exists. Are you sure the PR is for this issue?

**Comment by leoendless** [comment]
We modified the placeholder. It should be searched by username now.

**Comment by rayzhou2017** [comment]
verified
