### ISSUE TITLE
Env var were not generated in Jenkinsfile out of SCM mode

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#962]
![image](https://user-images.githubusercontent.com/22350668/88480335-100cd600-cf88-11ea-8adb-9a7592e3b675.png)

![image](https://user-images.githubusercontent.com/22350668/88480353-1d29c500-cf88-11ea-8819-18cf69d08f76.png)

![image](https://user-images.githubusercontent.com/22350668/88480386-303c9500-cf88-11ea-8118-a9a0feea0dad.png)

**Comment by shaowenchen** [comment]
`This project is parameterized`  will not save in Jenkinsfile.

When you run the pipeline,  it will show.

/remove-kind bug
/remove-priority hight
/help wanted

**Comment by huanggze** [comment]
same issue here https://github.com/kubesphere/kubesphere/issues/2651

**Comment by huanggze** [comment]
verified
