### ISSUE TITLE
custom ws role gives more permission

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#966]
**Describe the bug**
A custom ws role with role management only, but the user can see project menu
<img width="685" alt="Screen Shot 2020-07-27 at 11 02 55 AM" src="https://user-images.githubusercontent.com/28859385/88499571-d6c07e80-cff8-11ea-8c34-e70d35da8fec.png">
<img width="772" alt="Screen Shot 2020-07-27 at 11 03 00 AM" src="https://user-images.githubusercontent.com/28859385/88499578-dcb65f80-cff8-11ea-944e-a803ae43cd2f.png">
<img width="488" alt="Screen Shot 2020-07-27 at 10 59 53 AM" src="https://user-images.githubusercontent.com/28859385/88499583-e17b1380-cff8-11ea-8df1-87c77dc3a365.png">

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0-dev

**Comment by wansir** [comment]
All members in the workspace can see the list of projects(filtered by user roles), `view projects` in authorization list means grant user view **all** projects. Even if a user cannot view all projects in the workspace,  he can still see the list of projects he has joined.

**Comment by rayzhou2017** [comment]
make sense. The user does see nothing in the project list before invited to some project.
