### ISSUE TITLE
Metrics graph for latest 12h doesn't show correctly

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#974]
![image](https://user-images.githubusercontent.com/22350668/88522020-629dcf00-d028-11ea-9602-248b881c4319.png)

![image](https://user-images.githubusercontent.com/22350668/88520457-2ec1aa00-d026-11ea-8d6c-fa06802ace69.png)

![image](https://user-images.githubusercontent.com/22350668/88520491-3719e500-d026-11ea-957d-f0d48dbfad58.png)

![image](https://user-images.githubusercontent.com/22350668/88520526-439e3d80-d026-11ea-987d-93f8b2496afb.png)

**Comment by leoendless** [comment]
What do these pictures mean?

**Comment by huanggze** [comment]
The graph should have a shape like below:
            _______
______|

**Comment by huanggze** [comment]
verified
