### ISSUE TITLE
locales missing

### ISSUE THREAD

**Issue by rayzhou2017** [kubesphere/console#980]
It shows several code IDs here
![Screen Shot 2020-07-27 at 5 36 14 PM](https://user-images.githubusercontent.com/28859385/88527412-cd063d80-d02f-11ea-8b2c-0fa617e97d6e.png)

**Comment by leoendless** [comment]
`ROLE_WORKSPACE_MANAGER`  has been updated to `ROLE_WORKSPACES_MANAGER` @Sherlock113

**Comment by Sherlock113** [comment]
Ok, I will add them and ask Turtle to have a look.

**Comment by rayzhou2017** [comment]
verified
