### ISSUE TITLE
cluster visibility setting is  not active

### ISSUE THREAD

**Issue by wanjunlei** [kubesphere/console#990]
**General remarks**

> This form is to report bugs. For general usage questions refer to our Slack channel
>        [KubeSphere-users](https://join.slack.com/t/kubesphere/shared_invite/enQtNTE3MDIxNzUxNzQ0LTdkNTc3OTdmNzdiODViZjViNTU5ZDY3M2I2MzY4MTI4OGZlOTJmMDg5ZTFiMDAwYzNlZDY5NjA0NzZlNDU5NmY)

**Describe the bug**
Create a workspace ws and has only one visibility cluster testing,
Change the  cluster visibility of testing renove the workspace ws
The request return ok, but workspace ws still has one  visibility cluster testing,

For UI issues please also add a screenshot that shows the issue.
![image](https://user-images.githubusercontent.com/53003665/88640722-da373100-d0f0-11ea-8903-2ad463ae9ce9.png)
![image](https://user-images.githubusercontent.com/53003665/88640744-e02d1200-d0f0-11ea-8cbd-223dede9b81d.png)
![image](https://user-images.githubusercontent.com/53003665/88640754-e3c09900-d0f0-11ea-8a06-d786ff6eba33.png)
![image](https://user-images.githubusercontent.com/53003665/88640776-e9b67a00-d0f0-11ea-93eb-005c6316bccf.png)
![image](https://user-images.githubusercontent.com/53003665/88641332-9db80500-d0f1-11ea-955b-8bd9345c4f3e.png)

**Versions used(KubeSphere/Kubernetes)**
KubeSphere: 3.0.0(2020-07-28)

**Comment by rayzhou2017** [comment]
any update?

**Comment by wanjunlei** [comment]
verified
/close
